### ISSUE TITLE
Could you add markers with voice notes similar to when you mark a book in an interesting phrase?

### ISSUE THREAD

**Issue by jalarrea** [TortugaPower/BookPlayer#10]
I have the hope that you can help me with that

**Comment by GianniCarlo** [comment]
looks like a great feature to have!

**Comment by pichfl** [comment]
I'm closing this issue to focus on the current release. It is a very interesting addition to BookPlayer and I hope we can implement this further down the road. Which is why I added it to the new [Roadmap](https://github.com/GianniCarlo/Audiobook-Player/projects/1#card-8545359)

**Comment by GianniCarlo** [comment]
closing this in favor of #127 which has more details on how this feature may work
