### ISSUE TITLE
Bug: Sleep timer starts when starting play from widget 

### ISSUE THREAD

**Issue by ssd713** [TortugaPower/BookPlayer#1004]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

When starting play from the last played book widget, the sleep timer starts running from 5 minutes, despite being toggled off in the app settings and in the widget settings. 

## Steps to reproduce the behavior
1. Start playback on a currently playing file from the last played book widget with sleep timer turned off in app and widget settings. 
2. Check in app to see that sleep timer is on.

**Comment by GianniCarlo** [comment]
@ssd713 this should be resolved in the latest version 5.1.1, please let me know if it continues happening
