### ISSUE TITLE
Bug: Can't rewind into previous chapter

### ISSUE THREAD

**Issue by maxxxxxdlp** [TortugaPower/BookPlayer#1005]
## Environment

 - OS Version: iOS 16.8.1
 - App Version: 5.0.9

## Description

When using rewind back headphone gesture or a button in the BookPlayer UI, it does not allow rewinding past the start of current chapter - this is a very annoying limitation

## Why this is a problem
Quite often, there would be a significant sentence, or a cliff hanger in the last few moments of the previous chapter - I can't rewind back without getting my phone out of the pocket.

## Steps to reproduce the behavior
1. Open a non-first chapter near beggining
2. Try using rewind gesture or UI button to go to previous chapter - doesn't work

If you are open to fixing this (or adding a pref to control this behavior) I can work on a pull request

**Comment by GianniCarlo** [comment]
Regarding this, are you using the volumes feature? I tried with a test books that is split between multiple mp3 files, and converted the in app folder into a volume, and seems to be working (also tested with the control inside the app)

If you're using volumes, then one thing that could be happening, is that there's a threshold that allows to skip back your the previous chapter / file (I think 5 secs or 10), so if the skip happens at 0:06, it will only rewind to the start of the chapter, and if you rewind again, it will rewind into the previous chapter, this is to cover users with big intervals for rewind skip, so they have a stop gap at the start of the chapter

https://github.com/TortugaPower/BookPlayer/assets/14112819/522e89dd-23fd-484c-913c-c04991b22036

If you're not using volumes, then from the app point of view, you're playing individual items/books, so rewinding into the previous book does not feel right, and in the app there's the '<<' control to jump to the previous item

**Comment by maxxxxxdlp** [comment]
That is it: I wasn't using the volumes feature!
Seems like I have been using BookPlayer a bit wrong all along 😊

This also explains why I wasn't seeing bookmarks between files

Thank you for your help
