### ISSUE TITLE
Bug: Changing chapters in a volume while paused doesn't update UI, inconsistent with folders

### ISSUE THREAD

**Issue by harrisi** [TortugaPower/BookPlayer#1008]
## Environment

 - OS Version: 16.6.1
 - App Version: 5.0.10-12

## Description

While a volume is paused, changing chapters with the left/right chevrons (angle brackets) changes the chapter but doesn't update the UI. If you press play, it will update and start playing the chapter that was switched to.

## Steps to reproduce the behavior
1. Start playing a volume
2. Pause
3. Press right or left chevron
4. Notice no visual update
5. Press play

If the volume is converted to a folder and the steps are reproduced, step three will switch chapters and start playing immediately, with the correctly updated UI.

**Comment by GianniCarlo** [comment]
v5.1.0 is live now with a fix for this, let me know if this persists
