### ISSUE TITLE
Updates to Wiki for 2023

### ISSUE THREAD

**Issue by moeadham** [TortugaPower/BookPlayer#1051]
## Feature request

- Your dev guide is just slightly out of date. I've made some updates to bring it up to speed.

## Narrative

- I can't make changes to the wiki directly, so I forked it. You can apply this patch:
https://github.com/moeadham/BookPlayer-wiki/commit/496e60a4e91ee3466322b59f66a267766b504052

**Comment by GianniCarlo** [comment]
Thanks again @moeadham ! I've updated the Wiki with the changes
