### ISSUE TITLE
Bug: Localisation of shortcuts not working

### ISSUE THREAD

**Issue by SimonHaas** [TortugaPower/BookPlayer#1057]
## Environment

 - OS Version: 17.2
 - App Version: 5.1.0-23

## Description

In the Shortcuts-app the localisation does not work despite the correct strings being present in the source code. I only tested with german.

Translation for "intent_lastbook_play_title"
https://github.com/TortugaPower/BookPlayer/blob/develop/BookPlayer/de.lproj/Localizable.strings#L300

The last string is displayed correctly.

![BAFF7B12-DE9E-442C-BF78-89AB0605A2FC_1_102_o](https://github.com/TortugaPower/BookPlayer/assets/22013217/1c1052e8-0f88-4352-9e3c-adff1eed8c88)

**Comment by GianniCarlo** [comment]
Thanks for the catch @SimonHaas , I only checked the pre-built actions that AppIntents provide in the shortcuts app if you search the app, and thought everything was good, I'll see if there's anything extra to be done to get the translations working when adding actions to a shortcut

![IMG_442222C50D7E-1](https://github.com/TortugaPower/BookPlayer/assets/14112819/3e5d3991-6917-440c-9038-86d8d6c4ab6c)

**Comment by GianniCarlo** [comment]
The fix is now live in the beta (link to join: https://testflight.apple.com/join/xLDneJXN)

**Comment by GianniCarlo** [comment]
This is now live on the AppStore
