### ISSUE TITLE
Cannot "Mark as Unfinished"

### ISSUE THREAD

**Issue by Dahveed7** [TortugaPower/BookPlayer#1076]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

After I've already listened to some tracks and I want to mark them as unfinished (since I'm listening to them again), I am unable to do so. 

## Steps to reproduce the behavior
1. Swipe Left on Folder and choose Options (Example 1)
![Example 1](https://github.com/TortugaPower/BookPlayer/assets/82148605/a28ce4d3-94f5-43c7-8b40-a51991e176da)

2. If all of the files are already checked (which they are—see Example 2), you should be able to Mark as Unfinished
![Example 2](https://github.com/TortugaPower/BookPlayer/assets/82148605/46a4fa35-71d4-4b6b-95c1-bcac3bda199a)
 
4. When Mark as Unfinished appears, it doesn't actually change the files. They still appear as finished.
5. What Mark as Finished appears, it is incorrect since all files appear as finished!
6. One cannot mark individual files as unfinished either. When I swipe left to mark a file as unfinished, nothing happens.

**Comment by GianniCarlo** [comment]
@Dahveed7 the `finished` flag functions independently of the completed percentage, so if all those books were below 99-100% you'd see the change between the checkmark, and just the progress wheel. I get that it's a bit confusing, and maybe it's time to represent the `finished` state with a different UI 🤔. If you wish to remove the checkmark when they are 'unfishined', from the selection options, you can tap on 'Jump to start', that will set the progress back to 0, and then you'll see the change between the finished states

**Comment by Dahveed7** [comment]
Thanks Gianni! That’s very helpful! Another question: In the screenshot below, all the files working the Findamentals are marked as finished, so why isn’t the folder marked that way as well?  On Jan 18, 2024, at 2:26 AM, Gianni Carlo ***@***.***> wrote:﻿
@Dahveed7 the finished flag functions independently of the completed percentage, so if all those books were below 99-100% you'd see the change between the checkmark, and just the progress wheel. I get that it's a bit confusing, and maybe it's time to represent the finished state with a different UI 🤔. If you wish to remove the checkmark when they are 'unfishined', from the selection options, you can tap on 'Jump to start', that will set the progress back to 0, and then you'll see the change between the finished states

**Comment by GianniCarlo** [comment]
Hmmmm good point @Dahveed7 I can't see the screenshot (looks like attachments on emails do not translate to GitHub) but I know what you mean, I'll have to check on the code, as last I remember it should be considering all items marked as finished, as having completed 100% so the folder progress should be showing as a checkmark

**Comment by GianniCarlo** [comment]
Following up here, I had this case also via email support. The issue was the folder that was stuck in a unsupported state (0s duration with items inside), to reset this, just create an empty folder inside of said folder, and delete it, and it should recalculate the duration, and the finished state should show up properly
