### ISSUE TITLE
Add using URL

### ISSUE THREAD

**Issue by EddyG50** [TortugaPower/BookPlayer#1077]
## Environment iPhone 13

 - OS Version: 17.1.2
 - App Version: [5.1.1-28

## Description

I’m trying to us Add in BookPlayer then Download From URL. I have an mb4 file posted in Dropbox. When I paste the URL in BookPlayer it recognizes the file, looks like it’s downloading, but the fil shows 0mb in library and does not play. I also tried to zip the .m4b file but no luck with that.

How do I post a .m4b file that can be downloaded with URL directly into BookPlayer?

This is a great app! Thanks!

## Steps to reproduce the behavior
1. Post .m4b in DropBox & copy URL
2. Go to Add > Download From URL in BookPlayer 
3. Paste URL
4. Add to Library

**Comment by GianniCarlo** [comment]
Hi @EddyG50 ! You have to make sure that the download URL is the actual book, many services like Google Drive, actually share first a link that shows the 'representation' of the file on the browser with the 'real' download button with the url in that page. If you can share the link, I can test it out also and see what I can find

**Comment by EddyG50** [comment]
Thanks Gianni,
 
Below are links to both the .m4b and .zip - in both DropBox and Google Drive:
I'm using a small test file I created in Audiobook Builder App. I've also tried with a larger file.
I'm happy to archive it anywhere it can downloaded into BookPlayer from.
 
 
DropBox:
- m4b - [ https://www.dropbox.com/scl/fi/o3j73jtsqdby4tfzrnjqr/Test.m4b?rlkey=v8uk00ifbg61996ypo178jr1m&dl=0 ]( https://www.dropbox.com/scl/fi/o3j73jtsqdby4tfzrnjqr/Test.m4b?rlkey=v8uk00ifbg61996ypo178jr1m&dl=0 )
 
- .zip - [ https://www.dropbox.com/scl/fi/2euk64x6xd1abanutpb3m/Test.m4b.zip?rlkey=5pterrend5amv9d10swk7220w&dl=0 ]( https://www.dropbox.com/scl/fi/2euk64x6xd1abanutpb3m/Test.m4b.zip?rlkey=5pterrend5amv9d10swk7220w&dl=0 )
 
 
Google Drive:
- .m4b - [ https://drive.google.com/file/d/1GNXplVBecXLRzYzAN6GYRprcqg81yeed/view?usp=sharing ]( https://drive.google.com/file/d/1GNXplVBecXLRzYzAN6GYRprcqg81yeed/view?usp=sharing )
 
- .zip - [ https://drive.google.com/file/d/1C7FqlJin4kywk6bAl0mWsvNvIqHNsam6/view?usp=sharing ]( https://drive.google.com/file/d/1C7FqlJin4kywk6bAl0mWsvNvIqHNsam6/view?usp=sharing )
 

Thanks for your help!
 
Best,
Ed

-----Original Message-----

**Comment by GianniCarlo** [comment]
@EddyG50 I'm attaching a screen recording of what I mean with the first dropbox link

https://github.com/TortugaPower/BookPlayer/assets/14112819/ccbd4616-8af8-42c6-9d16-fff216f0d537

the real URL is this one: https://uc861dec133211a56ac502a73235.dl.dropboxusercontent.com/cd/0/get/CLnUe-UwdvQG9oE2LJrmF8dGRhr52lJoAb_JrPd-3Hmw2NZBYiPe_cvcpWpBPmxG8stYFy2txu3qpTVfNbd0G3Nu45apwLmIUkZw4Jxc-PrFJ317-9KUYjE5GsybbbhlayT47-ssIPdNu4BUBe1I785eVcWzPk_DC4D6aVgTGuJcOg/file?_download_id=4158192634913145799206147867187571916080962063796429567114007557&_notify_domain=www.dropbox.com&dl=1

which I'm guessing expires after some point, but if you are constantly sharing from your dropbox to the app, you could just have the third-party app installed in your phone, make sure you're signed in, and they have an integration to the native Files app to expose all their files, and we have an integration to read from the Files app, so you can import them that way

**Comment by EddyG50** [comment]
Hi Gianni,
 
Thanks for the video. I tried several times with no luck, I always received the same error.
Have you been able to get it to work?
 
I also tried downloading BookPlayer to my desktop (Mac Studio M2 Ultra - OS 13.5).
I imported a book and tried the "Share" function but nothing I clicked on was active (except edit Extensions which I did to include BookPlayer).
 
What is the "Download from URL" function work with optimally?
How do you get it to work?
 
Please let me know if you have any further suggestions of how I can supply a link that others will be able to use to download using the "Download from URL" function in BookPlayer.
 
Thanks so much for your support!
 
Ed


-----Original Message-----
