### ISSUE TITLE
Bug: Delete file from File app

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#1094]
I delete a file from the Files application, go into the application and it prompts me to import a new system folder “.Trash” in which the deleted file lies

![image](https://github.com/TortugaPower/BookPlayer/assets/15727518/920b7d00-32ef-4d90-b629-fc0aa2985f71)

**Comment by rastaman111** [comment]
the Trash folder is like a recycle bin, the same system as Inbox

**Comment by GianniCarlo** [comment]
@rastaman111 the fix is live on the beta in TestFlight, I have to get around fixing some performance improvements around ram usage on app launch before submitting v5.2.3, I'm looking into introducing Realm so we can eventually remove CoreData as the local database for the app

**Comment by GianniCarlo** [comment]
@rastaman111 yup not thrilled about the size increase either, but setting aside what is usually said about Realm's performance being better when executing queries, actually for me it's more about the interface and ease of use. I'm working on adding the sync tasks into a proper DB, as it was an error on my part to use UserDefaults, the previous library we used, used UserDefaults as well and I thought it was fine, but managing arrays in there is not pretty, and also very limiting if we want to merge tasks for the same item. 
For more context, my target is to eventually use SwiftData for the DB (minimum deployment iOS 17), so just thinking of setting up another `.xcdatamodel` file and the backing `NSManagedObject` classes for CoreData, it feels like adding more tech debt, as SwiftData APIs are much more similar to Realm's, I would rather go from CoreData → Realm → SwiftData, than adding more into CoreData (other than performance improvements to existing code)

**Comment by rastaman111** [comment]
@GianniCarlo 

I can’t say about speed, but I know for sure that if you do all the tasks to save the background, productivity increases and the UI does not freeze

**Comment by GianniCarlo** [comment]
The fix for this is now live on the AppStore
