### ISSUE TITLE
Bug: no chapter marks (cloud playback)

### ISSUE THREAD

**Issue by fs1209** [TortugaPower/BookPlayer#1097]
## Environment

 - OS Version: 17.3
 - App Version: 5.2.2-34

## Description

When adding a new book to one of my synced devices, it uploads to the cloud and is visible on all other devices. When I play this new book on one of the other devices without downloading it first, there are no chapter marks.

## Steps to reproduce the behavior
1. add a new book and wait until it's uploaded
2. wait until the upload is done and the new book shows up on the other device
3. hit play on the other device => no chapter marks

**Comment by GianniCarlo** [comment]
@fs1209 after hitting play, when it finishes buffering and starts playing, do the chapters load? (see screen recording attached)


https://github.com/TortugaPower/BookPlayer/assets/14112819/3f365012-c855-4b59-81f8-28631c6193b7

**Comment by fs1209** [comment]
On my iPad it's not working at all.
The book opens at the correct position and when I hit play, the button changes into the pause button, but no playback.
After a few seconds BookPlayer crashes and won't start again.

https://github.com/TortugaPower/BookPlayer/assets/150681522/adde084b-b484-483f-abaf-121c647ed47d

**Comment by GianniCarlo** [comment]
@fs1209 thanks for the recording, that crash is definitely preventing the file from loading properly when it finishes buffering, I'll look into the crash and report back

**Comment by fs1209** [comment]
After playing back on my iPhone I gave it another try on my iPad and it showed the attached error message and now the app at least does not crash anymore.

![IMG_0040](https://github.com/TortugaPower/BookPlayer/assets/150681522/2d766cc7-d050-47ce-9856-2a2da8f31723)

**Comment by GianniCarlo** [comment]
@fs1209 can you retry playback on your iPad? from the 'Metadata' part of the error, that means that the app's request to refresh the remote URL failed (or was cancelled from the message), when retrying, it will try to fetch it again if the current one is expired. Let me know if it throws the same error

**Comment by fs1209** [comment]
It's always the same cycle:
1. Start playback from cloud
2. BookPlayer crashes...
3. ...and keeps crashing directly after startup
4. After some time BookPlayer is not crashing anymore and shows the "Metadata"-Message (only once)
5. after dismissing the message, BookPlayer will start
6. until I hit the play button again...

**Comment by fs1209** [comment]
I've sent a feedback via TestFlight...

**Comment by GianniCarlo** [comment]
@fs1209 I just saw it, thanks, it's a race condition when updating the last played book info, in another thread it's in the middle of creating the chapters in the DB, so the CoreData context is being saved with incomplete information for the chapters. I'll update the beta later today with a fix for this

**Comment by GianniCarlo** [comment]
@fs1209 the beta is updated, please let me know how it goes

**Comment by fs1209** [comment]
I've updated to the latest beta and now it's working.

**Comment by GianniCarlo** [comment]
The fix for this is now live on the AppStore
