### ISSUE TITLE
Bug: Constantly losing the current playing item / progress

### ISSUE THREAD

**Issue by AsyncMoksha** [TortugaPower/BookPlayer#1098]
## Environment

 - OS Version: iOS 17.3
 - App Version: 5.11-28

## Description

I had been using the app for many months and every time I entered the app I had always been able to access exactly where I left off, the currently playing item is always at the bottom of the screen. Never once did it drop the progress. 

But ever since a recent update about a month ago, it's very often that when I entered the app, there's no current playing item at all. I have to go to the playlist and scroll through thousands of files in order to find which file I last played and tap on it.

## Steps to reproduce the behavior
1. Play something
2. Switch to any different app. Wait for a few days maybe
3. Re-enter the app, observe that the previously playing item is not there. In order to find it you have to go to your playlist and find which ones are already played and which ones aren't

**Comment by GianniCarlo** [comment]
hey @AsyncMoksha ! can you share the debug info from within the settings → Support → Share debug information. Also, is this reproducible if you kill the app from the app switcher and launch it again?

**Comment by AsyncMoksha** [comment]
Sure, here’s the debug info. 

I’ll try the kill app thing, but it will take a while because the problem doesn’t show up immediately. 
[bookplayer_debug_information.txt](https://github.com/TortugaPower/BookPlayer/files/14235081/bookplayer_debug_information.txt)

**Comment by AsyncMoksha** [comment]
I restarted the app and observed for a few days, the issue seems to have gone away. Closing ticket. Thank you

**Comment by AsyncMoksha** [comment]
Hi Gianni, this issue happened twice after I closed the ticket. I’m therefore reopening it. I’ll send the debug info file to your email instead of posting here for privacy reasons.

**Comment by AsyncMoksha** [comment]
Hi @GianniCarlo , to update the previous comment - the app lost the progress again today, this is after only 2 days, it looks like the interval is getting shorter. It takes quite a bit of time to locate the precious progress each time this happens, so hopefully this issue can be fixed.

Thank you.

**Comment by AsyncMoksha** [comment]
I wonder if this is related to the app version update as I saw a new version was updated yesterday. 

But I remember using the app for over 6 months previously without losing progress once, this frequent loss of progress issue is quite new.

**Comment by AsyncMoksha** [comment]
Yep, same steps. Thank you!

**Comment by DarkDevX** [comment]
I have exactly the same issue

**Comment by szmark02** [comment]
Unfortunately I have the same issue, and it’s quite annoying. The last position is saved, but I have to open the book and find the unfinished chapter manually, almost every time. If it’s been played very recently and no other audio was played during the two session, it seems to work fine. 

Thanks in advance for checking

**Comment by GianniCarlo** [comment]
I forgot to follow up here, this bug was actually a quite simple fix (included in [this PR](https://github.com/TortugaPower/BookPlayer/pull/1141)), I'll release a new version sometime this week (or at the latest the next one). In the meantime, for the specific scenario when you're listening to a book split into multiple files, you can workaround this by converting the folder containing the split audiobooks into a volume, so the app knows to treat them as a single book (progress is recorded differently between regular books and volumes, so you'll have to skip ahead once you convert it)

**Comment by GianniCarlo** [comment]
The update is now available in the AppStore, please let me know if it still happens @szmark02 @DarkDevX @AsyncMoksha

**Comment by szmark02** [comment]
Seems to be fixed, thanks so much for the continued support on this great app!On 26 Jun 2024, at 19:50, Gianni Carlo ***@***.***> wrote:﻿
The update is now available in the AppStore, please let me know if it still happens @szmark02 @DarkDevX @AsyncMoksha

**Comment by GianniCarlo** [comment]
thanks for the confirmation @szmark02 !
