### ISSUE TITLE
Auto sleep timer resets on new chapter

### ISSUE THREAD

**Issue by banny-list** [TortugaPower/BookPlayer#1104]
## Environment

 - OS Version: 17.3.1
 - App Version: 5.2.2

## Description

Auto sleep timer resets on new chapter. If all chapters in book are less then timer value - it will never stops.

## Steps to reproduce the behavior
1. Enable autosleep timer in settings
2. Enable sleep timer greater than chapter time remaining 
3. Check that on new chapter beginning timer has reset

**Comment by rishatl** [comment]
Hey, I'll take it upon myself, make me assignees, pls

**Comment by GianniCarlo** [comment]
The fix for this is now live on the AppStore
