### ISSUE TITLE
Bug: App doesn’t open on Apple Watch.

### ISSUE THREAD

**Issue by Immusama** [TortugaPower/BookPlayer#1114]
## Environment

 - OS Version: [14.3]
 - App Version: [5.2.5/4/3]

## Description

The new updates of the app don’t open on Apple Watch anymore. It works fine on the IPhone however no longer on the watch. 

Version 5.2.2 works, newer versions do not.

**Comment by GianniCarlo** [comment]
@Immusama sorry about the late response, I tested on my device, and it's currently working, between versions 5.2.2 and 5.2.6, we didn't touch any watch related code, but I've seen the watch getting stuck with third party apps (i.e. widgets won't even show either), at that point, I go to the iPhone, to the Watch app, and from the list of apps, make sure that BookPlayer is in the 'Installed on Apple Watch' section, and it doesn't have any spinning loading wheel next to it, if there's a spinning wheel, you can tap on it, remove it and tap on Install again, you wouldn't lose any info, as right now the Watch app is just a companion to the main app
