### ISSUE TITLE
Bug: App keeps crashing

### ISSUE THREAD

**Issue by Strawberri9109** [TortugaPower/BookPlayer#1118]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

Just got the app yesterday and it worked fine for a few hours, but then suddenly stopped playing and when I looked, I was no longer in the app. 
Opened it again, started playing my audiobook and then it did it again and now just keeps happening over and over again. It only plays a few seconds, sometimes minutes, at a time before it crashes again.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by Jeralynn** [comment]
Hi, I'm also a long time user of BookPlayer on ios (presently 17.3.1 on iphone 12 mini) and started reading a new book (it's probably been a couple months since I last used it) and it now crashes repeatedly.  I tried another app to read the book, no problems so it's definitely something with BP.

**Comment by GianniCarlo** [comment]
yes, this has been haunting me for some weeks now, still looking into why the OS watchdog is killing the app, and at what point memory usage is spiking, will update when I have more info

**Comment by Jeralynn** [comment]
@GianniCarlo Fixed! Thank you so much!

**Comment by GianniCarlo** [comment]
Thanks for the confirmation @Jeralynn 🚀
