### ISSUE TITLE
Bug: Selecting a new book leads to app crashing everytime.

### ISSUE THREAD

**Issue by toduyemi** [TortugaPower/BookPlayer#1121]
## Environment

 - OS Version: 17.3.1
 - App Version: 5.2.6

## Description

Whenever I select/switch to a new audiobook. The book plays for ~10 seconds. Then the app crashes. Once reopened, and I hit play, the book plays normally so long as its playing the book that was playing when it crashed. This happens every single time without failure.

## Steps to reproduce the behavior
1. 
2. 
3. 

I love the app and have been using it for almost 2 years now. This problem has only risen in the last week or soo!

**Comment by GianniCarlo** [comment]
@toduyemi can you confirm if the same happens on the latest version? (v5.2.7), the app was being killed due to a memory usage spike, and it could be related to this

**Comment by toduyemi** [comment]
@GianniCarlo Nope all clear! The crash has not happened in a while :) Thanks!
