### ISSUE TITLE
Bug: Recent Books widget does not react to tap on the book

### ISSUE THREAD

**Issue by oluckyman** [TortugaPower/BookPlayer#1126]
## Environment

 - OS Version: 17.1.2
 - App Version: 5.2.7

## Description

There is a widget Recent Books
![image](https://github.com/TortugaPower/BookPlayer/assets/642673/b2574da0-a5a2-4eb1-a49e-38ccf46814da)
The UI suggests that I can tap a specific book to start listening to it. (And as I remember, it was so maybe half a year ago).
But now, when I tap a book, nothing happens.
It only opens the BookPlayer and starts playing the current book if I tap the little logo in the top right corner.

## Steps to reproduce the behavior
1. Add Recent Books widget with 4 books
2. Tap any of the books on the widget
3. Nothing happens.

**Comment by GianniCarlo** [comment]
@oluckyman this has been a long time coming, but now on v5.4.0 this works as expected. The problem was how the core services were being created in the app, and how it was tied to the view lifecycle, so if the app wasn't running in the background, the core services weren't ready for playback, and it wouldn't start until the app was launched

**Comment by oluckyman** [comment]
Just updated the app and restarted iPhone.
Now the widgets are empty blank squares.
And there is no BookPlayer in the list of widgets 🙄

**Comment by GianniCarlo** [comment]
@oluckyman thanks for reporting this, it looks like it's an issue with the SDK ([link to dev forums](https://forums.developer.apple.com/forums/thread/762688)) and it always crashes on iOS 17, Apple says it is fixed on Xcode 16.1 beta 3, but there's a workaround I can try now. I'm reopening this issue and will ping back when I have a beta available for testing

**Comment by GianniCarlo** [comment]
I was able to test both the crash and the fix on a device I had with iOS 17, I'll submit directly to the AppStore as a hotfix

**Comment by GianniCarlo** [comment]
@oluckyman the fix is now live on v5.4.1, let me know if that works

**Comment by oluckyman** [comment]
It works! 🎉 thank you!
