### ISSUE TITLE
Bug: ImportOperation.swift

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#1127]
## Environment

 - OS Version: [e.g. 17.4.1]
 - App Version: [e.g. 5.2.7]

What do I do to get this crash:
1. I want to import a file from the device directory
2. Select the desired file and click "Open"
3. The Import screen opens with my file
4. Wait a minute and click “Finish”
5. It turns out to be a crash

On the line fatalError("Fail to move file from \(currentFile) to \(destinationURL). Error: \(error.localizedDescription)")

You may ask why we are waiting exactly a minute?
Since if you immediately click “Finish”, this bug is not reproduced. I think that this is due to waiting and an internal failure occurs

I noticed this bug a long time ago (a year ago), but I didn’t know how to reproduce it

**Comment by rastaman111** [comment]
I think this is due to the fact that the files are stored in tmp during import, and this is a temporary directory

**Comment by rastaman111** [comment]
I tested on the simulator and monitored the tmp folder in real time. The file is stored there for literally 40-50 seconds and deleted

**Comment by GianniCarlo** [comment]
Hi @rastaman111 ! interesting, for reference, the files used to be put into the app container in the Documents/Inbox folder, and they pretty much stayed in there until cleared by the app. 

The URL is now looking like this `file:///private/var/mobile/Containers/Data/Application/D0863F00-31DB-43A6-8517-F2FEDD2B3C32/tmp/com.tortugapower.audiobookplayer-Inbox/001.mp3`, not sure when this was changed (could be iOS 17?), but I think a quick solution to this, would be to preemptively move the files from the tmp directory to the Inbox folder, and pass the new URL to the import manager

**Comment by rastaman111** [comment]
Привет, это было и раньше когда импортируешь через документПикер, а если когда через симулятор и просто переносишь файл то сразу в Инбокс

**Comment by rastaman111** [comment]
Hello, this happened before when you import through documentPicker, and if when through the simulator and just transfer the file, then immediately to Inbox

**Comment by rastaman111** [comment]
There is a cool FlEX library, it shows the entire internals of the application and can be monitored in real time

**Comment by GianniCarlo** [comment]
@rastaman111 I've updated the beta with a fix from #1134, from my tests it looks to be fixed, please let me know if it still happens to you (link beta: https://testflight.apple.com/join/xLDneJXN)

**Comment by rastaman111** [comment]
@GianniCarlo Hello

I checked the assembly, there is no more bug 👍🏼

**Comment by GianniCarlo** [comment]
Nice! Thanks for checking @rastaman111

**Comment by GianniCarlo** [comment]
This is now live on the AppStore
