### ISSUE TITLE
Audio Bookshelf support?

### ISSUE THREAD

**Issue by mehgcap** [TortugaPower/BookPlayer#1128]
## Feature request

I'd love to see support for [Audio Bookshelf](https://www.audiobookshelf.org/).

## Narrative
Audio Bookshelf is a self-hosted repository for audio books and podcasts. It would be great to see support for it added to this project. The [API](https://api.audiobookshelf.org/) seems fairly comprehensive, letting the app pull a user's libraries, sync reading positions, and more.

## Design

This is the tricky part. I'm no UX designer, so my thoughts are probably not helpful.

Since Audio Bookshelf has its own library system, I would suggest a new tab on the bottom of the screen. Change the current Library tab to Local Library, and add a tab called ABS Library next to it, if the user has added ABS in the settings.

This tab will prompt the user to sign in if the app can't authenticate, or alert that the server can't be reached if, well, the server can't be reached. Assuming all is well, the app will present the user with their most recent view. Users in ABS can have multiple libraries, which hold books and podcasts. Books can be organized by author, series, and narrator.

When in a library view, I suggest a search field and title header, in the usual iOS style. In the top right would be buttons to sort by author, series, or narrator. Each item in the table would have swipe actions to go to that item's author, narrator, or series view. If an item is a book, additional actions for play/pause, download, delete from local storage, and so on would be added.

When play or pause is tapped, the app should silently try to sync with ABS's playback position record for the current title. If the server is out of reach, such as if the user is not on the right network, save the playback position locally and try syncing periodically, or next time the app is opened. A setting should control whether to alert the user if the playback position can't be synced. If the user only ever uses this app on one device, they'll never care about syncing their playback position with the server anyway.

I wish I were better with Xcode and Swift, so I could take a crack at this. I know me, though. I won't get far, nor would I have the time to do this right.

**Comment by harrisi** [comment]
Hey, thanks for the suggestion! This is a duplicate of #1042. We should have an update soon so follow that issue to be notified.

**Comment by mehgcap** [comment]
Sorry for the duplicate. I searched for Audio Bookshelf before I wrote this, to see if someone else had already suggested it. I somehow missed that issue.

**Comment by harrisi** [comment]
You probably searched with a space ("audio bookshelf") like I did initially. GitHub can't figure out the similarity it seems! :)
