### ISSUE TITLE
Bug: ...Won’t install on Apple watch 3 watchOS 8.8.1

### ISSUE THREAD

**Issue by chrisvaldivia** [TortugaPower/BookPlayer#1136]
## Environment

 - OS Version: 8.8.1
 - App Version: 5.2.7-45. iOS 17.4.1

## Description

The app Won’t install on Apple watch 3 watchOS 8.8.1

## Steps to reproduce the behavior
1. Install app on iphone
2. Try to install app on apple watch 3, loading icon, nothing happens
3. Try to install on watch directly, receive an error message ‘Unable to complete request. Try again later.’

**Comment by chrisvaldivia** [comment]
I also tried the latest version on TestFlight 5.2.8-48 and it won’t install on apple watch

**Comment by GianniCarlo** [comment]
@chrisvaldivia yeah I've seen this while testing and deleting the main app, but it's not related to client side code, meaning that the OS is in charge of installing it on the Watch, and we have no control over how this process works. What has worked for me, is to first on the iPhone, on the Watch app, go to the apps list at the bottom, and make sure that there's no spinning wheel next to BookPlayer, if it is, just tap it, and it should just say Install. Then turn off and on the watch (I've also sometimes turn off and on the phone as well), and try tapping Install again

I'm closing the ticket, as it's not something we can do control, but feel free to follow up
