### ISSUE TITLE
Post-sync trouble: Error AVPlayerItem: The requested URL was not found on this server.

### ISSUE THREAD

**Issue by antonrang** [TortugaPower/BookPlayer#1142]
## Environment

 - OS Version: 17.5.1
 - App Version: 5.2.8-49

## Description

After syncing between two devices, files uploaded from the first device play on the second, but files uploaded from the second device do not play on the second, instead giving a dialog with “Error AVPlayerItem: The requested URL was not found on this server.”

I have an iPhone 14 Pro and an iPad Pro. I have been using BookPlayer on the iPhone for some time. Tonight, I created an account for syncing (via the iPhone) and then installed BookPlayer on the iPad, connecting to the same account.

I then added a number of files to the iPad (M4B files, from my iCloud Downloads folder). I sorted them into folders.

After waiting for synchronization to complete on both devices, I was able to see all of my files on the iPad. I can play the files which were added on the iPad, and also the files which were synced from the iPhone.

However, while I can now see (the names of) all files on the iPhone, the files (and folders) added from the iPad show up as generic folder and file icons. Trying to play them results in the error, as above. The debug log shows the broken files with an [x]. (Before accessing the containing folder, they were listed as “Remote only items” in the debug log.)

I have a hunch that perhaps this is related to having sorted (moved into new folders) the files after they were added but before the sync had completed, but am not sure.

Is there a way to force resynchronization? Logging out & back in has no visible effect.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
Hi @antonrang ! first thanks for your support!, second, yes you're right, last week I encountered this bug (a race condition) where if you import  files specifically to a folder (and not to the root), the local sync service will fail to create a hard link to the backing file, and when uploading the metadata, it won't find the reference to the local file and will continue on to the next item to be synced. This was fixed [in this PR](https://github.com/TortugaPower/BookPlayer/pull/1141/files#diff-020596a8c6775d57973628f1dea90141795ae44c89b1c2adced2d447eeb9c949R406-R410) last week, I've been meaning to put out a new version with this, I was just in the middle of finishing some other work, probably going to cut that short to get this out as soon as possible.

Regarding forcing resync, can you send me the debug info to my email (gcarlo89@hotmail.com)? I can mark the remote only items as not synced in the DB, and next time you log out and sign back in, it should start uploading the files

**Comment by GianniCarlo** [comment]
This issue should be fixed, but please feel free to follow up here or via email if anything comes up
