### ISSUE TITLE
Bug: sync stopped working

### ISSUE THREAD

**Issue by fs1209** [TortugaPower/BookPlayer#1152]
## Environment

 - OS Version: iOS 17.5.1; iOS 18 beta 3; iPadOS 18 beta 3; macOS 14.5
 - App Version: 5.3.1-52

## Description

Usually I listen to my books on one device. I noticed, that the upload queue builds up as well as the last sync timer.
I've tried the following with no success:
- added a new device and did the initial setup, but no books appeared in my list
- logged of all devices and logged in with my primary device, upload queue still no progress
- logged of all devices, deleted my account and created a new account (on my mac). Then I've added one small book (10mb) - not syncing.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by fs1209** [comment]
Thinking about it - taking the playback position/book on my other devices - it must have stopped around the time I've changed my subscription from monthly to yearly, could this be the cause?

**Comment by GianniCarlo** [comment]
Hi @fs1209 ! thanks again for your support! can you help me out and email me the debug information for the devices? (from Settings → Support section → Share Debug information), just a heads up that on Mac (running the iPad app) it wouldn't allow exporting a file, so the alternative was to provide the copy / paste option

Re changing the subscription, I'll look into it, I don't think it should be the cause, but it's worth ruling that out

**Comment by fs1209** [comment]
Hi GianniCarlo,
I've done the same test on my iPad ant when I tap on "share debug information", I get the message "You are not subscribed"...

**Comment by GianniCarlo** [comment]
it looks like locally we do have the state as subscribed (we fetch that data directly from RC)

<img width="686" alt="Screenshot 2024-07-18 at 8 07 08 AM" src="https://github.com/user-attachments/assets/1d4c13d2-ba2e-443e-af15-b9185f7c5d58">

And on the server the auth middleware has the wrong data, so yeah I think you're right on the subscription change, probably we got the new event, and the profile was put in a weird state

<img width="571" alt="Screenshot 2024-07-18 at 8 07 58 AM" src="https://github.com/user-attachments/assets/0877fd3d-e764-4de2-b86f-c5b50420e723">

Can you share the email that shows up in the Profile tab? I can track things down in our database with that. Thanks again for reporting the issue

**Comment by fs1209** [comment]
frank.schmidt@mac.com

**Comment by GianniCarlo** [comment]
Found the issue @fs1209 , RevenueCat never sent the event to our servers about the subscription change, and apparently we shouldn't expect them to, I think we can circumvent this on our servers, by querying the user status from RevenueCat if the API is hit for a user that has been a subscriber before, and it's not currently enabled for some reason, and we backfill the information missing

<img width="1274" alt="Screenshot 2024-07-18 at 8 37 09 AM" src="https://github.com/user-attachments/assets/ca7c2b29-87ac-40e3-99e9-7d0c652e4f54">

I have manually added the event to our database, so your profile should be working again, please let me know if the issue continues though

**Comment by fs1209** [comment]
Upload is working again, but the books do not appear on the other devices.
Currently I've three devices and uploaded one book on each device (three different books).
Is there a way to see what is stored on the server side?

**Comment by GianniCarlo** [comment]
@fs1209 let me know if the issue persists, or if there's anything else I can help with

**Comment by fs1209** [comment]
waiting for the upload of all the books to be completed, I'll let you know when it's done.
Maybe one additional question: I'm currently uploading the books from my mac, but the actual playback state and history is still on my iPhone. What will happen when I activate the sync on my iPhone after the upload from my mac is done? Is the cloud state updated from my iPhone, or the other way around?

**Comment by GianniCarlo** [comment]
@fs1209 that is a good point, right now it will be overwritten, I need to put in a check like we have for the last played, where we compare the remote vs local last-played timestamp, and only update if the remote is newer. We should also spawn update tasks when the local timestamp is newer than the remote one (I was looking through the logic, and the changes are a bit more complex than I'd like, I have to think it through a bit more)

Regarding the files, I was looking through the backups we do, and was able to locate your files, and the metadata associated to them. I can put them back and associate it to your current profile, let me know if I should go ahead and do that

**Comment by fs1209** [comment]
It would be great, if you restore those files.
Do I need to stop the sync from my mac before the restore?

**Comment by GianniCarlo** [comment]
@fs1209 preferably yes, I'll get right on it then, and ping back when it's done so you can check

**Comment by fs1209** [comment]
okay, sync is stopped...

**Comment by GianniCarlo** [comment]
alright, it should be ready @fs1209 , if you pull down to refresh, or sign out and sign back in, it should show the entire list, and allow you to stream the files too. Let me know if it works correctly

**Comment by fs1209** [comment]
It's working now, many thanks!

**Comment by GianniCarlo** [comment]
that's great news! let me know if anything else comes up

**Comment by fs1209** [comment]
Unfortunately there is another issue concerning sorting. I manually sort my books and when I rearrange my books, the sorting gets reset to an older state - maybe the state you‘ve recovered?

**Comment by GianniCarlo** [comment]
@fs1209 Re sorting, yeah that could definitely be a part of the issue, but if you rearrange them again, are they not staying with that order? We can open up another issue to keep track of it and I'll look into it
