### ISSUE TITLE
Bug: book order is reset at restart

### ISSUE THREAD

**Issue by fs1209** [TortugaPower/BookPlayer#1157]
## Environment

 - OS Version: iOS 17.5.1; iOS 18 beta 3; iPadOS 18 beta 3; macOS 14.5
 - App Version: 5.3.1-52

## Description

After the restore on server side, the sorting gets reset to the state after restore.
After changing the order of the books all looks fine, a lot of tasks are in the sync task list and get processed.
On next restart, the order is reset to the one after restore.

## Steps to reproduce the behavior
1. Change order of the audiobooks
2. wait for the sync to be finished
3. restart the app => order is changed back

**Comment by GianniCarlo** [comment]
@fs1209 thanks for the bug report! I'll look into it later today

**Comment by GianniCarlo** [comment]
@fs1209 this should be fixed now, it was an issue on the server ([commit with the fix](https://github.com/TortugaPower/bookplayer-api/commit/5e7ae4e3a336c8ab5f398315fa0eb26947923d7b)) introduced as part of the changes that added the default values for the orderRank field, and it was basically setting the order back to 0 

Please let me know if you keep seeing this issue after updating the order of some items @fs1209

**Comment by fs1209** [comment]
looks good, many thanks!

**Comment by GianniCarlo** [comment]
awesome! thanks for the confirmation
