### ISSUE TITLE
Add a button for Play until next chapter

### ISSUE THREAD

**Issue by arthurbrunborg** [TortugaPower/BookPlayer#1160]
## Feature request

- I would like an extra button (this can be disabled by default) that I can click to start playing a chapter of the audiobook but automatically enable sleep timer until the next chapter. 
- Currently you need to click play, then click sleep timer, then click until next chapter. I would love to only have one button for that process.

**Comment by GianniCarlo** [comment]
@arthurbrunborg this should already be possible in a way. From Settings → Player Controls → Auto Sleep Timer, toggle that on, and if you're on v5.3.1 or later, you should be able to set the sleep timer once, and next time you hit play, it'll arm the sleep timer to the same last choice you had

Let me know if that works

**Comment by GianniCarlo** [comment]
I'm closing based on my comment, but feel free to continue the thread
