### ISSUE TITLE
Bug: 5.3.5 crashes on launch 

### ISSUE THREAD

**Issue by daxmonson** [TortugaPower/BookPlayer#1176]
iPadOS 18

5.3.5 

Today’s update crashes on launch. Have rebooted a few times  and it’s still crashing,

**Comment by GianniCarlo** [comment]
Thanks for reporting the issue @daxmonson , I'm pausing roll out and looking into this

**Comment by daxmonson** [comment]
@GianniCarlo  might be related to NSLayoutConstraint 

these might be relevant to help track it down:

{"imageOffset":50668,"symbol":"-[NSLayoutConstraint isActive]","symbolLocation":0,"imageIndex":20}

{"imageOffset":4170548,"symbol":"-[UITabBarController initWithNibName:bundle:]","symbolLocation":164,"imageIndex":11}

{"imageOffset":94948,"symbol":"objc_exception_throw","symbolLocation":88,"imageIndex":7}

no worries, I’m sure you’ll sort it out, hope that helps.

**Comment by GianniCarlo** [comment]
@daxmonson turns out the tabbar is no longer shown at the bottom on iPadOS 18, I have a fix for it in the referenced PR. Going to check the widgets disappearing before submitting a new version

**Comment by GianniCarlo** [comment]
the new version has been submitted, will follow up once it's available

**Comment by GianniCarlo** [comment]
v5.3.6 is now live, @daxmonson please let me know when you get the chance if the issue is solved

**Comment by daxmonson** [comment]
@GianniCarlo It’s working again. Thanks for the rapid update.

**Comment by stephenkoo** [comment]
Hi, I believe this update is now causing crash on launch for iOS 18.0.
Updated to the latest version on the App Store 3 days ago coincides with when it started crashing on launch.

Thank you @GianniCarlo for the amazing app.

**Comment by GianniCarlo** [comment]
@stephenkoo is the crash happening on v5.3.6 too? could you open a separate ticket so we can keep track of it and debug it?

**Comment by stephenkoo** [comment]
Ah @GianniCarlo my bad, It seems fixed in the latest iOS 18.0 update, I just had a similar issue with Instagram since it updated so I realized it's not a BookPlayer issue.
