### ISSUE TITLE
Bug: Widget is broken in last update

### ISSUE THREAD

**Issue by sohate** [TortugaPower/BookPlayer#1177]
## Environment

 - OS Version: iOS 17.6.1
 - App Version: 5.3.5

## Description

The Widget is broken. I can't find the widget in widgets section and it looks like this right now:

<img width="414" alt="Screenshot 2024-09-11 at 12 32 29 jpeg" src="https://github.com/user-attachments/assets/fb321a9d-24b7-4d6c-b33c-5283bc45fe57">

**Comment by GianniCarlo** [comment]
the new version has been submitted, will follow up once it's available, thanks for the report @sohate

**Comment by GianniCarlo** [comment]
v5.3.6 is now live, @sohate please let me know when you get the chance if the issue is solved

**Comment by GianniCarlo** [comment]
Got confirmation via mail support that this is now working. Feel free to continue the thread if the issue persists after updating the app
