### ISSUE TITLE
iOS 18 Dark Mode Icon

### ISSUE THREAD

**Issue by GinSoakedBoy** [TortugaPower/BookPlayer#1184]
## Feature request

- A dark icon that automatically turns on when Dark Mode is enabled.

## Narrative

- Currently there is a dark icon but it requires a subscription to use and it does not activate automatically with the new iOS 18 feature of switching to dark icons when Dark Mode is enabled.

**Comment by GianniCarlo** [comment]
I've been looking into this, it'll be fairly easy to do it for the regular icon. I believe there's a way to enable it for the other alternate icons, but I'll have to refactor from where they are getting the image data, besides having the actual dark mode image for the alternate icons. I'll include the first part in the next release though

**Comment by GianniCarlo** [comment]
@GinSoakedBoy this is now live in the AppStore, as mentioned in my previous comment, it only covers the main app icon for now
