### ISSUE TITLE
Let the app combine several M4B files into one book while keeping chapters beneath intact

### ISSUE THREAD

**Issue by wighnut** [TortugaPower/BookPlayer#1185]
## Environment

 - OS Version: [18.0]
 - App Version: [5.3.6]

## Description

Not a bug report (i assume). Sometimes there are audiobooks with different covers per chapter or per part. If I would like to keep them it's necessary to split the book into multiple M4B files. Say there's a book with 2 parts, A and B, with a cover each. If I'd like to use both I import both parts (with each having multiple chapters within them).

### Issue
If I import both parts they don't get combined into the same book/entry. Even if they have the same title/album name in the metadata. If I then want to combine the two parts it deletes the actual chapters below the part. This behavior is different in Apple Books. There it assumes it's the same book if the Album tag is the same.

My assumption is that BookPlayer is not designed to handle parts and chapters at same time (i.e. One book, two parts, 10 chapters each). Instead it assumes you have one M4B file with chapters beneath OR multiple M4B files (one for each chapter) and then combine them within the app.

Is there a solution to this. Or could it even be on the roadmap?

## Steps to reproduce the behavior
1. Create book in AudioBookConverter
2. Make it 2 parts with each part having chapter of their own
3. Give them the same Album tag
4. Import them to BookPlayer
5. End up with having two identically named files in Library.

**Comment by GianniCarlo** [comment]
yep, I have this on my radar too, I have this use case when downloading audiobooks as parts from Audible, I took a stab at fixing this some time ago, but it proved to be a little more complex than I anticipated, I'll revisit this in the near future

**Comment by GianniCarlo** [comment]
@wighnut this is now live in the AppStore in v5.4.0. Please let me know if you experience any issues in the new version

**Comment by wighnut** [comment]
@GianniCarlo Tested it just now. Works perfectly. Chapters as well as covers are preserved upon combination of parts. Many thanks.
