### ISSUE TITLE
Local Apple Watch Downloads

### ISSUE THREAD

**Issue by ysakols** [TortugaPower/BookPlayer#1196]
## Feature request

- As an end user of BookPlayer, who has a lot of local files, I would like to be able to: 1. Download local files to my Apple Watch so I can listen to my audiobooks without my phone being present. 2. Have a sync functionality that allows me to sync my listening progress between my Apple Watch and my phone. 

## Narrative

there is no application with good native support today for listening to audiobooks on an Apple Watch. Audible is a closed system. Apple Music experience is subpar. Libby has no Apple Watch app.

it would be a killer feature if I could listen to audiobooks locally on my Apple Watch so that when I go on long runs or head out without my phone, I can still listen to my audiobooks. In addition, it would be really valuable if BookPlayer, Apple Watch and BookPlayer iOS have a sync functionality.

## Design
- I think the download to iPhone functionality would be more or less straightforward. The WorkOutDoors app has a nice function called Send to Apple Watch that is a push based sync.

**Comment by GianniCarlo** [comment]
@ysakols there is now an open beta to test this feature for existing subscribers (as the first iteration is meant to pull the data straight from our servers). There are still some issues that I'm working on, but it's in a good enough state for testing and finding any other issues I may have missed (link to join: https://testflight.apple.com/join/cuvGt3cy)

**Comment by GianniCarlo** [comment]
Marking this as complete as it was released on v5.5.0
