### ISSUE TITLE
Ability to sync libraries between BookPlayer app on Mac and the app on iOS? 

### ISSUE THREAD

**Issue by kb1-3** [TortugaPower/BookPlayer#1204]
## Feature request

- Apologies if this function already exits but I can't seem to find a tutorial on how to set this up so I'm assuming it doesn't already exist. I would like the ability to sync my libraries between my MacBook and my phone.

## Narrative

- I have a ton of audiobooks I'd like to add to my Book Player library but it's a pain to add several books at a time on my phone. It's much easier to add and organize books on my MacBook.

**Comment by GianniCarlo** [comment]
@kb1-3 this can already be accomplished with the pro features and the cloud sync (i.e. once subscribed, on the Mac app you upload the books, and it should be made available on your phone after they are uploaded)

**Comment by Tekl** [comment]
Does it use iCloud?

**Comment by GianniCarlo** [comment]
@Tekl no, we roll our own servers, there's a longer explanation on the original ticket though for the cloud sync feature
