### ISSUE TITLE
Bug: Doesn't start

### ISSUE THREAD

**Issue by melifarodev** [TortugaPower/BookPlayer#1211]
## Environment

 - iOS Version: 18.1
 - App Version: 5.4.1

## Description

Doesn't start. Screenshot is below
![IMG_8804](https://github.com/user-attachments/assets/761ea962-30e2-4ba0-b934-7780b5d78edb)

## Steps to reproduce the behavior
Hello. Application doesn't start.
1. Download from AppStore
2. Press the icon
3. Get error

**Comment by GianniCarlo** [comment]
@melifarodev thanks for posting this, this is actually something that I was hoping someone would report, as I was seeing a crash for some people right after the app launched (on the last version I removed the automatic crash so the message could be read and I could debug it). Does this keep happening if you force quit the app from the app switcher and open it again?

**Comment by melifarodev** [comment]
Hi!

1. Run the app. Get the message. Click OK. Check app switcher - there is no running BookPlayer
2. Run the app. Get the message. Force quit the app from the app switcher. Run the app and get Error again

**Comment by GianniCarlo** [comment]
@melifarodev Ive been banging my head against the wall trying to figure out the root issue. Could you help me joining the open beta (link: https://testflight.apple.com/join/UkvZEdCc) so I can debug better? That build only adds some breadcrumbs alongside the launch process, so I can inspect if there's something amiss on the first setup of the app. I also added a cleanup of the database file before the crash in that type of error, just in case if that is a possible patch to the issue

**Comment by melifarodev** [comment]
Hi again!

I have good (?) news. I've installed beta version and it crashed after run. But the second, third, fourth and later attempts are successfully. Now the app works!

**Comment by GianniCarlo** [comment]
@melifarodev thanks for the confirmation, yeah that's definitely the patch that I mentioned, so the DB file was malformed when it was first created, and removing it so the app recreates it, fixes the issue. I'm adding a second button to the error alert to make the recovery more seamless, as I can't track or reproduce this issue so it's definitely a race condition somewhere in the startup process. I'm thinking of doing a rewrite of the app to just use SwiftUI after my work on the watch app, and do away with so much legacy code the app has from these past 7-8 years

**Comment by GianniCarlo** [comment]
v5.4.2 is out now, with the option in the error alert to apply the patch that was in the beta. #1214 may be related to this, but I'll continue tracking it in its own ticket
