### ISSUE TITLE
Bug: github roadmap: is missing

### ISSUE THREAD

**Issue by blipspings** [TortugaPower/BookPlayer#1215]
## Environment

 - web (github.com)

## Description

under faq, when going to roadmap, the link:

https://github.com/TortugaPower/BookPlayer/projects/1

is 404'ing.

## Steps to reproduce the behavior
1. go to https://github.com/TortugaPower/BookPlayer/projects/1
2. see 404 page.
3. done.

**Comment by GianniCarlo** [comment]
Thanks @blipspings ! the link has been updated now
