### ISSUE TITLE
Bug: add "audiobook builder.app" to the list of known m4b creation apps to the faq.

### ISSUE THREAD

**Issue by blipspings** [TortugaPower/BookPlayer#1216]
## Environment

 - web:
 - github:
 - https://github.com/yermak/AudioBookConverter/releases
 - header: _How to combine MP3 files into M4B audio books_

## Description

Audiobook Builder, by Splasm Software. macOS. Shareware/Trial/Commercial. https://www.splasm.com/audiobookbuilder/

(i am a fan and user, but not the developer or affiliated with any way, other than a fan.)

**Comment by GianniCarlo** [comment]
Thanks for sharing @blipspings ! I've updated the Wiki
