### ISSUE TITLE
FYI: Okusana copycat app

### ISSUE THREAD

**Issue by vardecab** [TortugaPower/BookPlayer#1217]
Hi! 

First of all, thanks for creating BookPlayer — it's really great 🫡

I wanted to bring to your attention that I've discovered an application that appears to be using your GPL v3.0 licensed code without complying with the license terms.

- Copycat app: [Okusana](https://apps.apple.com/us/app/audio-book-player-okusana/id1507653226)
- The app appears to be a modified version of your work but is being distributed without source code and includes added advertisements for monetization (+ subscription to remove ads)

**Comment by GianniCarlo** [comment]
Thanks @vardecab ! I did report this to Apple some time ago, but they only put me in contact with the other developer to "resolve" the issue, after the other developer didn't respond, Apple did threatened to remove the app if we can't come to an amicable solution, but it's been months now with no resolution. 

The worst thing is that I previously had the key for Sentry hardcoded, so I actually started receiving crashes for their app, I provided this evidence to Apple, but nothing. 

Not sure if I'm missing something of how this process should go, but in the meantime I created an LLC and transitioned my dev account to an organization account, with the hopes that someday I have enough money to have some legal counsel on what to do in these cases

**Comment by vardecab** [comment]
Yea, no idea — never had such problem myself so I cannot help :( I can only keep my fingers crossed that (soon!) that app is gonna be removed (+ dev's Apple Account banned) and such things won't happen in the future. One could probably try to contact Google/AdMob to restrict the account and thus the money generated by that app, but that probably won't happen, similar to how Apple responded.

**Comment by GianniCarlo** [comment]
No worries, I appreciate you finding and bringing this up though, I'm closing the ticket, but anyone feel free to chime in with any recommendations, I honestly thought that Apple would crack down rapidly on this type of cases
