### ISSUE TITLE
Bug: ...

### ISSUE THREAD

**Issue by Mailolipop** [TortugaPower/BookPlayer#1222]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description
The beta test is over and I can't access the audiobooks or the app

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
Hi @Mailolipop ! You can always download the AppStore version if the beta build expires, at this point there are only two betas running, the first one about adding jellyfin support, the second one about the watch app stand alone playback, but these are on separate test groups from the main one I usually use, to better isolate any feedback for those builds, if you'd like to test any of them let me know and I can provide the links
