### ISSUE TITLE
Incorrect encoding of Polish characters

### ISSUE THREAD

**Issue by F-RX** [TortugaPower/BookPlayer#1223]
## Environment

 - OS Version: 18.1.1
 - App Version: 5.4.2-76

## Description

Incorrect encoding of Polish characters in file names and chapter subtitles.

![IMG_4993](https://github.com/user-attachments/assets/062da081-04e6-4a7e-af51-656cfde38f5b)
![IMG_4994](https://github.com/user-attachments/assets/5b2f7ace-c1f6-46ea-b30e-a5411c6bef99)

![IMG_4992](https://github.com/user-attachments/assets/7b498679-1cb0-4313-9ec5-a4d211e2ce5d)

**Comment by GianniCarlo** [comment]
@F-RX this has been reported before, but it is usually the audio file having corrupted encoded metadata. You can test by overwriting the title / author with the correct text, and it should display them correctly. I'm closing the ticket, but feel free to continue the thread
