### ISSUE TITLE
Bug: The app displays in Simplified Chinese if the system language is set to Japanese

### ISSUE THREAD

**Issue by AndyRightNow** [TortugaPower/BookPlayer#1226]
## Environment

 - OS Version: 18.1.1
 - App Version: 5.4.2-76

## Description

The app displays in Simplified Chinese if the system language is set to Japanese.

## Steps to reproduce the behavior
1. Change the system language to Japanese
2. Open the app and the language is in Simplified Chinese

**Comment by GianniCarlo** [comment]
I've added Japanese as a supported language but with the English text, this should fix the system for some reason using the Chinese translation. It would be good to add a real Japanese translation, if anyone wants to contribute with this, just ping me

**Comment by GianniCarlo** [comment]
this is now live on the AppStore, please let me know if it still happens @AndyRightNow

**Comment by AndyRightNow** [comment]
> this is now live on the AppStore, please let me know if it still happens @AndyRightNow

@GianniCarlo thanks for the swift response and it now shows English on my iPhone with Japanese system lanaguage!
