### ISSUE TITLE
Web import or multifile selection via ios Files

### ISSUE THREAD

**Issue by q6276270** [TortugaPower/BookPlayer#1231]
## Feature request

I am honestly not sure whether this is intended behavior or a bug. I cannot select multiple files to import, which makes it practically impossible to import my audiobooks at the moment.

## Narrative

I've uploaded the files with vlc's webserver interface.
Steps:
1. open bookplayer
2. Add files
3. "Import Files"
4. "On my iPhone"
5. Select VLC (probably any other app directories will yield the same result)
6. Search for the audiobook
There is no option to select multiple files. I can only tap on one and it goes straight into the "Import" UI which lets me continue the import, cancel or delete the selection and cancel.
Also when searching for a part of the name of the files there is an option to list "Contains <search_string>" but when I tap that the result list is empty.

## Design
I'd either like an option to select and import multiple files audiobooks or alternatively and probably better:
A web interface like in VLC to upload multiple files audiobooks easily. I think this has been proposed in https://github.com/TortugaPower/BookPlayer/issues/362 and even attempted by https://github.com/TortugaPower/BookPlayer/pull/491 .

I would even like to help implement it but I just discovered my Mac is too old to run the current XCode.

**Comment by GianniCarlo** [comment]
Hi @q6276270 ! the import files interface basically opens the Files app, it's not intuitive, but they do support multiple file selection by tapping the '...' button in the top right corner, and then tap on 'Select'.

You can do the same by going directly to the Files app, and then choosing and from the share button, tapping BookPlayer

**Comment by q6276270** [comment]
It's not possible to select while searching for files apparently. I already guessed that it wasn't under your control, thanks for the help anyway.
I'm still hoping for the webserver upload feature in the future though.
