### ISSUE TITLE
3.0.0 beta: Add drag hint on player

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#196]
The skip back/forward  rework isn't apparent, we need to add a hint to let the user know that it's no longer a button

**Comment by pichfl** [comment]
I had scheduled this for 3.1 in #158  but it seems logical to move this to 3.0. I adjusted the original ticket as necessary.

Todo: 
- Hint forward/rewind  if a user has never used it by nudging the artwork to the right
- Resize Play / Pause button action with the cover artwork, limiting the interactive area to the cover.
- Register taps on the jump icons to nudge the artwork to the side without actually navigating
