### ISSUE TITLE
Improve feedback for drag & drop

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#202]
Besides the vibration we should also highlight the cell in case the playlist creation would be stopped. 

I think this might also highlight an error in the current implementation that makes it hard to abort the playlist creation.

**Comment by GianniCarlo** [comment]
For v4.0.0 we switched from a third-party library to the native way of dragging and dropping things in iOS due to performance issues. We also had to remove the create-playlist-on-drop interaction, due to the new interaction limitations, so this ticket no longer applies
