### ISSUE TITLE
VoiceOver support

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#205]
We should check VoiceOver and general accessibility guidelines for the application. @dunkelstern might be able to help with this.

**Comment by ryantstone** [comment]
I'd like to contribute to this ticket. When are you targeting having this released?

**Comment by pichfl** [comment]
It would be wonderful if you could help us with this. We plan to release the next minor version (3.1) in September, given we can finish the open issues in time. 

Please start your effort from the `next/minor` branch which contains everything we already put into place for 3.1.

**Comment by ryantstone** [comment]
Wanted to give an update, main library, and mini-player are done. I'm working my way through the main player at the moment.

**Comment by pichfl** [comment]
@ryantstone if there is anything that needs clarification feel free to contact me directly, I'm pretty sure most of that VC is my code and I can feel my mishaps pressing down on me.

**Comment by GianniCarlo** [comment]
closed by #233 , thanks @ryantstone !
