### ISSUE TITLE
3.0.0-5 `Add` cell is sometimes obscured by the mini player

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#208]
Reported by @alexdnt33 
Bug currently happening in the `PlaylistVC`

Screen recording:
https://drive.google.com/open?id=0B3-Zy3XlVezaeGVSenh4S3c0aWt2S1JqeERWSFdLbnFwb0lV

**Comment by pichfl** [comment]
It seems the offset I introduced for the Library doesn't apply to the playlists.
