### ISSUE TITLE
Batch "Move to playlist"

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#210]
Using drag & drop is rather exhausting when doing for a large number of files or far down a list. 

- We should introduce a way to move a file to a playlist using the swipe menu
- Importing files via AirDrop should ask if you want to put the files into a playlist
    - If possible, we should detect the currently open playlist and put files there
    - If not, we should ask the user where to put the files
- Expose playlists as folders inside iTunes file sharing to handle sorting there?

We could also introduce a right swipe action which allows people to "select" multiple files for which to select an action. I can create a mockup for that.

**Comment by pichfl** [comment]
This is a bit bigger than expected, mostly because UITableViewCells are so good at custom touch interactions. Moving to 3.2.0

**Comment by Guy27** [comment]
I think when moving large amount of files using the swipe menu might be just as exhausting.
we should consider a 'move to playlist' button that show checkboxes for non-playlist items, and a done button that will ask for an existing playlist/new one.

I second the requirement to import files to an existing playlist, it's super useful :)

**Comment by GianniCarlo** [comment]
We've expanded a bit on this idea, and the bulk edit that @pichfl is envisioning, is similar to how [Things 3](https://itunes.apple.com/ae/app/things-3/id904237743?mt=8) does it

**Comment by GianniCarlo** [comment]
solved by #289
