### ISSUE TITLE
Create playlist on import

### ISSUE THREAD

**Issue by martinklepsch** [TortugaPower/BookPlayer#223]
* **Feature Request**
* Importing 10 files results in those 10 files being listed in the library individually.
* I've seen you already have some ideas around making playlist creation easier (#210) so just throwing this idea in as another alternative: When importing multiple files, provide an option to move all files into a playlist right after import.

**Comment by pichfl** [comment]
That is an excellent idea, especially considering the upcoming improvements to our importer made for #209

To keep our backlog clean and focussed, I'm closing this ticket and adding it to our roadmap.
