### ISSUE TITLE
Fine grained playback speed settings

### ISSUE THREAD

**Issue by bensaufley** [TortugaPower/BookPlayer#224]
**Feature Request**: allow custom speed (within reason). I mostly use the Audible app right now, and it supports speeds similar to BookPlayer. Google Play's app, which I just tried out, allows increments of `.05` anywhere within a range, using a slider UI. It's great and solves one of my biggest problems—I've had a few books that are too slow for 1.5x, but too fast for 2x. Even just supporting 1.75x would be cool, but a custom speed slider would be 👌

I'd love to contribute if you think this is something doable. Swift isn't really my primary language, but I've done a little.

FWIW my environment is iOS 11.4.1 on an iPhone 7 Plus, running BookPlayer 3.0.0. Please let me know if there's anything else I can let you know.

**Comment by pichfl** [comment]
Wonderful idea! Whilst not on our Roadmap yet, we discussed replacing the speed (& sleep timer) controls with a custom interface that allows for the fine adjustments you're looking for. 

If you want to tackle this yourself and need help getting into the project, feel free to contact me personally via Twitter or Email. We would be happy to get you involved. 

Either way, I'll provide interface mockups for this that match the overall look and feel of the new UI.

To keep our backlog clean and focussed, I'm closing this ticket and adding it to our roadmap.

**Comment by pichfl** [comment]
<img src="https://user-images.githubusercontent.com/194641/53362790-3b2a6a80-393b-11e9-9013-b6843c0960a1.png" alt="" width="375">

This is how the new interface could look like. A slider which locks in 1/8 steps from 0.625 to 2.625. Tapping the speed icon or swiping down will dismiss the card. Tapping outside the card will do so as well. 

If someone want's to tackle this, please contact us so we can coordinate the necessary changes to be made to the overall player UI discussed in #281

**Comment by bensaufley** [comment]
Just coming back to this. Not really able to contribute right now unfortunately (Swift not being really an area of expertise and time being limited). But I'd add that it'd be nice to go above 2.5x. I had to switch back to the Audible player for a book recently so that I could do 3x (some readers are just so slow!). Audible and Libro.fm both support 3x speed; Audible supports 3.5x, even. Can't support every use case, obviously, but worth considering the way to best support the broadest number of use cases without overcomplicating the UI and the code.

(Also I like your choice of example book with the mockup @pichfl)

**Comment by pichfl** [comment]
Whelp. I'm not sure if 3.5x speed makes for a nice listening experience, but looking at the mockup above, we could easily use slightly different increments and squeeze the ticks on the slider a bit closer to make 3x or more available. Thanks for the follow up.

(Can't wait for the follow-up and for the BBC series. And for Michael Sheen to read more books, his narration style is magnificent)

**Comment by DarkXaHTeP** [comment]
Hi! Could it be possible to add 2.25x and 2.75x as well in addition to 1.1x and others?

**Comment by GianniCarlo** [comment]
This is solved by the new playback speed controls

**Comment by bensaufley** [comment]
I saw! They're great! Thanks!
