### ISSUE TITLE
Handle importing files as a batch operation

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#225]
Each batch of files should:
- Prompt the user `(if files > 1)` to create a playlist which will contain such books
- Alphabetically sort the imported files

With this approach, it'll be easier to handle the feedback shown to the user with the new cell that @pichfl provided

**Comment by timkelty** [comment]
I would also be great if either:

- When it prompted you to name the playlist, it used the first file's name.
- and/or – allow copy/paste of filenames, so I can go back and rename the playlist

Basically I end up with files like "Some Really Long Title I Don't Want to Type on Phone - Part 1, Some Really Long Title I Don't Want to Type on Phone - Part 2, etc." - and would like getting them into named playlists easier.

**Comment by GianniCarlo** [comment]
Great suggestion @timkelty I'll definitely do point 1. Expanding on your idea, how about having that text pre-selected too as the initial state, so it'll be faster for the user to just clean it if he wants something different 🤔.

Point 2 I'm not really sure how we'd go about it 🤔 you could elaborate more on point 2 if you wish, to know how you envision that in particular

**Comment by timkelty** [comment]
> Expanding on your idea, how about having that text pre-selected too as the initial state, so it'll be faster for the user to just clean it if he wants something different 🤔.

Yep!

As for copy/paste – that is really a separate request…I just mean it would be nice if you could somehow get the text from the filename. Either long press to bring up copy dialog, or somewhere in a menu.

**Comment by GianniCarlo** [comment]
closed by #237
