### ISSUE TITLE
Zip support

### ISSUE THREAD

**Issue by atomicguy** [TortugaPower/BookPlayer#228]
Feature request

Currently import zip files is not supported.

Importing a zip file (a compressed folder of mp3) would be helpful. A bonus would be if they could be automatically put into a playlist.

**Comment by GianniCarlo** [comment]
Hi @atomicguy , I fear that supporting zip files will introduce unwanted complexity (e.g. different sublevel of folders and files). Currently we're working on https://github.com/TortugaPower/BookPlayer/issues/225 which will cover the bonus point you mentioned.

You're more than welcome to contribute with this feature in particular.
This should:
- Uncompress the zip
- Recursively iterate the folder(s) and its contents to get all the items
- Post a notification via `NotificationCenter` with the name `.libraryOpenURL` and the `fileURL` for each file in the `userInfo`

**Comment by GianniCarlo** [comment]
I'm closing this issue for now, but feel free to continue the conversation 👌

**Comment by GianniCarlo** [comment]
Regarding point 2 I was thinking that all files be extracted and discard the hierarchy to keep things simple

**Comment by GianniCarlo** [comment]
Regarding point 1, I agree, we could just drop them

**Comment by GianniCarlo** [comment]
Regarding point 3, I was thinking if it made sense that we had an alert/modal view detailing the new things 🤔 ala Discord whenever we release a new version. Not thrilled about the idea since we'll be repeating the info from the release notes, but some people might not read them

**Comment by pichfl** [comment]
Yeah, people don't read release notes. They won't read these dialogs either 😁

**Comment by GianniCarlo** [comment]
haha true, I don't think I've ever read one of those alerts of Discord

**Comment by GianniCarlo** [comment]
@atomicguy I wouldn't mind giving you some pointers, if you'd like, we could talk over at [Discord](https://discord.gg/B5vY2Sh).

At a macro level you'd have to:
1.- Find (most likely) a dependency via Carthage that handles unzipping files
2.- The class `ImportOperation` handles the processing of files. Here you'd have to check if it's a zip file
3.- unzip the file, get the files (disregarding the folder hierarchy)
4.- add the new files into the array of files to be processed
4.- let the loop continue with the files

There's a `for` loop that I think would be good to do it in a recursive way

**Comment by GianniCarlo** [comment]
Completed by #258
