### ISSUE TITLE
iPad version

### ISSUE THREAD

**Issue by Wiredframe** [TortugaPower/BookPlayer#230]
Hi there, I just stumbled upon this awesome app. Unfortunately I don't have an iPhone and would like to listen to my Audiobooks on my iPad. 

Is an iPad version planned?

**Comment by GianniCarlo** [comment]
hi @Wiredframe ! our current design didn't have the iPad in mind 🤔, and the blown up proportions might detract from the experience 🤔. What do you think @pichfl , have you tried it on an iPad?

@Wiredframe worst case scenario, you could run the project and enable the iPad support since it's just a checkbox

**Comment by Wiredframe** [comment]
Ok, thanks 😃

**Comment by pichfl** [comment]
First class iPad support is definitely on my ToDo list. [Our roadmap](https://github.com/TortugaPower/BookPlayer/projects/1) has an entry in the "later" column.

I'll close this ticket and add it to our Roadmap. I'll reopen it once we have a chance to work on this.

**Comment by pichfl** [comment]
+1 from @steve4jobs4 for this. 

----  

We are planning for this, but the iPad UI is a big task and it requires a lot of work both on my design side as on the code side. We also wanted to have a sync solution in place before we actually implement it so moving from one device to the other as seamless as possible.

@GianniCarlo and I did discuss about moving the UI forward and adding the sync later but haven't reached a proper conclusion yet.

**Comment by morpheus12** [comment]
@pichfl can we support you with beta testings for ui or something like that (e.g. with testflight)?

You've created the best app i've seen the last 12 months. Now it seems like that i'll be able to replace the real ipod. If i can support with testing: very welcome!

**Comment by pichfl** [comment]
@GianniCarlo does the development, I mostly do the design of the app. Testing is nice, but to really support us we need people join into the development effort, @GianniCarlo can only do so much on his own. 

I'm glad you enjoy what we managed to get done so far, it is the best part of the day to read about people enjoying what we created here. Enjoy and tell other people 🙂

**Comment by XiaoHippo** [comment]
My kids use their iPads to listen to audiobooks and it would be so much better if this app had native iPad support.

**Comment by Delamcode** [comment]
Any updates?

**Comment by GianniCarlo** [comment]
not yet, still working on the branch v5.0.0 for the next major version on cross-device sync

**Comment by GianniCarlo** [comment]
v5.0.0 is finally released, there are big fundamental changes on how the app works, so we'll be checking if any issues come up that need to be addressed
