### ISSUE TITLE
Toggle between chapter duration and total audiobook duration by tapping on the time label

### ISSUE THREAD

**Issue by boettges** [TortugaPower/BookPlayer#231]
Hello,
first of all I love BookPlayer. It is finally an iOS audiobook player that just makes sense. I love the easy import via the Files aoo or even Airdrop. Huge thumbs up 👍

Just a minor usability improvement:

It would be nice to be able to **tap** either the current timestamp (left) or the total chapter duration (right) …
![chapter_runtime](https://user-images.githubusercontent.com/20265197/45037796-10341d80-b060-11e8-94a8-3f8dcef2eec7.jpg)

… to **toggle** to display the total runtime of the audiobook.
![total_runtime](https://user-images.githubusercontent.com/20265197/45037854-3d80cb80-b060-11e8-894a-884f5006287b.png)

In that case the progress bar should recalculate its position to the percentage-wise accurate position in the entire audiobook instead of the progress in the current chapter.

Maybe the total duration needs an icon to distinguish it from the chapter runtime.

Thanks a lot in advance and thank you for the tremendous work!

**Comment by pichfl** [comment]
Thank you @boettges for this request. I made the current behavior which goes as follows: If a book has chapters, you'll see only info about the current chapter. If not, you see total times and the middle label shows a numerical percentage played. So it reads like `00:00    Chapter N of N    00:00` for files with chapters and `00:00    N%    00:00` for files without and the slider matches accordingly.

What do you think about making a tap on the middle label toggle between both variants for books that have chapters? 

Sidenote: I kind of want to reserve a tap on the right most label for switching between total and remaining time at some point.

----

To keep this issue tracker focused on the current iteration, I'll close this request and add it to our Roadmap. Discussion is encourage. The issue will be reopened once we find time to work on the request.

**Comment by boettges** [comment]
That is true, tapping the time indicator to toggle to the remaining time (`-00:00`) would make sense, as it is expected behavior and used by many players, such as VLC, QuickTime, IINA etc. and even some web players.

---

I appreciate the idea to make the chapter-indicator in between the two time indicator a touch target. But to reveal an overall percentage personally doesn't provide informational value for me for long audiobooks. In my opinion the percentage shown as a pie chart is a visually pleasing indicator in the library view, but only once you know (and remember) the total duration of an audiobook.

**My use case**
I usually tend to listen to 2-3 audiobooks at a time and make a decision which one to continue, depending on mood, setting (gym = less attention) and especially by how much spare time I have to devote. The total duration and total remaining time is very useful for that. 
Also I usually keep a few books on my device ("to listen" list) and also factor in the total listening duration, when picking the next one. If I know I'll be busy the next days/weeks, I won't start a long audiobook, but might fit a short 1-2h one in.

Showing the percentage that indicates overall progress alone wouldn't help me to estimate how much time I actually need to devote to finish the audiobook, as that information (total duration) is quite hidden in the chapterlist.

My current process for a long chapterized audiobook looks as follows:
- I tap on the book in the library to open it
- I immediately pause playback
- I tap the chapter list button
- I scroll to the bottom of the sometimes lengthy list, especially if a book has hundred and more chapters
- I read the small grey, accumulated total duration shown underneath the last chapter's title
- I then crosscheck with the accumulated current playback time in the currently selected chapter with the checkmark on the right
- quickly subtract them to get the remaining total time to finish the book
- (optional: divide by a factor to account for altered playback speeds, such as 2x)

That is quite a process. On the other hand I can understand that all those different stats and numbers are not shown permanently in the main screen of the app, as it would clutter the screen.

--- 

Maybe swiping up on the cover image could flip it around to reveal the "backside", which is a short list of "detailed information", such as:
- total playback duration of the entire audiobook (= sum of all chapters)
- accumulated listened time up to the current point
- the percentage of progress
- maybe a toggle button to base estimations of the total duration upon the current speed setting

That skeuomorphic cover flip would be fitting to the perspective skew of the cover, when using the progress slider.

**Comment by boettges** [comment]
@GianniCarlo That would be an amazing solution 👌

While I was typing my comment yesterday I took a closer look at BookPlayer's interface and noticed a inconsistency: 
In the "now playing"-view the total duration is displayed in the format `hh:mm:ss`, whereas the accumulated duration in the chapters list is shown in minutes and seconds, such as shown in the screenshot below.

![chapters1](https://user-images.githubusercontent.com/20265197/45106141-34fac480-b136-11e8-861b-b04f2508a2fa.jpg)
![chapters2](https://user-images.githubusercontent.com/20265197/45106146-36c48800-b136-11e8-9b7e-7e690d498db3.png)

Is this a deliberate decision?

To me using minutes and seconds makes sense as long as the accumulated playtime is less than 60min. After that I prefer the `hh:mm:ss` format.

Thanks a lot in advance.

**Comment by pichfl** [comment]
@GianniCarlo I'm not a fan of having a single tap with four states, but it's close to what I had in mind:

My idea in other words: 

- Tapping on the right label toggles between time left and total time (which was my sidenote).
- Tapping on the middle label toggles **all** three labels **and** the progress bar between chapter state and total book state if the book has chapters.

@boettges No, that wasn't a deliberate decision. Both labels use different NSDateFormatters but should use the same. This is a bug.

**Comment by GianniCarlo** [comment]
sounds good @pichfl 👌

**Comment by GianniCarlo** [comment]
closed by #239
