### ISSUE TITLE
Inconsistent time format in Player and chapters overview

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#234]
The total time omits hours in the chapters list for some reason. Both views should use the same kind of NSDateFormatter

Reported by @boettges here: 
https://github.com/TortugaPower/BookPlayer/issues/231#issuecomment-418788055

**Comment by GianniCarlo** [comment]
reference: https://forums.developer.apple.com/thread/32475

Seems like we'll have to keep the `nowPlaying` dictionary ourselves and set it entirely in `MPNowPlayingInfoCenter` instead of just updating one value at a time

**Comment by pichfl** [comment]
Looking at the original comment by @boettges again I realized that there is something off about this. Shouldn't we treat books with a single chapter like if they have no chapter at all? @GianniCarlo I think the work you did for #231 makes this easy to handle.

**Comment by pichfl** [comment]
Extracted the single chapter issue into #242

**Comment by boettges** [comment]
Just updated the app and I’m impressed. You came up with a very clean solution 👌
Thank you for taking the time.

**Comment by pichfl** [comment]
@boettges thanks, but I guess your reply was meant for #231 - This ticket is for the other issue you reported regarding the formatting of the duration.
