### ISSUE TITLE
Feature request - some ability to quickly skip forward or backwards X seconds

### ISSUE THREAD

**Issue by stemcc** [TortugaPower/BookPlayer#236]
* Do you want to request a *feature* or report a *bug*?
Feature

* What is the current behavior?
Double tapping on the left or right side of the now playing screen does nothing

* What is the motivation / use case for changing the behavior?

It would be very helpful if one could double tap in the general direction of the right side of the now playing screen to skip ahead X seconds or tap the left side to skip back X seconds. A button could accomplish this too.

After leaving a long book in the middle of it and coming back later, it's helpful to be able to quickly skip backwards 15 - 30 seconds to refresh my memory about where I left off. And when listening to something I don't need to listen to, to be able to easily skip forward. 

Right now, my only option (as far as I'm aware) is to scrub with my finger, which at best can be imprecise, sometimes causing me to try multiple times to simply scroll backwards 30 seconds. 

* Please tell us about your environment:
Latest app store version, iphone X

**Comment by GianniCarlo** [comment]
Hi @stemcc , for the latest version (v3.0.0) we switched out the skip buttons and we put gestures which requires you to drag the artwork left or right to accomplish the skip back or forward. We also included customizable intervals for skipping (they can be changed in the settings page. 

Please try it out for a time and let us know what you think

**Comment by pichfl** [comment]
In fact we also have another feature that helps you as well: Smart rewind (when activated) does the jump for you automatically. 

I'm closing this issue to keep focus on the current milestone. Please keep us posted if we missed something.

**Comment by stemcc** [comment]
Dragging the artwork left or right does what I need perfectly - thank you!
