### ISSUE TITLE
Siri Suggestion

### ISSUE THREAD

**Issue by ryantstone** [TortugaPower/BookPlayer#243]
Feature Suggestion:
I was using Castro this morning and after using it I was presented in Siri suggestions with a suggestion to "Resume playback from the top of your queue". Later in the BookPlayer roadmap a similar feature would be nice. Just pull down to search and be presented with a "Pick up where you left off" suggestion, tap and play.

**Comment by GianniCarlo** [comment]
Hey @ryantstone I really love the possibilities of Siri suggestions/shortcuts. I've been working on a branch where I already split into a shared framework part of the codebase. I got de-railed a bit looking into implementing a watch app, but I'll circle back around to Siri soon enough, so this feature might make it into production soonish (say 3.3.0 maybe)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pichfl** [comment]
Very much in favor of this even though I've yet to see my first suggestion on my phone.

As always, I'm putting this into our roadmap and closing this ticket to keep focus on the next release.
