### ISSUE TITLE
Support links not working

### ISSUE THREAD

**Issue by atomicdecay** [TortugaPower/BookPlayer#247]
In the latest version (3.1.0-2), the two links under Settings->Support do not appear to be working.  I can tap on them, but nothing happens.

**Comment by GianniCarlo** [comment]
Hi @atomicdecay thanks for reporting it. v3.1.1 is currently under review in the app store and it includes the fix for this.

The PR that fixes this is: #246 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
