### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ryantstone** [TortugaPower/BookPlayer#273]
I rebased the `add-completed-state` branch on `Develop` and am receiving a build error related to the new logic added to `AppDelegate`

```swift
func setupDocumentListener() {
        let documentsUrl = DataManager.getDocumentsFolderURL()
        self.watcher = DirectoryWatcher.watch(documentsUrl) //Cannot invoke 'watch' with an argument list of type '(URL)'
        self.watcher?.onNewFiles = { newFiles in //Value of type 'DirectoryWatcher' has no member 'onNewFiles'
            for url in newFiles {
                DataManager.processFile(at: url)
            }
        }
    }
```
Is this happening with anyone else?

**Comment by GianniCarlo** [comment]
run carthage update, the DirectoryWatcher dependency was updated

**Comment by GianniCarlo** [comment]
the lock file should already be updated 🤔

**Comment by GianniCarlo** [comment]
Forgot to mention, this was updated/introduced in #272 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
