### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#286]
We should move the app to proper localization.

Our app statistics seem to suggest we have quite a few Russian and German users (and I'm not all of them). Also having a Spanish version won't hurt for the US market.

I can provide and maintain translation strings for German and I'm quite confident we'll find someone who wants to help us out with the Russion version.

**Comment by Nibelungc** [comment]
Hi. I can help with Russian localization

**Comment by pichfl** [comment]
@Nibelungc wohoo. That was even faster than I expected. Thanks a lot! We'll keep you posted about when and how.

**Comment by GianniCarlo** [comment]
@Nibelungc awesome!

on another point @pichfl , some time ago I stumbled on this framework https://lokalise.co which is free for open source projects, let me know what you think about it (it might be overkill for just one app though)

ps. I'll do Spanish

**Comment by pichfl** [comment]
@GianniCarlo I haven't tried them but having a managed solution for the translation keys makes for a much better translator experience and might help us a lot. Totally in favor of lokalise.co here.

**Comment by GianniCarlo** [comment]
An update on this, we got a project going on https://lokalise.co and we've added all the keys that we're currently using in BookPlayer. @Nibelungc please let us know with which email you'd like to be invited to the localization project so you can contribute with Russian translations

**Comment by GianniCarlo** [comment]
so far we've got covered:
- [X] English (Base)
- [X] German (@pichfl)
- [X] Spanish (@GianniCarlo)
- [X] Russian (@Nibelungc)

If you'd like to see the app localized in your language and contribute, please let us know so we can add you to the project

**Comment by Nibelungc** [comment]
nibelungc@gmail.com

**Comment by GianniCarlo** [comment]
@Nibelungc invitation sent, thanks for your help!

**Comment by carcade** [comment]
Can help with russian localization.

**Comment by GianniCarlo** [comment]
We'll be picking this up again to finally close and merge it for the next version (3.4.0) 🙂. We'll have more news on this throughout this month

**Comment by devil418** [comment]
I can help with the polish version. I'm miki123211 on Google's email service. I'm a blind user, so not sure how my screen reader is going to handle the translation SAAS, though.

**Comment by pichfl** [comment]
@devil418 we can always export a plain text translation file for you. We want to get some other features out of the way before we start this one, but we'll get back to you very soon!

**Comment by GianniCarlo** [comment]
Hi guys! Sorry for the delay on this issue, but we got the basis working on the PR #427, and I've added all the translations that we had on lokalise.com. I've also updated lokalise.com with all the missing keys that have come up with the new changes and features.

At your convenience, please help us out to finish the translations again so we can release it in the following weeks 👌

cc @Nibelungc @GAumala @hypeitinc

**Comment by GianniCarlo** [comment]
@carcade can you still help us with Russian localization?

**Comment by hypeitinc** [comment]
Hi Gianni,

I will continue on the Swedish translation. Not sure how much time I can spend on it right now so the obvious question, when would you like to release it?

/peter

**Comment by GianniCarlo** [comment]
@hypeitinc  Ideally I'd like to release it by the end of February, but let me know once you've taken a look (there's around 90 new keys) and estimated when you could have it done in your free time so I can readjust my expectations 🙂. We could do the release with the 4 languages we already have 100% (English, Spanish, German, Czech) and add new ones down the road in later versions, so no pressure 👍

**Comment by carcade** [comment]
> @carcade can you still help us with Russian localization?

Yes, how can I participate?

**Comment by GianniCarlo** [comment]
@carcade we need an email to invite you to the platform lokalise. You can either post it here, or send it to us to support@bookplayer.app 🙂 Thanks again

**Comment by carcade** [comment]
> @carcade we need an email to invite you to the platform lokalise. You can either post it here, or send it to us to [support@bookplayer.app](mailto:support@bookplayer.app) 🙂 Thanks again

I sent a message to support@bookplayer.app, you can use that email address.

**Comment by GianniCarlo** [comment]
great! invitation sent 👍
