### ISSUE TITLE
Skip forward and back from headphones remote

### ISSUE THREAD

**Issue by cuddawudda** [TortugaPower/BookPlayer#301]
Overcast has a gesture where you can double click the remote button to rewind and triple click to skip forward. 
This is useful when you wish to skip and don't wish to look at screen.

**Comment by cuddawudda** [comment]
Neck should be 'and back'...
Best should be 'headphones'
I'm blaming my phone's keyboard... Apologies. 
Title should read. 
Skip forward and back from headphones remote.

**Comment by GianniCarlo** [comment]
mmmm I think it should be available already 🤔, let me test it and get back to you

**Comment by pichfl** [comment]
To clarify: If you want skipping: BookPlayer already supports jumping by the regular forward/backwards intervals using the double click (forward) and tripple click (backwards) actions on the Apple EarPods remotes. Most manufacturers implement the same signal for their hardware buttons so this should cover other headphones as well.

If you want to have the seek controls, we currently did not implement them and mapped the seek commands to the same jump controls described above. So if you want to see seeking via Headphones (that is clicking the button twice or thrice and holding it down) to seek into either direction, we'll consider this as a feature request.

**Comment by pichfl** [comment]
Follow up question: What headphones do you use? We may need to very the "gestures" / click actions still work as intended.

**Comment by cuddawudda** [comment]
Hi. I use apple wired earphones and plantronics back beat fit bluetooth. I don't use the buttons on the plantronics as it's not easy to triple click with any accuracy and I find myself doing forward instead of backwards more often than not.
