### ISSUE TITLE
Importing file, unable to assign any "favorites"

### ISSUE THREAD

**Issue by molonlabe88** [TortugaPower/BookPlayer#308]
I am running iOS on the Xs Max and when I go to import a file, I go into locations and use the DS File to do so. I noticed there is a "favorites" header underneath the Locations header and above the Tags header. I cannot seem to figure out how to add anything to that favorites header.

**Comment by pichfl** [comment]
It bugs me a lot to say this, but once you're inside the file picker, you basically left BookPlayer. So everything happening there is part of the Files.app plugin provided by the app you're using for file storage, which in the case of DS File doesn't implement the whole API. 

TLDR; DS File is lacking this feature. You might consider asking Synology about it. 

I'm closing this issue as it is not related to BookPlayer.

**Comment by molonlabe88** [comment]
Except I’m not in DS yet. You can see here what I mean. 









Thank you,



Shane Taylor
taylorsm88@gmail.com

**Comment by molonlabe88** [comment]
Thanks, i don't think it is DS either. It appears to be apple. When I go into Imgur to upload a picture the file picker is the same.

**Comment by atomicdecay** [comment]
That is indeed an issue specific to the iOS Files app. If you tap and hold your finger on a file or folder and pull up the little black context bar, one of the options will be to add the item to the Favorites section.
