### ISSUE TITLE
Add 'New playlist' option when importing files [Playlist screen]

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#310]
I added some files while listening to an audio book (app active screen was inside the audio book playlist)
the pop up for import appeared and i clicked "new playlist".
the screen immediately closed (not giving me the option to name it) and all the files added to current playlist instead to a new one on root level

**Comment by Guy27** [comment]
Sorry guys, seems like i misread. though a new playlist option was there, apparently it was "current playlist".

**Comment by GianniCarlo** [comment]
You bring up a good point, it should show you an option to let you create a new playlist, no matter where you are

**Comment by GianniCarlo** [comment]
I think this can easily be added after the work done in the batch edit pr #289
