### ISSUE TITLE
Show the full progress on the book and some more pretty chapter names

### ISSUE THREAD

**Issue by hydro0** [TortugaPower/BookPlayer#311]
* Do you want to request a *feature* or report a *bug*?
Feature

* What is the current behavior?
It shows only the duration and state of current chapter, also mp3 extension in chapter names seems redundant

* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem. 
* What is the expected behavior?
Show somewhere in the top the duration of entire book and current position in it, also “Chapter 10” seems more descriptive then “10.mp3”

* What is the motivation / use case for changing the behavior?
Chapters may be different size, also it’s convenient to have a track on the progress of the entire book. Maybe it could be one of the modes when you press on the duration of current chapter

* Please tell us about your environment:
    * Version of BookPlayer 3.2.1
    * Your Device and its OS version iPhone 7+, iOS 12.2

* Other information
  Maybe you guys already considered this feature and decided not to do it, but if not I can handle the implementation to help you with that, very great product and the only decent app for listening audio books on the iOS

**Comment by GianniCarlo** [comment]
Regarding the progress of the entire book, you can press the center label underneath the slider to toggle between chapter duration and book duration:

![52d989ef-63ac-4835-b087-6fc60d34be4d](https://user-images.githubusercontent.com/14112819/52323219-3d3b8200-29aa-11e9-9c61-69adac239b87.GIF)

Let me know if that's what you had in mind?

**Comment by GianniCarlo** [comment]
regarding pretty chapter names, since the names are extracted from the file itself, we're offloading that responsibility to the user for the time being. 
We do have something in mind for the future, to let you see the book or playlist info and let you modify the metadata. We believe this would be a long term solution to the chapters name problem.

If you're up for it, we'd be more than glad to receive help for these features. We would provide any assistance we can to guide you in how the app is structured.

**Comment by hydro0** [comment]
1. I see, thanks. Somewhy just nothing happens when I press that label. 

1. About chapter names - I can take a look and show some proposal.

**Comment by pichfl** [comment]
Please note that the chapter names @GianniCarlo is talking about are part of audiobooks stored in the M4B format. 

While this request is reasonable, it will require to update the way playlists are handled inside the player, which is something we'll look into in future updates.

[We recommend](https://github.com/TortugaPower/BookPlayer/wiki#how-to-combine-mp3-files-into-m4b-audio-books) converting your books into M4B for now. We fully support the chapters that are created inside these files and it makes handling books much easier.

**Comment by hydro0** [comment]
Okay, thanks, seems it is working fine with M4B format, looks much better btw, so I would just use it instead. Sorry for disturbing. Maybe I missed that somewhere but would be useful to mention it in the application that preferable way is M4B format with the link you've shared with me.

**Comment by pichfl** [comment]
I'll keep the issue open as we will most likely find a way to make this work for non-m4b audiobooks as well, stay tuned. 

We put the m4b first in our descriptions, but that's a rather subtle way of telling people about the benefits. I'll keep your suggestion in mind when reworking the texts for the next big update 🙂

**Comment by redcardfr** [comment]
The ability to 

> Regarding the progress of the entire book, you can press the center label underneath the slider to toggle between chapter duration and book duration:
> 
> ![52d989ef-63ac-4835-b087-6fc60d34be4d](https://user-images.githubusercontent.com/14112819/52323219-3d3b8200-29aa-11e9-9c61-69adac239b87.GIF)
> 
> Let me know if that's what you had in mind?

Is it possible to have this functionality at the playlist level?

Typically I’ll have a playlist with 2-3 books I’m currently listening to, and it would be nice to see time remaining etc. for the playlist 

Thanks

**Comment by pichfl** [comment]
Not yet, but we are working on that 🙂

**Comment by song4Him** [comment]
Just adding a note here saying I, too, would love to have a way to see progress on the book or playlist as a whole. I was wondering if perhaps a percentage number next to the current pie chart progress tracker would be an easy addition? But I do like redcardfr's idea, too.

I also haven't worked out how to effectively do m4b books, as I get almost all my audiobooks as mp3s, and converting them is a pain. Is it okay to have one m4b file per chapter, or more preferred to have all the chapters put together in one m4b file?

**Comment by pichfl** [comment]
@song4Him we are working on a solution to bundle up files into a single book from inside the app in the future. For now and for easier handling of books in general we always recommend [using m4b to create a single file for each book](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-combine-mp3-files-into-m4b-audio-books). 

In short: You most definitely want to have a single file per book and use the chapter feature inside m4b to get chapters 👍

**Comment by dano3006** [comment]
A playin-in-progress meter would be a nice addition, very useful and helpful.

I use m4b almost exclusively, so they do work. Agree that converting multiple files - either mp3 or m4b - is a pain*.

*I have not found many sound utilities that can edit m4b. I use Audiobook Builder to compile multiple files into a single or a few files but it does not edit m4b, it only compiles mp3 or m4b into bigger m4b files. My preference is to put multiple files together and then have ABB convert them into a single file, or, when the single file gets to be about 175-200 MB I start making multiple or more. This seems to be the method that the professional audiobook creators are using.

**Comment by GianniCarlo** [comment]
with the mp3 volume feature, this should be solved 🙌
