### ISSUE TITLE
First chapter starts when tap on the image of the playlist in the Library list

### ISSUE THREAD

**Issue by hydro0** [TortugaPower/BookPlayer#312]
* Do you want to request a *feature* or report a *bug*?
Bug

* What is the current behavior?
When I press on the image of the book in the library it brings me a player with a first chapter

* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem. 
Open some book on any chapter, then open library and press on the book image - it starts the first chapter. Can share the video if that’s not reproducible, but later when I will get to the laptop.

* What is the expected behavior?
It should open player view with current state.

* What is the motivation / use case for changing the behavior?
It loses entire progress and start the book from the first chapter, don’t think it is intentionally

* Please tell us about your environment:
    * Version of BookPlayer 3.2.1
    * Your Device and its OS version IPhone 7+, 12.2
* Other information
  Can help with this as well if you need spare hands

**Comment by GianniCarlo** [comment]
It'd be of great help if you could provide a recording 👍, I'll be able to do some tests much later today and report back

**Comment by hydro0** [comment]
Sorry, just read it opens first **unfinished** chapter, and somehow I had chapter 1 just a few seconds behind being finished. Though continuing from the current state looks more logical for me, but that's not a big deal, thanks for the fast reply!

**Comment by hydro0** [comment]
Seems it is still reproducible even if I marked all chapters as read explicitly, please check the [video](https://share.icloud.com/photos/0h0CyieTjH36HqJ_FM5tyuA4A) :

1. All the files are "read" up to chapter 21.

1. When going back to the library and pressing on the artwork - chapter 1 is opened.

1. Marking chapter 1 as read again - just to be sure.

1. Open chapter 21.

1. Going back to the library and pressing on the artwork - chapter 1 is still opened.

**Comment by pichfl** [comment]
Very important question: 
The chapters you're talking about, are they inside a single file or is *each file* a single chapter? The former would have files A-C with A containing Chapter 1-10, B containing Chapter 11-20, C containing 21-26, the latter having files A-Z with A being Chapter 1, and so on.

@GianniCarlo I think this may be solved by #276. I'm rather sure the error would be in this part of the model, which was my naive approach to finding the first unfinished file.
https://github.com/TortugaPower/BookPlayer/blob/6be02e1b427ee9e5a6620821fd35605d586fcd0b/BookPlayer/Models/Playlist%2BCoreDataClass.swift#L132-L142

I'm pretty sure this is the culprit:
https://github.com/TortugaPower/BookPlayer/blob/6be02e1b427ee9e5a6620821fd35605d586fcd0b/BookPlayer/Models/Book%2BCoreDataClass.swift#L41-L45

**Comment by hydro0** [comment]
@pichfl thanks for the explanation, it is a one chapter per file

**Comment by pichfl** [comment]
Looks like a proper bug then, we'll keep this issue updated when we find a fix.

In the mean time I recommend the same as I did in [your other issue:](
https://github.com/TortugaPower/BookPlayer/issues/311#issuecomment-461007943) Use one of the free converters to collect the mp3 files into a m4b type audiobook, naming the chapters in the process.
