### ISSUE TITLE
Miniplayer: superimposed title and author labels

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#315]
Reported by GJ via email support

![GitHawk Upload by GianniCarlo](https://i.imgur.com/k76kHeq.jpg)

This might be due to height of the artwork 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pichfl** [comment]
I'm pretty sure it is. I'm pretty sure I attached the labels to a view with height depending on the artwork size and I never tested for extreme ratios.
