### ISSUE TITLE
Playback speed options

### ISSUE THREAD

**Issue by amiramir** [TortugaPower/BookPlayer#323]
Thanks again for the great work. Best iOS audio book reader around!

It’d be nice to have some more speed controls on the low end.

Two suggestions:
- add a 1.125 speed
- add a “set your speed” option with a field to enter any speed the user wants

**Comment by amiramir** [comment]
Thanks again for the great work. Best iOS audio book reader around!

It’d be nice to have some more speed controls on the low end.

Two suggestions:
- add a 1.125 speed
- add a “set your speed” option with a field to enter any speed the user wants

**Comment by pichfl** [comment]
@amiramir thanks for the suggestion. We do not plan to extend the speed options in its current state, but rather provide a completely new interface to control playback speed in the next major version, which was brought up in #224 

I'm closing this ticket as a duplicate and linking it to the older issue.
