### ISSUE TITLE
Reaching to chapter list is uncomfortable if book is a playlist of multiple files

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#348]
Current behavior:

in case where i wish to continue listening to a book i already listened to after the app was closed the steps are as follows:
1. open the app
2. at the bottom bar i can see the last chapter of the book i listened to (while the main screen itself is showing, not the chapter list of the last heard book)
3. i click play on the chapter and enjoy my listening to.
4. at a certain point i wish to go back to a previous chapter but there is no bottom to get to the chapters list of the current book.

It was assumed that the "back" feature will get us there, but it is not the case on the scenario above since i reached the play screen via the bottom bar shortcut and not through the navigation via the playlist.

i can't even begin to imagine how many times this happened for me :)

**Comment by pichfl** [comment]
I do understand your problem, but it's origin and therefore solution might be less obvious.

Is your book a single m4b file or multiple small mp3 files? The former format supports native chapters which we fully support in BookPlayer. The latter does not have chapters at all, but rather gets imported as a Playlist with individual items. 

The fastest fix on your side would be to [follow the guide in our FAQ](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-combine-mp3-files-into-m4b-audio-books) on combining MP3 files into a single audiobook. I do recommend this anyway, as it makes handling audiobooks much more pleasant. 

Our task will be to determine a good solution how we can do something similar from inside the app, basically handling a playlist like a single book. @GianniCarlo and I will discuss what could be done.
This will take time and as it is a new feature will be added to our roadmap to be implemented later.

**Comment by pichfl** [comment]
Closed in favor of #389
