### ISSUE TITLE
Jump chapter buttons

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#350]
it can be done with the 3d click option (hard click) on the same back/forward buttons that are currently displaying. 
it's frustrating to need to go back to the chapter list if i missed a few seconds and want to hear them again but new chapter just began, (scrolling back stops at the beginning of the chapter).

**Comment by pichfl** [comment]
Just as with #348 this stems from how we handle playlists and native audiobook files. Once #348 is handled, this might become redundant. 

However we should consider allowing the Jump buttons to work across files when listening to a playlist, which will be a good enhancement for the interface in any case.

**Comment by GianniCarlo** [comment]
This was finally introduced in v4.2.0 🎉
