### ISSUE TITLE
Display Multipart Books as Single Book

### ISSUE THREAD

**Issue by beornlake** [TortugaPower/BookPlayer#354]
Feature request: Presently, books that are split into multiple .m4b files are displayed with their parts listed separately in the Library (see screenshot below). The filenames for the parts differ only with `, Part #` at the end, and the metadata for the files properly defines each part as being from the same Album and are marked as "track X of Y".

![IMG_C17D38D44727-1](https://user-images.githubusercontent.com/3237644/56608677-ee78ae00-65d0-11e9-9346-b32fdd8a74da.jpeg)

Expected behavior:
In iTunes and the built-in iOS Books app, these same files are displayed as all parts being combined into one book. This means that listening progress is calculated across all parts of a book. With the combined method, a user is better able to gauge their actual progress through the book (rather than through just the current part), and it tidies up the Library so that there aren't a bunch of seemingly-duplicate entries in the list.

Version: BookPlayer 3.3.1-2 on iOS 12.2 (iPhone XS Max)

**Comment by GianniCarlo** [comment]
Excellent request! we have considered this, and we were thinking on following Bound's approach. The user will be able to combine/remove books at will into/from a single one. This is something that I want to sort out for the next release, so we'll see how this develops

In the mean time, to mitigate the need for this, playlists can be used, the progress wheel on the cells aggregates between all the playlist's books, and they can be named to whatever the user wishes

**Comment by beornlake** [comment]
Sounds good. And thanks for the Playlist tip! I'll use that for now.

**Comment by pichfl** [comment]
iTunes uses books metadata (Album name) to combine them, which might be a good option for us as well. 

Since we know that many people do not fill in IDE3 tags, our solution must be a bit more sturdy, but it could be nice to automate this if we detect matching album names 🙂

**Comment by GianniCarlo** [comment]
Agreed, automate when possible 👍

**Comment by pichfl** [comment]
Closed in favor of #389
