### ISSUE TITLE
Implement sleep timer resetting by phone shake

### ISSUE THREAD

**Issue by carcade** [TortugaPower/BookPlayer#359]
Feature request.
One thing I really miss after switching from android audiobook player to this is the ability to reset (renew) sleep timer by shaking a phone.

Behavior: 10 seconds before sleep timer end, app should play a sound, and user has 10 seconds to shake the phone to renew the timer, otherwise it will stop.

Is it possible to implement this?

**Comment by GianniCarlo** [comment]
We got something planned to handle this case (https://github.com/TortugaPower/BookPlayer/issues/341), a snooze timer alert, so you can resume the book and reset the timer 👍

**Comment by carcade** [comment]
I saw that issue, if I understand correctly, it allows to resume the book by clicking some alert on phone display?
I'm talking about phone shaking, because when listening to the book before sleeping, it is really handy to renew timer by shaking the phone, instead opening your eyes, clicking something, etc. 😄

**Comment by GianniCarlo** [comment]
hmmmm interesting point, it could be an enhancement, to have a sound 10 secs before the audio stops and the notification appears, and if the phone is shaken, it'll reset the time left

**Comment by GianniCarlo** [comment]
let's move this to #341 since I think it's on the same line as this
