### ISSUE TITLE
Add Notes to as a bookmark

### ISSUE THREAD

**Issue by syto203** [TortugaPower/BookPlayer#360]
What I mean is sometimes i stop listening to a book for weeks at a time and when I come back I’ll have to roll back a few minutes until I remember what was going on in a story. My suggestion is having the option to add a small note where I stopped to give context the next time I play.

**Comment by GianniCarlo** [comment]
Hi @syto203 , thanks for the suggestion and you'll be happy to hear that we do have it into consideration. A bookmark will have a title, note and the timestamp

**Comment by GianniCarlo** [comment]
I'm closing this issue to focus the conversation regarding bookmarks into #127
