### ISSUE TITLE
Sleep timer global setup

### ISSUE THREAD

**Issue by carcade** [TortugaPower/BookPlayer#361]
Feature request.

It would be great to setup timer once and enable it globally, and every time playing a book, timer starts automatically. This eliminates the need to turn on and adjust the timer every time. I think, it will be very convenient.
Are there any cases when you need to manually setup timer every time you want to listen to the audio book?

**Comment by pichfl** [comment]
This will to some extend be resolved by the planned changes to the sleep timer displayed in #281 which can default to the previously selected value.

Having a global timer that automatically starts for each file that can be configured via Settings is possible, but not a priority right now. I'm closing this issue to focus on more pressing matters. If anyone want's to tackle this, feel free to comment and I'll reopen this.
