### ISSUE TITLE
Apple Watch App Does Not Show Clock

### ISSUE THREAD

**Issue by Serendigity** [TortugaPower/BookPlayer#369]
With the new Apple Watch support there is no clock displaying the current time on the user interface. Please look at the layout of the default Apple 'Now Playing' app. 
![IMG_8817](https://user-images.githubusercontent.com/45026713/63003514-77389400-beb7-11e9-895d-04cfd7e354e1.JPG)
![IMG_8819](https://user-images.githubusercontent.com/45026713/63003516-77389400-beb7-11e9-90f9-de4f5a4619fe.JPG)

To the right of the word 'Dismiss' please show the current time.

**Comment by GianniCarlo** [comment]
Agreed, I’ll look into fixing this as soon as possible. A little reasoning behind this: having the now playing view shown as a modal was a last minute change, given that if it was put as a two pager app, the now playing view will bug itself and be sligthly off screen and wouldnt present any information

**Comment by GianniCarlo** [comment]
solved by #370

**Comment by Serendigity** [comment]
Thanks for the quick action :)
