### ISSUE TITLE
Drag and dropped book folder does not show up

### ISSUE THREAD

**Issue by geongeorge** [TortugaPower/BookPlayer#372]
Even after dragging and dropping the book via iTunes the library is empty inside theapp
![image](https://user-images.githubusercontent.com/29296982/63035189-5896c500-bed8-11e9-9f0f-5f49e89cc486.png)

**Comment by GianniCarlo** [comment]
We disabled folder support on the lastest version (3.4.0) due to some bugs whose foundation I described in this comment: https://github.com/TortugaPower/BookPlayer/issues/358#issuecomment-507009883 . If you zip the folder before importing it, the import should work properly though

**Comment by GianniCarlo** [comment]
I'm closing this issue, but feel free to continue the conversation here @geongeorge or if you want to go deep into the underlying issues on #358 , we would be more than grateful if you could lend a hand regarding the watcher dependency

**Comment by geongeorge** [comment]
@GianniCarlo Thanks for the amazing app,
Works flawlessly now! <3
It took me a while to figure out how to import books.
I did find the zip way eventually. 
For noobs like me, a simple help page would be amazing,
or at least an intro in the app store description

**Comment by GianniCarlo** [comment]
I'm glad you're enjoying it 🙂, thanks for the recommendation, I'll be updating the app store description 👍
