### ISSUE TITLE
Can't handle progressbar for long audiobooks

### ISSUE THREAD

**Issue by Jidbo** [TortugaPower/BookPlayer#380]
**Bug**: The progressbar of long audiobooks is not displayed right in the in-app player.

The progressbar is full and the percentage of the book is above 100 even though the book is not finished. This only happens with books that are longer than 13+ hours. The iOS lockscreen displays the progress bar the right way.

I am running Version 3.5.0-2 on iOS 13.1 Beta.

![photo_2019-09-06_12-34-00 (2)](https://user-images.githubusercontent.com/25406344/64422207-cbdcc280-d0a3-11e9-80c0-44fddf5fda24.jpg)
![photo_2019-09-06_12-34-00](https://user-images.githubusercontent.com/25406344/64422196-c54e4b00-d0a3-11e9-8b55-8f37be7d4855.jpg)

**Comment by GianniCarlo** [comment]
Hi @Jidbo thanks for reporting this. I can't seem to reproduce this on some books that I have that are 20+ hours. Would you mind copy/pasting here the info that you get from the file using `ffprobe /path/to/<file>`? More info, this command-line tool comes with installing `ffmpeg`

**Comment by Jidbo** [comment]
It seems like it's a problem with the metadata of my file and not with the app. Thank you though :smiley: 

```Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Die Stadt der Träumenden Bücher.m4b':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2010-10-09T14:28:42.000000Z
    encoder         : FAAC 1.26.1 (Apr  8 2007) UNSTABLE
    artist          : Walter Moers
    title           : Die Stadt der Träumenden Bücher
    album           : Die Stadt der Träumenden Bücher
    date            : 2005
    genre           : Books & Spoken
  Duration: 13:15:21.86, start: 0.023220, bitrate: 130 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 97 kb/s (default)
    Metadata:
      creation_time   : 2010-10-09T14:28:42.000000Z
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 300x300 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)```

**Comment by GianniCarlo** [comment]
👌 I think a quick fix to the file's metadata would be to pass it through `ffmpeg` with this command: `ffmpeg -i damagedfile.m4b -c copy newfile.m4b`

**Comment by Jidbo** [comment]
That fixed it :+1:

**Comment by and-pete** [comment]
> 👌 I think a quick fix to the file's metadata would be to pass it through `ffmpeg` with this command: `ffmpeg -i damagedfile.m4b -c copy newfile.m4b`

This was a nice little fix for another `.m4b` issue I experienced.

A 16-hour audiobook was dead silent in _BookPlayer_ on either my iPhone or iPad (and also if opened by the device's default player within Files), but it *would* work using the _VLC_ app on each device.  Running it through `ffmpeg` did the trick. Thank you!
