### ISSUE TITLE
Independent watchOS app

### ISSUE THREAD

**Issue by sprig** [TortugaPower/BookPlayer#382]
I saw a previous ticket for this, but nothing implemented yet, it seems - It would be great if the watch app could work independently of the phone, at least as far as playback goes.

**Comment by diogoribeiro09** [comment]
I vote for this too. Using the watch app together with the phone is amazing but being able to upload your own files to the watch would be a killer for me !

**Comment by NemesiS153** [comment]
I’m not sure how easy it would be to upload directly to watch, but overcast (podcast app) seem to have the balance really well done,

Current features - 
Upload to phone
Sync to watch (with limits like, number of podcasts to sync)
Listen on watch, syncs position on phone
Simple watch interface to switch between iPhone control and direct watch control

Feels like the biggest user case is go to gym/run etc with ability to carry on listening to book without phone

**Comment by pichfl** [comment]
Replaced by #464
