### ISSUE TITLE
Add books from any website

### ISSUE THREAD

**Issue by openaudible** [TortugaPower/BookPlayer#383]
I am writing code to add a new feature for BookPlayer to allow a user to import books from the web. It works well and just cleaning things up.  

Hopefully this will be useful for those who want to browse [librivox](https://librivox.org/search?primary_key=0&search_category=author&search_page=1&search_form=get_results) or keep their own books in a web accessible library. 

I'll submit a pull request shortly.. but I thought I'd post here in case someone wants to comment.

**Comment by GianniCarlo** [comment]
@openaudible that's great! I can't wait to test it out 💪

**Comment by openaudible** [comment]
Here is a version you can test!
https://github.com/openaudible/BookPlayer

```bash
git clone https://github.com/openaudible/BookPlayer.git BookPlayerTest
cd BookPlayerTest
carthage update --platform ios --no-use-binaries --verbose
```
You should be able to Add+ a book... and browse for files on a web page.  

This is my first iOS app work in a long time--so I may have unintentionally broken storyboards, constraints, programming conventions, etc. Feel free to fix or laugh at my bad code. I tested mostly on a few simple web pages with mp3s and some password protected directories.  I did not test zip files at all. 

I ran into a [known WebKit bug](https://stackoverflow.com/questions/46221577) by using WKWebView in the UI editor. This can be fixed, but for now, I just required iOS 11. 

Anyway, thanks for the enthusiasm for the feature.. Let me know and I can submit a PR.. or feel free to merge it into your own code.

**Comment by GianniCarlo** [comment]
Don't worry about it, we're more than happy to provide feedback 🙂. Whenever you can, please submit a PR, so it'll be easy for us to comment 👍. Regarding iOS 11, with iOS 13 coming out today, I don't think raising the minimum version required would be a problem, (thoughts @pichfl ?)
