### ISSUE TITLE
[New feature] text-to-speed ebook.

### ISSUE THREAD

**Issue by northernSky** [TortugaPower/BookPlayer#386]
Hi,
Currently, we could only listen to books that have someone reading for us. But there is a limit number of these kind of book. 
It would be nice if we could import ebook ( .pdf, .prc) and Bookplayer will read it out loud.
Google Text-to-speed have improved alot. The output sound are quite naturally now.
Currently, I'm using version 3.5.1-4 on ios 13
Thanks for reading this :D

**Comment by pichfl** [comment]
Thanks for the quite interesting suggestion, but I'm sorry to have to turn it down. 

BookPlayer is focused on providing an easy to use playback experience for your audiobooks. Creating audiobooks from text lies beyond our intended set of features. 

If anyone is interested in creating a sibling app called BookReader that creates files that could be consumed by BookPlayer, we'd be happy to get in touch and discuss UI and provide app icons and such things. 

While I do get the wish to make a single app do everything, we are a small team and keeping focus on our main mission outweighs an ever growing list of features that becomes to big for us to maintain.
