### ISSUE TITLE
Importing files should dismiss player

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#387]
If the player is open and files are imported via AirDrop or sharing from an external app, the import progress isn't shown. Dismissing the player / presenting the Library would change that.

**Comment by mmurali88** [comment]
@pichfl I have tried resolving this issue. I raised a PR for this https://github.com/TortugaPower/BookPlayer/pull/473

**Comment by GianniCarlo** [comment]
merged, thanks again @mmurali88 !
