### ISSUE TITLE
Add 'More' option to bulk controls

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#388]
Requested via email by Alexander. We could add a fourth button in the floating bulk-controls (or maybe remove the 'move' button in favor of this one), which would present the options sheet that we already present when swiping left on a cell. This would expand the functionality so that multiple (filtered) books can be marked as finished, or jump back to the beginning

**Comment by pichfl** [comment]
Very much in favor of this 👍

I will provide a suiting icon. The one above does not match our iconography. Also will provide a new icon that marks selected entries, I did realize they should have some sort of check mark in them.

**Comment by pichfl** [comment]
@GianniCarlo suggested to show "select all" in the upper left corner of the navigation bar when in edit mode, which is a somewhat common pattern.

**Comment by GianniCarlo** [comment]
This is already in the app 👌
