### ISSUE TITLE
Books auto-starting shortly after pausing them.

### ISSUE THREAD

**Issue by SaintNicholas** [TortugaPower/BookPlayer#392]
I've had this problem for the last few weeks. Almost every that I pause a book, the book will automatically re-start again after a few seconds. It usually does this 1 - 4 times before it stays paused. It doesn't matter if my phone is in my pocket, if it's flat on a table, if it's locked, or unlocked. I can't find any pattern in what it's doing.

I'm using BookPlayer 3.5.1-4 on iOS 13.1.2.

[IMG_0009.mov.zip](https://github.com/TortugaPower/BookPlayer/files/3726641/IMG_0009.mov.zip) is a .zip of a movie that I took of the issue happening several times in a row.

Let me know if you have any other questions.

**Comment by GianniCarlo** [comment]
O: damn. I haven't seen this behavior before. Just to get some things out of the way, did you have the companion Watch app running? airpods or any bluetooth headset nearby?, or have some automations setup in your phone?

Thanks again for the video 👌

**Comment by SaintNicholas** [comment]
I don't have the companion watch app running, and I don't have any automations setup on my phone. I removed all of my bluetooth devices except for my Apple Watch, and was able to reproduce the problem pretty quickly.

**Comment by GianniCarlo** [comment]
This is solved by #408

**Comment by GianniCarlo** [comment]
@SaintNicholas I just uploaded a beta to TestFlight, it'd be great if you could help me test and see if the solution works. Link to join: https://testflight.apple.com/join/FLv3zLyN

**Comment by GianniCarlo** [comment]
merged
