### ISSUE TITLE
Name playlist after folder/archive name instead of first file

### ISSUE THREAD

**Issue by mikolysz** [TortugaPower/BookPlayer#394]
*feature*
* What is the current behavior?
When importing from a folder/zip into a playlist, the default playlist name is the name of the first file, which doesn't make sense.
* What is the expected behavior?
The playlist name should be the folder name, or, the name of the zip file, without the extension.
* What is the motivation / use case for changing the behavior?
The first file is often called "chapter1.mp3", which doesn't tell us much, especially when we have more than one book with that convention. A name based on the archive/folder would make much more sense here.

**Comment by pichfl** [comment]
Very good idea! 

Notes to anyone who wants to take a stab at this: It is likely that this might require some refactoring in the ImportOperation class.
