### ISSUE TITLE
White stripes around PNG art on lock screen *bug*

### ISSUE THREAD

**Issue by megasuperlexa** [TortugaPower/BookPlayer#397]
The non-square PNG art looks perfect in the app, however on the lock screen it has white stripes around it:

![App](https://i.imgur.com/b08BLTt.png "App")

![Lockscreen](https://i.imgur.com/HDRzpBq.png "Lockscreen")

**Comment by pichfl** [comment]
There is no defined behavior for this. MP4 container based audiobooks store the artwork as a single frame, MP3 does something different. Anything but the player screen is completely out of our hands. Consider writing a [bug report to Apple](https://bugreport.apple.com), but I don't think this will ever be fixed, transparency is not expected to work here.
