### ISSUE TITLE
Last played postition being reset on bluetooth connections with autoplay

### ISSUE THREAD

**Issue by ErinMorelli** [TortugaPower/BookPlayer#398]
* Do you want to request a *feature* or report a *bug*?

Report a bug

* What is the current behavior?

When I connect to my phone using bluetooth headphones (in this case, it is a pair of the Amazon Echo Buds) the app will start to auto-play the last book I was reading but go back to the beginning of the file instead of starting from where I had last stopped.

* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem. 

Stop listening to the book, close the app and disconnect the ear buds. Reconnect the ear buds and the auto-play will kick in and reset the play position.

* What is the expected behavior?

I would expect that the file would start playing from where I last left off.

* What is the motivation / use case for changing the behavior?

It's very frustrating to have to find my place again after the reset.

* Please tell us about your environment:
    * Version of BookPlayer: 3.5.1-4
    * Your Device and its OS version: 13.2.2

* Other information

This does not happen with bluetooth devices that do not invoke "autoplay" when they connect.

**Comment by GianniCarlo** [comment]
Hi @ErinMorelli ! thanks for reporting the issue. Have you seen if this happens with other books as well? Would it be possible that you share with us that book?

**Comment by ErinMorelli** [comment]
Hi @GianniCarlo! Here's a link to the book that I am experiencing the issue with: https://emorel.li/398-audiobook (it's "The Subtle Knife" by Philip Pullman). I saw it happen with the first book of this series as well ("The Golden Compass") but I don't have access to that file any more.

**Comment by GianniCarlo** [comment]
I've been trying to reproduce this, but to no avail.

I've put the book at around 93% completion for the tests, I'm using airpods, which have a similar autoplay feature but it only kicks in if the audio was interrupted when one is taken off and put back in. The book when downloaded with safari it came with a .m4b.mp4 extension, but if downloaded with chrome, it does come only with the .m4b extension. On the latter file I didn't find any problems with the metadata.

When you say
> close the app

Do you mean to just go to the home screen? or to force quit it from the app switcher?

I do remember we had a similar problem when executing the siri shortcut, that it sometimes didn't have the book ready and would start at the beginning, and this was the fix #365 . Maybe it's related 🤔

**Comment by GianniCarlo** [comment]
also a screen recording would be very helpful @ErinMorelli

**Comment by ErinMorelli** [comment]
By "close the app" I meant force quitting from the app switcher.

I'm working on getting a screen recording of this for you.

**Comment by GianniCarlo** [comment]
@Guy27 also experienced this (steps described in #402), but without the need of bluetooth earphones. So I think the problem lies in closing/force-quitting the app and generating the play event to continue playing the book 🤔. I'll test this scenario and see if I can reproduce it (I'm currently on iOS 13.2.3)

**Comment by niv** [comment]
I was seeing the same behaviour in my car, but the BT connection is not needed to trigger the bug for me.

Repro steps:
* Open BookPlayer, pick any book (I tested 3 from varied sources), skip to any progress. Play a bit, then pause.
* Go ho home screen, swipe up to go to app switcher and kill Bookplayer by swiping it away (or open enough apps to evict it from memory)
* Swipe down in control center, observe the media controls showing empty/no current media.
* Press Play: Bookplayer will reopen and restart the last-played book at position 0. I presume the BT connection triggers the same activity.

Note: Progress will resume correctly when instead opening Bookplayer via app icon.

iOS 13.2.3

**Comment by GianniCarlo** [comment]
I think #408 is a possible solution to this problem, I'll let you guys know when I got a beta up and running in case you're willing to test it out

**Comment by GianniCarlo** [comment]
@niv @ErinMorelli @guy27 guys I just uploaded a beta to TestFlight, it'd be great if you could help me test and see if the solution works 👌. Link to join: https://testflight.apple.com/join/FLv3zLyN

**Comment by niv** [comment]
@GianniCarlo Gave it a quick test on a second device and this particular issue seems solved! Couldn't get it to repro with any of the above mentioned cases.

**Comment by ErinMorelli** [comment]
@GianniCarlo Been using the beta app for the last day without any issues or having my book restart!

**Comment by GianniCarlo** [comment]
merged
