### ISSUE TITLE
Can no longer import files via Google Drive

### ISSUE THREAD

**Issue by cwagzz** [TortugaPower/BookPlayer#399]
I used to import files via Google Drive but now when I choose "open in" the app does not appear as an option.

I have also tried using the import function within the app to open directly from Google Drive and the files are faded out and I cannot select them to open into the app. 

Has a recent iOS update changed the functionality of the app?

Also, the files are .m4b. I have checked with a few .m4b files I had opened this way in the past and it no longer allows them to be imported.

**Comment by GianniCarlo** [comment]
hi @cwagzz , I recently downloaded Google Drive and did some tests. It looks like it's a Google Drive problem. I'll post my findings

**Comment by GianniCarlo** [comment]
First, I was able to select both .mp3 and .m4b files I recently uploaded to my account

![IMG_F496BC4BADB4-1](https://user-images.githubusercontent.com/14112819/69149046-a573d400-0aa3-11ea-8c9a-d10fee5a308c.jpeg)

It would be great if you could share with us one of these files that can't be selected.

Problems I found:
* The message `Waiting to down...` when the file is selected, actually stays there for a loooong while (and this was a 75mb audiobook), until it suddenly is already donwloaded. We've known for a while that Google Drive doesn't show feedback when downloading (at least now it shows the waiting-to-download message).
* I tried the "open in" from inside Google Drive, and sadly the `Preparing to export` phase, always fails for me (with a message about failing to download the book).

While the problems listed here are out of our hands, what we can do, is make sure that BookPlayer shows up in the iOS share sheet when mp3 and m4b files are trying to be shared

**Comment by GianniCarlo** [comment]
I've extracted the share sheet issue into #401 . The other issues regarding Google Drive sadly is out of our hands, and it relates on how they implement the file-provider support for iOS. I'm closing this issue, but feel free to continue the conversation 👍
