### ISSUE TITLE
Playback streaming

### ISSUE THREAD

**Issue by GianniCarlo** [TortugaPower/BookPlayer#4]
Allow to stream and reproduce an audiobook from an online service

**Comment by GianniCarlo** [comment]
This might need a switch from `AVAudioPlayer` to `AVPlayer` to support this feature

**Comment by pichfl** [comment]
> maybe in the far future, after exploring cloudkit and see if you could play your books without finishing the whole download - @GianniCarlo

I'm closing this to focus on upcoming 3.0.0 release. This will remain in the Roadmap project and will be reopened as needed.

**Comment by klamouri** [comment]
Hi all,

Sorry to dig this thread from the almost dead! It would be very cool to look at streaming from [audiobookshelf](https://github.com/advplyr/audiobookshelf) with a mode to download the audiobook, for traveling on a plane for example.
What would it bring?
* A Netflix / Audible like experience (stream books and download them for when we don't have connectivity)
* AudiobookShelf is able to scrape metadata on the books from various providers, this could help featuring more content in the app in the future.

**Comment by GianniCarlo** [comment]
Hey @klamouri ! thanks for linking to audiobookshelf, I had no idea it existed O:, I've been going through their docs, and it looks really good, we were currently working our server side with @ynunezaguirre , and this is something that could potentially bring us closer to v5.0.0 a lot faster, and it's open source as well 🎉. I'll test how cross sync works on their platform, and see how viable it is for us

**Comment by GianniCarlo** [comment]
circling back to this, it looks like they don't allow nested folders, which is a deal breaker for us. We can use it though as a guide on similar things that we want to accomplish though 👍

**Comment by klamouri** [comment]
Thanks for taking a deeper look at the suggestion! It's a shame it's not a good match!
What is the preliminary plan for the streaming? It seems you hinted at a custom made server application for BookPlayer?

**Comment by GianniCarlo** [comment]
yup, we're on it, v5.0.0 initial release won't include streaming, but with the library sync, we'll have the jump off point to start working on adding streaming and other things too 👍

**Comment by GianniCarlo** [comment]
Great news for this ticket, we'll be able to include it in the initial release of v5.0.0, it turns out that our change a while back to using `AVPlayer` and `AVURLAsset` was the heavy lifting for this one feature, since we had to implement the 'wait until ready to play', it was almost as simple as just loading a remote URL instead of a local URL for it to start streaming 🙌

**Comment by zfkdnop** [comment]
> Great news for this ticket, we'll be able to include it in the initial release of v5.0.0, it turns out that our change a while back to using `AVPlayer` and `AVURLAsset` was the heavy lifting for this one feature, since we had to implement the 'wait until ready to play', it was almost as simple as just loading a remote URL instead of a local URL for it to start streaming raised_hands

I love BookPlayer. Great work. I'll be adding to the Tip Jar again soon!

**Comment by GianniCarlo** [comment]
v5.0.0 is out and includes this feature 🙌
