### ISSUE TITLE
Query cum feature - Export audiobooks from app

### ISSUE THREAD

**Issue by panth** [TortugaPower/BookPlayer#400]
Hi 

I am using BookPlayer v 3.5.1-4 on iOS 12.3.1. I have recently taken a new android mobile so was trying to see if the books already imported into the app can be exported to a computer so that I can upload on the new mobile but could not see that. Any plans of having this feature built in ?

**Comment by pichfl** [comment]
Files imported into the application can be exported from the Library using the "Export" option available from the menu that appears when swiping left on a book.
