### ISSUE TITLE
IOS 13 bug resets audiobook progress

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#402]
HI guys,

ever since i upgraded to ios 13 i'm experiencing this issue:
1. open the app and listen to your favorite audiobook.
2. close the app.
3. pull down the menu in ios from the top of the screen
4. click play (note that it won't recognize the app as the app is closed, and it's ok)
5. the phone will identify that Bookplayer was the last one to play so it will trigger a play event, and not the book will start from the beginning loosing the progress made..

in previous ios versions it would have just kept playing from the last position

thanks!

**Comment by GianniCarlo** [comment]
This seems to be related to #398 since @ErinMorelli confirmed that he also kills the app, and his echo buds are performing the play action described on your step 4.

Let's continue the discussion on #398
