### ISSUE TITLE
Chapter List: Chapter Titles should not be abbreviated but break into multiple lines

### ISSUE THREAD

**Issue by anthonyattard** [TortugaPower/BookPlayer#403]
Would be nice to have a portrait mode so that long chapter names are fully visible. In portrait mode the names get cut off.

**Edit @pichfl** The chapter names in question are those in the Chapter List screen, see recording below.

**Comment by pichfl** [comment]
Can you provide a screenshot where chapters names are cut off? We had scrolling labels in place to work around this, so if this does not happen any longer, this is a bug to be fixed. 

An actual landscape player view is not something we plan to create right now.

**Comment by anthonyattard** [comment]
Thank you for the prompt reply @pichfl . Please see the gif blow that shows a screen recording of me on the chapter pane for approximately 30 seconds during which the chapter names do not scroll. Hopefully this helps.![issue](https://user-images.githubusercontent.com/8838135/69748863-121f4c00-10fe-11ea-97b1-bc7887ab037e.gif)

**Comment by pichfl** [comment]
Oh, the chapter names in the *Chapter List* are cut short. That is unfortunate and very much a bug. 

The more obvious solution to this would be to allow the titles in these cells to break into multiple lines, which is a much smaller change than making a full blown landscape mode and allows users to see the full chapter names even in portrait. 

If you have time to do so, this would be a very welcome fix.

In regards to landscape: We are in the middle of refactoring and adjusting the Player UI to further improve the experience. I can provide mockups for the landscape version of the new iteration later this year. Allowing landscape usage only on certain screens is a nightmare to control, so it's either all or nothing and all means I have to prepare quite a few mockups which I can't fit into the time I can spend on BookPlayer right now.

**Comment by GianniCarlo** [comment]
This is already solved and will be launched in the upcoming 3.8.2 version #454

**Comment by anthonyattard** [comment]
@GianniCarlo thanks! Just noticed the fix in the app.
