### ISSUE TITLE
Soft landing for sleep timer

### ISSUE THREAD

**Issue by TadDavisPhila** [TortugaPower/BookPlayer#404]
BookPlayer 3.5.1-4 on my iPhone12,1 running iOS 13.2.3

When sleep timer is set to anything other than Chapter End, set a mark at the selected time to resume playback, but allow audio to continue for another 30-40 seconds, gradually decreasing the volume to 0.

### Edit @pichfl

To simplify the above: Sleep timers currently pause the audio abruptly if the time option is used, which is not a pleasant experience when drifting off into sleep. 

- To change that, we should start fading out the audio after the timer countdown has finished
- We should only do so for time base countdowns, not for the chapter based option.
- We need to reset the volume to its original level
    - if the timer gets cancelled.
    - after the fade-out has happened and the audio was stopped.
- We also need to reset the playback position to the time where the countdown was finished.
- This will be the new default behavior, but can be disabled via the Settings screen, adding a new cell to the group "Playback settings" titled "Fade out when Sleep Timer ends" with the toggle defaulting to the on position

**Comment by pichfl** [comment]
This is a reasonable idea, I fleshed out the steps to make this in the description above.

**Comment by TadDavisPhila** [comment]
Don't know if I'm violating protocol by adding another comment, but.... well said. Very clear summary. Thanks!

**Comment by pichfl** [comment]
Not at all. I'm glad you don't mind me adjusting your description. We have new people wanting to help out and the better the summary, the easier it becomes to implement.

**Comment by GianniCarlo** [comment]
> #### To decide
> * [ ]  Is this an optional setting? If so, should this be the default behavior?

🤔 I think it should default to that, and if anyone asks for the abrupt interruption to be back, then we can consider making it an extra setting.

Re fading _after_ timer finishes, does the playback remain wherever it lands after the fading out?

**Comment by pichfl** [comment]
> * We also need to reset the playback position to the time where the countdown was finished.

no :)

**Comment by GianniCarlo** [comment]
This will be included in the next release 👍
