### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by allanlaal** [TortugaPower/BookPlayer#407]
any plans on making this multiplatform?

**Comment by GianniCarlo** [comment]
Hi @allanlaal , at some point I wanted to do it, but due to lack of time, I'd rather focus all my efforts on this version until it gets to multi-device support. Then it'd make more sense to me to start developing the app on Android

**Comment by GianniCarlo** [comment]
closing this issue since it's out of scope for this repo. Feel free to continue the conversation though

**Comment by pichfl** [comment]
I haven't used an Android device in years except for testing stuff, but you may want to take a look at https://github.com/PaulWoitaschek/Voice which might be a viable alternative to BookPlayer and is also Open Source. https://github.com/PaulWoitaschek/Voice
