### ISSUE TITLE
Support iOS 11 "Smart invert"

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#41]
Instead of providing a custom dark color scheme, support for the smart invert mode introduced in iOS 11 could provide similar results with less work.

**Comment by GianniCarlo** [comment]
good suggestion 🤔, this would be only for the users that have smart invert on right? is there a way to 'turn it on' for only the app?

**Comment by pichfl** [comment]
I don't think so. The feature can be configured to be triggered via the home button shortcut though.

You might have changed my mind, while the support would be good, it is no replacement for a real dark mode.

**Comment by pichfl** [comment]
We now provide a dark scheme and it's very likely we'll see official dark theme support in iOS 13, so I'm closing this for now. If anyone is in dire need of this feature, feel free to comment and I'll reopen it as needed.
