### ISSUE TITLE
Auto play not working - stops after every track

### ISSUE THREAD

**Issue by NemesiS153** [TortugaPower/BookPlayer#415]
Bug

Will not continue to next "track/chapter". Stops after each one. Different books have the same issue. 
Have reset phone
Turned on/off Autoplay Library
Happens on all Book types

Version - 3.6.0-3
IOS 13.3
Iphone XS Max

**Comment by niepiekm** [comment]
I was going to report that myself. After updating the app it won't play next track.

Version: 3.6.0-3
iOS 13.3
iPhone 7

**Comment by NemesiS153** [comment]
> I was going to report that myself. After updating the app it won't play next track.
> 
> Version: 3.6.0-3
> iOS 13.3
> iPhone 7

at least its not just me.

FYI, the app was updated overnight last night

**Comment by mvesci** [comment]
Same here. Worked yesterday. After the latest update, app stops after each file. Not good while driving.

**Comment by GianniCarlo** [comment]
Thanks for reporting this guys, we are looking into it

**Comment by GianniCarlo** [comment]
fixed by #416

**Comment by NemesiS153** [comment]
> fixed by #416

that the speed of service we like 😄 
thanks
