### ISSUE TITLE
Failure when import from multiple cloud services

### ISSUE THREAD

**Issue by Resonanz** [TortugaPower/BookPlayer#418]
I am running the latest BookPlayer 3.6.1-1 on iOS 13.3.

First, I love this app, so keep going !!! But.....

If I have a .zip file containing MP3 audiobook files, and I have downloaded it in the pCloud or OneDrive app so it is definitely offline and stored in full on my iPhone XR, then BookPlayer takes forever to Add it to itself. The message says "Waiting to down..." with the spinning circle thing, and sits there, well, forever.....

Is anyone looking at importing from cloud services? I am happy to test for them if I can, but either way I really would like this to be reliable. At the moment it is simply not working :-(

**Comment by GianniCarlo** [comment]
This goes along the same lines as #412 . Let's keep the discussion regarding this topic over there

**Comment by pichfl** [comment]
Have you tried going the other way?

Open OneDrive, tap on the … at the end of the file, select "Open in another app" from that menu and select BookPlayer from that dialog.
