### ISSUE TITLE
Tapping on a book in overview should start playback

### ISSUE THREAD

**Issue by winsmith** [TortugaPower/BookPlayer#420]
This is a feature request. 

When I cold launch the app, I find myself in the overview of all books. Tapping on a book gets me to the Now Playing screen.

Currently, I need another tap, on the Play button, to start playback. Instead, I propose the book should start playing immediately after I tap on it in the overview screen. 🙂

**Comment by GianniCarlo** [comment]
Hi @winsmith ! you can already do this if you tap the mini artwork on the overview/library screen. Let me know if that works for you

**Comment by winsmith** [comment]
That doesn't seem to work... tapping on the artwork both in the table view as well as in the overlay just opens the Now Playing screen but does not start playback
 
![ezgif-3-4d2bbfe4525c](https://user-images.githubusercontent.com/954120/73276679-5c4da800-41e9-11ea-9623-ce960e65336c.gif)

----

Alternative suggestion: I just want to tap only once when returning to the app, not twice. And I don't *really* want to hunt for a tiny tap target either. Maybe do it the other way round and open the **last played book** on startup? Then it's just one tap on the play button.

**Comment by pichfl** [comment]
This seems to be a bug. 

To verify: It does work if you dismiss the mini player. It does not if the mini player is present for the book you want to start. You can press the play button on the mini player for now, but this inconsistency must be resolved.

**Comment by GianniCarlo** [comment]
the bug is resolved in #422 and will be included in the next release 3.6.2 👍. Thanks for letting us know @winsmith
