### ISSUE TITLE
Feature request costume playback speed

### ISSUE THREAD

**Issue by KNiehus** [TortugaPower/BookPlayer#425]
I would like to request a feature.
Currently one can change the playback speed of the audiobook by tapping on the '1x' button and is the offered a variety of speeds raining from 0.75 to 2x in quarter increments as well as 2.5x.

When I listen to podcast I usually listen to them on 1.2x speed because I like to have everything a little faster. However, the option to that is 1.25x which is just a little too fast for my taste.

That is why I would like to request a costume playback speed.

I have multiple ideas on how to implement this: 

-  just adding the 1.2x playback speed

- creating a setting where the user can set a customisable playback speed that is then also available in the playback speed menu 

- or adding a setting that when turned on offers a bigger variety of playback speed in the menu e.g. increase by 0.05 instead of a quarter

I am using the app on an iPhone 11 with iOS 13.3 and Bookplayer 3.6.1-1.

I know this is quite niche thing to request but since you guys really seem to care about the user experience I thought I'd give it a try.

Keep up the great work! This is by far the best audiobook player and I really like it!

**Comment by pichfl** [comment]
A quick search should have brought up #224 and #281 which both are in consideration and will be implemented in the near future. Thanks for you vote on this, you are not alone when it comes to requests for finer grained controls and we will provide them hopefully soon and in a way that is easy to use.
