### ISSUE TITLE
3.6.2-1 Sleep Timer doesn't display remaining time in Player toolbar

### ISSUE THREAD

**Issue by patjolata** [TortugaPower/BookPlayer#426]
Since the update today the app is no longer showing the remaining time next to crescent moon symbol/sleep timer (see screen shot). The remaining time used to be to be displayed before.

![E9C1D3A9-1062-4A84-BEA7-FF4EE5E400A5](https://user-images.githubusercontent.com/53347808/74285608-87c2ad80-4d26-11ea-85ac-30f7c0fcac8f.jpeg)

* BookPlayer: 3.6.2-1
* Device: iPhone SE
* iOS 13.3.1

**Comment by pichfl** [comment]
The remaining time should show instead of the Moon while the timer is running. 
For some reason this isn't true when selecting "End of current chapter", we will investigate.

**Comment by patjolata** [comment]
@pichfl At the start it looks like that:

![IMG_3207](https://user-images.githubusercontent.com/53347808/74516829-670a7b80-4f11-11ea-8030-c9a88f442882.jpeg)

And later it changes to the behaviour with noch remaining time at all shown in my first post.

**Comment by GianniCarlo** [comment]
Thanks @patjolata , #432 fixes this issue and it will be released on the next version 👌
