### ISSUE TITLE
Bug: Player crashes when trying to use AirPlay

### ISSUE THREAD

**Issue by Team-Hufflepuff** [TortugaPower/BookPlayer#431]
I'm trying to use [AirServer for Mac](https://www.airserver.com/Mac) to AirPlay my audiobooks to my Mac, and the app crashes when I connect to AirPlay and hit Play. AirServer/AirPlay is working fine for other apps on my phone, like Castro, my podcast app.

I'm using an iPhone XR on 13.3.1 and BookPlayer is running 3.6.2. Let me know if you need more information!

**Comment by GianniCarlo** [comment]
Hi @Team-Hufflepuff , I just downloaded AirServer, and tried it, and it only works when it's in the mirrored mode, if the mac is just selected as a speaker, it looks like airserver crashes on my laptop, and then the audio never starts, see following gif:
![crash-airplay](https://user-images.githubusercontent.com/14112819/75121413-b6fbe780-5661-11ea-9043-3fe58b534b1a.gif)

I'd like to see if airplay works on an apple tv or homepod (I don't have neither of them :/) before doing more investigation, if someone who does have one can test, it'll be great

**Comment by pichfl** [comment]
I can't get it to work either, but it doesn't crash on me. I am able to use AirPlay on the Apple TV 3rd gen though.

**Comment by hypeitinc** [comment]
I can use it on Apple TV and also on AirServer on a MacBook. In both cases only if I go into mirrored mode. Then the airplay button in the app has no effect, neither has the control panel. I cannot pipe it to either by just using the airplay button. (The AirServer does not crash though)

**Comment by Team-Hufflepuff** [comment]
I should probably clarify, BookPlayer is what’s crashing on me, not AirServer.

**Comment by pichfl** [comment]
What type of audiobook are you playing? (mp3/m4a/m4b?)

**Comment by hypeitinc** [comment]
I have tried with mp3, m4a, wav.
Another observation: If I set the "Add a Lossless Quality Receiver" in AirServer/Audio, then I can play as expected (without mirroring). Weird thing then though, the AirServer notification for what track is playing keeps popping up (on the MacBook) every 5 seconds or so.

**Comment by pichfl** [comment]
@GianniCarlo is there any chance this could be related to the new audio engine we use?

**Comment by GianniCarlo** [comment]
mmmmm did it work in 3.5.x? out of the list of [these requirements](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/AirPlayGuide/EnrichYourAppforAirPlay/EnrichYourAppforAirPlay.html), I think the only we haven't done yet (or made sure of at least) is that the audio is properly routed 🤔. AVPlayer does have a property [allowsExternalPlayback](https://developer.apple.com/documentation/avfoundation/avplayer/1387441-allowsexternalplayback) which refers to AirPlay, but it's by default true, so that shouldn't be a problem

**Comment by GianniCarlo** [comment]
mmmm it looks like `allowsExternalPlayback` was renamed from `allowsAirPlayVideo`, and according to [this answer](https://stackoverflow.com/a/8808838/2105150) from StackOverflow, if we're just using audio, then we should set `false` to that flag

**Comment by GianniCarlo** [comment]
O: it does work, the fix is included now in the upcoming 3.7.0 release
