### ISSUE TITLE
Launch screen not adapted for dark mode

### ISSUE THREAD

**Issue by halleygen** [TortugaPower/BookPlayer#440]
* Do you want to request a *feature* or report a *bug*?
Bug

* What is the current behavior?
The launch screen remains white when device is set to dark mode.

* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem. 
Launch the app in dark mode. Ensure the device's brightness is not too high lest your eyes be fried.

[RPReplay_Final1585473313.MP4.zip](https://github.com/TortugaPower/BookPlayer/files/4398525/RPReplay_Final1585473313.MP4.zip)

* What is the expected behavior?
The launch screen is not white in dark mode.

* What is the motivation / use case for changing the behavior?
It hurts my eyes when opening the app and there is a blinding flash of white.

* Please tell us about your environment:
    * Version of BookPlayer
3.7.1

    * Your Device and its OS version
iPhone iOS13.4

* Other information

**Comment by pichfl** [comment]
Thanks for bringing this to our attention. 

@GianniCarlo if you need new design assets ping me.

**Comment by GianniCarlo** [comment]
It seems like the fix is an easy one when using the system dark mode: https://stackoverflow.com/a/56892137/2105150

**Comment by GianniCarlo** [comment]
Fixed in: https://github.com/TortugaPower/BookPlayer/pull/441
