### ISSUE TITLE
*feature* Please fit in iPad soon😭

### ISSUE THREAD

**Issue by jxyddtc** [TortugaPower/BookPlayer#445]
I really enjoy this app, but the unfit ui makes me sad.

**Comment by GianniCarlo** [comment]
The app is currently intended to be used in an iPhone, there's no native support for the iPad yet. Also please refer to the open issues list to avoid duplicating issues, anything iPad-support related should go in this one: https://github.com/TortugaPower/BookPlayer/issues/230
