### ISSUE TITLE
System black background

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#462]
Hello!

I'm interested in your code on a dark topic.

A question such as you in your application turned off the system theme theme?

**Comment by GianniCarlo** [comment]
Hi @rastaman111 , I'm not quite sure I understand, do you mean if we support dark mode? Linked to the phone dark mode configuration? If so, yes we already support that, from within the app's settings > Theme > 'Use system mode'

Let us know if that's not what you mean

**Comment by rastaman111** [comment]
I meant that when the phone has a dark topic, by going into the application it is still white, I did not find in info.plist responsible for this.

**Comment by GianniCarlo** [comment]
This is what I meant in regards to the UI, if you have that on, then the application will turn dark alongisde the rest of the iPhone
![IMG_2D8F3335F2EF-1](https://user-images.githubusercontent.com/14112819/81813571-4096b500-94ed-11ea-83d5-7892b811c310.jpeg)

If you mean where in the code everything happens, there's a class called `ThemeManager` which handles theme changes

**Comment by rastaman111** [comment]
I found this in the code, but I can’t figure out how to do it myself, copied it and it doesn’t work

**Comment by GianniCarlo** [comment]
If you're interested in handling themes in your app in a similar fashion as BookPlayer does, you can use the dependency https://github.com/GianniCarlo/Themeable (which was forked from https://github.com/latenightswift/night-mode ) and compare how BookPlayer makes use of that 👍
