### ISSUE TITLE
Can't Navigate Chapters With VoiceOver

### ISSUE THREAD

**Issue by parhamdoustdar** [TortugaPower/BookPlayer#465]
This is a bug when using the app with VoiceOver.

I'm not able to navigate by chapters. I expect that the option would be available somewhere in the player.

Here are the steps to reproduce:

1. Open Book Player, and open an audio book with VoiceOver running.
2. In the player, swipe to the right/left. You will notice that there are no options accessible to move between chapters.

This could just be me not knowing where to look, but I can't imagine this functionality being anywhere else in the application.

Currently, I can not use the functionality of moving between chapters, and it'd be great to have that instead of manually advancing forward.

I'm using the latest iOS on iPhone 8 and the latest Book Player version from the AppStore.

**Comment by GianniCarlo** [comment]
Hi @parhamdoustdar ! thanks for reporting this, 🤔 I was planning to hold off the next release until we can do the major release with the rework of the file structure, but this may be a fix worth justifying another patch version, and then we can also introduce the Romanian translation

**Comment by GianniCarlo** [comment]
just as a clarification, are you listening to books split among multiple mp3 files? or the ones represented by single m4b files?

**Comment by parhamdoustdar** [comment]
Thanks for considering a patch for this!
I'm listening to a single M4B file.
I just tried this with another M4B file and the "Chapters" button does get
read out. Is this button maybe hidden if the M4B has no chapters marked?

**Comment by GianniCarlo** [comment]
Yeah that's usually the case, if there are no chapters metadata in the file, which is common for mp3s, then the chapter button is hidden. In that case the solution would be to add the next track functionality. But in this case, if the button is showing up, I think we can do something better with a custom rotor, to enable fast jumping between chapters when available 🤔

**Comment by parhamdoustdar** [comment]
Having the ability to jump quickly between chapters using the router would
be great.
However, it seems like my original reported issue is not valid, because the
chapters button does show up when the metadata is available – it's just
that it wasn't available in that file.
So, you could close this issue if you like.

**Comment by GianniCarlo** [comment]
Naah, we do have a problem, and it's that we're hiding the button, we should keep the button and show it disabled so VoiceOver picks it up as well. The custom rotor feature could be extracted into another issue though

**Comment by GianniCarlo** [comment]
#468 includes the custom rotor, also in the next version, the chapter button is no longer hidden, it'll show disabled instead
