### ISSUE TITLE
Edit button is enabled when there is no item in the library / playlist view

### ISSUE THREAD

**Issue by mmurali88** [TortugaPower/BookPlayer#477]
* Do you want to request a *feature* or report a *bug*?    -  Reporting a bug
* What is the current behavior? -  Edit button is enabled when there is no item in the library / playlist view
* If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo / screenshot / screen recording of the problem.  - Have no items in the library view or no items in playlist view. Check the navigation bar for edit button
* What is the expected behavior? - Edit button should be disabled
* What is the motivation / use case for changing the behavior? - Edit button should not be accessible if there is no items to be sorted / Moved / Deleted
* Please tell us about your environment:
    * Version of BookPlayer - Dev
    * Your Device and its OS version Simulator / iOS 13
* Other information

**Comment by mmurali88** [comment]
https://github.com/TortugaPower/BookPlayer/pull/478 Fixes this issue.

**Comment by GianniCarlo** [comment]
merged 🎉
