### ISSUE TITLE
Misaligned Tick mark on the completed playlist while editing on the library view

### ISSUE THREAD

**Issue by mmurali88** [TortugaPower/BookPlayer#479]
While editing on the library view, tick mark on completed Playlist is pushed out to the corner of the screen rather than staying aligned like individual item

1. Have few books completed in the library view including a completed playlist
2. select edit and tap on select all. Look for the misaligned checkmark

### Expected behavior

The checkmark should be aligned

![Screen Shot 2020-07-07 at 6 36 45 PM](https://user-images.githubusercontent.com/4982265/86865157-55be3900-c083-11ea-880f-f0ea0702aca2.png)

**Comment by pichfl** [comment]
I just saw that the custom floating actions on the bottom are off as well.

**Comment by mmurali88** [comment]
Yes, It happens randomly but there should be a way to reproduce. I will create a different issue for that and for couple more

**Comment by GianniCarlo** [comment]
merged! thanks @mmurali88
