### ISSUE TITLE
CarPlay: Continue the last unfinished item inside a playlist

### ISSUE THREAD

**Issue by keatre** [TortugaPower/BookPlayer#481]
I use BookPlayer almost exclusively with CarPlay.  While on the native UI for iPhone, finding the last saved location works flawlessly.  However, when you start CarPlay - there's no way to say "Start where I left off".  Clicking the arrow on the book brings up all chapters.  I have to scroll to find the chapter that isn't marked as complete and click it.  For epic fantasy books that have 50-60 chapters, this can be a bit of a headache for short hops to the grocery store and back.

Below is a youtube link that shows this in action.  I'm on Chapter 16 of Book 2 of the Wheel of Time series.  When I start the car (2016 Chevy Colorado) BookPlayer doesn't seem to have an option to "Start where I left off" like the phone UI does.

https://youtu.be/V4aFIf4q_4U

BookPlayer version 3.9.0-1 - iOS 13.5.1

**Comment by pichfl** [comment]
#### The quick and dirty solution

We recommend [converting your books into m4b containers](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-combine-mp3-files-into-m4b-audio-books), which wrap the book into a convenient container and allow us to save the position in an easier way.

#### The actual issue

This is a feature request for a new entry inside a playlist on CarPlay: We need to add a new row to the beginning of playlists which allows people to jump straight into the first unfinished file in a playlist. Even though CarPlay is a nasty API, it should be doable. I can do testing in my car if someone has the time to look into the class that generates the lists.

**Comment by GianniCarlo** [comment]
This is already solved, if you select it from the Recent tab, it will autoplay, but if selected from the library it will open the playlist instead

**Comment by keatre** [comment]
As shown in the video, upon initial start of the vehicle - there is nothing in the "Recent" tab.

**Comment by GianniCarlo** [comment]
From the youtube video, I saw that the Recent tab wasn't fully rendering, this sometimes happens with the library as well, and it happens when carplay was just launched, not sure how they handle things internally since iOS 13 where they split the mirror behaviour, but just switch tabs again and it should render

**Comment by keatre** [comment]
> #### The quick and dirty solution
> We recommend [converting your books into m4b containers](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-combine-mp3-files-into-m4b-audio-books), which wrap the book into a convenient container and allow us to save the position in an easier way.
> 
> #### The actual issue
> This is a feature request for a new entry inside a playlist on CarPlay: We need to add a new row to the beginning of playlists which allows people to jump straight into the first unfinished file in a playlist. Even though CarPlay is a nasty API, it should be doable. I can do testing in my car if someone has the time to look into the class that generates the lists.

Ok thanks, I'll try converting this book to m4b container and see if that works easier.

**Comment by GianniCarlo** [comment]
> From the youtube video, I saw that the Recent tab wasn't fully rendering, this sometimes happens with the library as well, and it happens when carplay was just launched, not sure how they handle things internally since iOS 13 where they split the mirror behaviour, but just switch tabs again and it should render

@keatre let me know when you get the chance to test the Recent tab

**Comment by keatre** [comment]
> > From the youtube video, I saw that the Recent tab wasn't fully rendering, this sometimes happens with the library as well, and it happens when carplay was just launched, not sure how they handle things internally since iOS 13 where they split the mirror behaviour, but just switch tabs again and it should render
> 
> @keatre let me know when you get the chance to test the Recent tab

So just went out to the car and tried this again - still no luck.  Youtube video is attached.  It appears to function the same as the initial load.  Tried it about 3-4 times and it always acted the same.

https://youtu.be/QQLAyppRzkQ

However, if I started the book on my phone UI, then plugged it in - it did work as you described.  Maybe the initial load of CarPlay is causing problems?  I switch between BookPlayer and Spotify and it seems more stable if I leave from BookPlayer+CarPlay... leave the car... then come back and start BookPlayer+CarPlay.

Will work converting the MP3 files into a m4b and testing, as well.

**Comment by GianniCarlo** [comment]
Thanks for taking the time to test this. Hmmmmm, there's definitely an issue here, I'll try to debug this trying a similar configuration as you have 🤔

**Comment by keatre** [comment]
Sure thing - let me know if there's anything I can help test or work through.  Appreciate all the help!

**Comment by pichfl** [comment]
I'll get the car out tomorrow and do some testing as well.

**Comment by GianniCarlo** [comment]
Our CarPlay implementation has been reworked with the iOS 14 APIs in the latest release (v4.6.0) now available in the AppStore. Feel free to follow up if there's still an issue
