### ISSUE TITLE
Playback Speed Setting - 1.1x

### ISSUE THREAD

**Issue by mrwoo123** [TortugaPower/BookPlayer#487]
# 🗣 Context

App is fantastic. Easy to use & simple/useful features. 

Request: **adding 1.1 playback speed** 

Reasoning: 1.25 is a bit fast for my taste & I still would like the benefits of reducing the time required to listen to a full audiobook. **Example:** 

- For a 60 minute chapter, listening at 1.1 speed reduces time taken by ~6 minutes. 
- In my case, 16 hr audio book at 1.1 speed knocks off ~80 minutes. 

1.1 speed is hardly noticeable while listening time is reduced. A win/win in my opinion.

Also, likely a simple code update. Thoughts??

**Comment by pichfl** [comment]
#224 will bring improved fine grained speed controls. While adding a single speed is not a big issue, the ever growing list will become quite a messy UI otherwise.

**Comment by mrwoo123** [comment]
Thanks for the timely response Florian!
