### ISSUE TITLE
Files List: File names should not be abbreviated but break into multiple lines

### ISSUE THREAD

**Issue by anthonyattard** [TortugaPower/BookPlayer#489]
# 💬 Description

File names get cut off/abbreviated instead of breaking into multiple lines to fit the whole name. Pretty much the same issue I reported in #403 but on the file list view instead of the chapter list view (thanks again for the fix for that one!).

![IMG_2161](https://user-images.githubusercontent.com/8838135/88597821-f8cbf800-d01c-11ea-958e-00321fe76a36.PNG)

# 🦶 Reproduction Steps

Add a file that has a longish name.

# 🤝 Relationships

- Related PRs or Issues: #403

**Comment by GianniCarlo** [comment]
on v4.0.0 the entire file name should be visible now 👍
