### ISSUE TITLE
Support for iPad layout 

### ISSUE THREAD

**Issue by isaikrishnatej** [TortugaPower/BookPlayer#492]
# 🗣 Context

_Describe the context..._

# 💬 Narrative

As a ...
I want ...
So that ...

# 📝 Notes

_Provide additional notes..._

# 🎨 Design

_Provide design example, screenshot, text input/output etc_

# ✅ Acceptance Criteria

**GIVEN** ...
**WHEN** ...
**THEN** ...

# 🚫 Out of Scope

_Describe what is out of scope_

**Comment by pichfl** [comment]
A small note on Open-Source etiquette that needs to be mentioned: It is rather rude to not take the time to search for existing issues and then to not even add *any* description to your request. 

The title of this issue suggests it is already covered by #230
