### ISSUE TITLE
Bug: Deleting Currently Playing File

### ISSUE THREAD

**Issue by fowl2** [TortugaPower/BookPlayer#498]
# 🌎 Environment

 - OS Version: iOS 14 GM
 - Version/Release: 3.10.1

# 💬 Description

When you delete the file that is currently playing, it still shows as paused, but can't be resumed. The file also still takes up storage space until the app is force closed. 

Example 

![DD128819-AC05-4213-A594-4A8BD2C52FF5](https://user-images.githubusercontent.com/12844147/93654244-df18c100-fa5f-11ea-9009-a3ead50b088b.png)

**Comment by clarencecodes** [comment]
I managed to replicate this issue on iPhone 11 Simulator (iOS 13.6). Would be great if I could have a hand on this issue! :)

**Comment by pichfl** [comment]
@clarencecodes of course. Looking forward to your Pull Request!

**Comment by clarencecodes** [comment]
@pichfl Great, I'll work on this issue and send a PR soon!
