### ISSUE TITLE
GianniCarlo/Themeable error

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#499]
After updating my project, this error appeared
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/aleksandrsibircev/Desktop/introvert-develop1/Carthage/Build/iOS/Themeable.framework/Modules/Themeable.swiftmodule/arm64-apple-ios.swiftmodule

Tell me how to fix

**Comment by GianniCarlo** [comment]
Hi @rastaman111 , it should be enough to rerun `carthage update --platform ios`, let me know if the problem persist though

**Comment by rastaman111** [comment]
![Uploading Снимок экрана 2020-09-30 в 09.17.42.png…]()

**Comment by rastaman111** [comment]
<img width="1365" alt="Снимок экрана 2020-09-30 в 09 17 42" src="https://user-images.githubusercontent.com/15727518/94649653-c92bbb80-02fd-11eb-8023-7d6f5c8f38ff.png">

**Comment by rastaman111** [comment]
@GianniCarlo an error occurs when performing an update

**Comment by clarencecodes** [comment]
Hey @rastaman111, I had a similar issue the other day. Seems like an issue with Carthage and Xcode 12 - https://github.com/Carthage/Carthage/issues/3019. One workaround which I did was to build the project using an earlier version of Xcode (I used Xcode 11.6).

I found this to be a good read for managing multiple Xcode versions: https://www.donnywals.com/installing-multiple-xcode-versions-with-xcversion/

**Comment by GianniCarlo** [comment]
Yeah I'm experiencing this issue but with the Kingfisher dependency, I'm looking into maybe transitioning the project to Cocoapods as dependency manager 🤔

**Comment by GianniCarlo** [comment]
#507 addresses this issue and it'll be merged later today after some tests 👍

**Comment by GianniCarlo** [comment]
@rastaman111 @clarencecodes this should be ok now on the `develop` branch, we now manage things with the Swift Package Manager which is already integrated/managed by Xcode.  I'm closing the issue, but feel free to continue the discussion
