### ISSUE TITLE
CarPlay: Playback controls unresponsive (via BookPlayer playback screen, Siri, Apple Watch app)

### ISSUE THREAD

**Issue by theboyk** [TortugaPower/BookPlayer#501]
# 🌎 Environment

 - OS Version: Apple CarPlay via iOS 14.0.1
 - Version/Release: 3.10.1-1

# 💬 Description

When using BookPlayer via Apple CarPlay, while an audiobook is playing, but I'm in another CarPlay app (Apple Maps, Waze, etc.), when I attempt to pause a book, BookPlayer will not pause playback. If I attempt to navigate to the BookPlayer playback screen, it will quickly land on the playback screen, but then immediately kick back to the library (list of audiobooks) screen. Multiple attempts at getting to an audiobook's playback screen (the one playing, or any other in the library) will continue to kick me back to the library. if I continue to try and get to the playback screen, sometimes it will stick, but at this point, tapping the pause button does not pause the playback (even though the icon changes). The controls are completely unresponsive in terms of pausing the audio.

As well, using Siri to try and pause the playback fails (continues to play). Same with attempting to pause playback via the Apple Watch app (it just continues to play). The only way to pause playback is to use the iPhone app; pausing via the iPhone app works (but, not really an option when driving unless a passenger is able to do it).

This issue _is not_ consistent in that when I first start playing an audiobook, the controls work fine. But as I listen to audiobooks via CarPlay on a daily basis, the issue _is_ consistent as it eventually happens (on a daily basis). I have not be able to narrow down what causes this; but, typically, I get in the car and play whatever book it is I'm listening to. Then, I'll start of Waze for navigation. And then I drive. Playback control will be working fine; but, eventually, they fail and it becomes impossible to pause the playback without using the phone.

# 🦶 Reproduction Steps

Steps to reproduce the behavior, provide an example of the command line issued:
1. Play an audiobook via CarPlay.
2. Switch to another app (Apple Maps, Waze, etc.)
3. Drive
4. Attempt to pause the audiobook via the in-app playback controls, Siri or Apple Watch (after an undetermined amount of time).

# 🤔 Expected Results

- I can access the BookPlayer in-app playback screen to pause the audiobook.
- I can use Siri to pause the audiobook.
- I can use the Apple Watch app to pause the audiobook.

# 😲 Actual Results

Audiobook playback will not pause.

- The in-app playback screen kicks you back to the library (or, if you can get it to stick on the playback screen, the controls do not work).
- Siri will not pause playback.
- The Apple Watch app will not pause playback.

**Comment by GianniCarlo** [comment]
Hi @theboyk ! thanks for reporting this, my car is currently undergoing maintenance so I won't be able to test this for a while yet :/, but if any one else wants to help debug this, any help is always welcome 😁

**Comment by pichfl** [comment]
Yeah I noticed similar issues. Debugging CarPlay is a mess, for me it means sitting in my car in the driveway and hoping for the Wifi to be still in reach 😄 

Not sure what changed, but we are most likely missing some new config or changed hooks. CarPlay is like working through a key hole, not exactly a pleasant dev experience but it would be nice to improve this.

**Comment by theboyk** [comment]
Wondering if there's any way the project could be built against the latest version of Xcode/newer iOS version? I downloaded the project today and tried to do this, just to see if it'd help (as this happens so often it's becoming unusable), but because my developer account isn't part of the MFi program, my provisioning profile fails (as there's some CarPlay specific aspects of the provisioning profile that require the MFi program)?

**Comment by pichfl** [comment]
You should be able to apply for a CardPlay certificate [here](https://developer.apple.com/carplay/) at the very bottom of the page before the footer (Section: Tell us about your apps that have the potential to be supported by CarPlay.)

**Comment by GianniCarlo** [comment]
Re: latest Xcode, yeah I'm working on that part, Carthage has some issues in the latest Xcode, so I'm looking into replacing it altogether with the Swift Package Manager to avoid future problems

**Comment by pichfl** [comment]
I can't reproduce this any longer using my wired USB connection. @theboyk do you use wired CarPlay and does it work for you by now?

**Comment by kmaling** [comment]
Sorry guys. Moved my audiobook library into PLEX and started using Prologue for iPhone & CarPlay playback, so haven't been running BookPlayer since late 2020. Sorry.

**Comment by pichfl** [comment]
@kmaling Don't be! If you have Plex that sounds like a nice option 👍

**Comment by GianniCarlo** [comment]
The new CarPlay implementation we introduced in v4.6.0 is independent of the state of the main iOS app, so this shouldn't keep happening. Feel free to follow up if this is still an issue
