### ISSUE TITLE
Allow manual duration for sleep timer

### ISSUE THREAD

**Issue by ghost** [TortugaPower/BookPlayer#503]
When you tap on the sleep timer at the bottom left corner with the selected book at full screen, you are given a few options. Ignoring “Off”, we have the choices of 5 min, 10 min, 15 min, 30 min, 45 min, and 1 hour. Near the end of this sequence the jumps become pretty high, and thus it would be useful for the option to manually set the duration for the sleep timer. This ability to set the sleep timer to a precise amount of time would surely be useful to many.

**Comment by pichfl** [comment]
Yes indeed. This option will become available when the new Card based UI will become available as described in #281 - which needs to be updated with the latest mocks as Gianni and I worked quite a bit on that.

**Comment by GianniCarlo** [comment]
This has been solved in the latest release (v4.4.5) 👌
