### ISSUE TITLE
Exclude from ITunes backup

### ISSUE THREAD

**Issue by Guy27** [TortugaPower/BookPlayer#506]
# 🗣 Context

Hi Folks,
is there a way for you to allow us to mark a book / library to exclude from itunes backup?
i've reached to a point where i have about 100GB of books and every backup takes forever where this content isn't a necessary backup content. 

backing up to the PC takes forever with such a huge library, (creating duplicates since if you already have those files stored on your pc, the backup simply encrypts and restore).
backing up to icloud consumes tons of space and takes forever since it's over the net

**Comment by avioli** [comment]
I disabled app backup altogether since all my audiobooks are coming from a storage/backup anyway.

**Comment by avioli** [comment]
I wonder if the manual solution will work:

A) Add .nosync to a folder or file name
B) A folder called "tmp" or ending with ".tmp" won't be synced

**Comment by GianniCarlo** [comment]
This was addressed in [this PR](https://github.com/TortugaPower/BookPlayer/pull/614), which is included in the next upcoming version v4.1.0
