### ISSUE TITLE
Playback Speed control in CarPlay

### ISSUE THREAD

**Issue by dkBrazz** [TortugaPower/BookPlayer#509]
Didn't find how to control playback speed in CarPlay, have to pick the phone for this

Is it possible to add such control on the CarPlay UI?

**Comment by pichfl** [comment]
As far as I understand the current design, and with the current and very limited API it is not possible to show custom controls on the playback screen.

I'm hoping to revisit this at some point in a distant future where Apple allows us to control the UI more directly.

**Comment by dkBrazz** [comment]
Can playback speed be controlled with voice commands?

**Comment by pichfl** [comment]
I think it should be possible to add additional Siri triggers to adjust playback speed. If you have a moment, I'd appreciate a separate issue for that 🙂

**Comment by pichfl** [comment]
@GianniCarlo found the appropriate method which can apply this https://github.com/TortugaPower/BookPlayer/issues/513#issuecomment-724150210

> I found it! `MPChangePlaybackRateCommand`, implementing this in the `AppDelegate` alongside the other commands for `MPRemoteCommandCenter` should enable the speed toggle from CarPlay (maybe from the locked screen as well?)

**Comment by GianniCarlo** [comment]
interesting thing, it looks like the `MPRemoteCommandCenter` can only display **_correctly_** speeds from 0.5x to 2x, jumping by intervals of 0.25 minimum. So we have two options, either make available a separate speed array, which woud only work for remote commands and properly display the information, or make all the speed options available, but have the media center display incorrect information for speed different than 0.5x - 2x (in-between intervals of 0.25)

**Comment by mttjj** [comment]
> As far as I understand the current design, and with the current and very limited API it is not possible to show custom controls on the playback screen.
> 
> I'm hoping to revisit this at some point in a distant future where Apple allows us to control the UI more directly.

I wonder how Marco Arment does it then. Overcast has support for speed settings and even chapter navigation on the CarPlay interface. I think this would be a really awesome addition to the app.

**Comment by dkBrazz** [comment]
Checked Overcast in CarPlay. 
He really managed to add custom buttons into the Player screen. And there is a button which opens a list of custom speed values, similar to BookPlayer dropdown on iPhone

**Comment by GianniCarlo** [comment]
@dkBrazz @mttjj this looks to be related to new apis introduced in iOS 14 for CarPlay ([related WWDC video on the subject](https://developer.apple.com/videos/play/wwdc2020/10635/?time=56)). I do agree that it will be a great improvement, but since it requires iOS 14+ and we support iOS 13, I'm not too thrilled yet to jump at it and possibly support two sets of apis for it. Maybe later this year we can drop support for iOS 13 and rework the entire carplay implementation 🤔, we have to evaluate it yet

**Comment by GianniCarlo** [comment]
This was included in the latest release (v4.6.0) now available in the AppStore 🙌
