### ISSUE TITLE
Please do a version for iPad

### ISSUE THREAD

**Issue by b3rrym** [TortugaPower/BookPlayer#536]
I've switched from my iPhone to a iPad but recognised that your great app is not supported. Please bring a version for the iPad, it looks how so horrible, thank you all very much,, would be very happy about a version for iPad.

**Comment by pichfl** [comment]
there will be an iPad version in the future but it takes time and resources we do not have right now. This has been requested previously so this issue is a duplicate of #230 and will be closed.
