### ISSUE TITLE
Minor improvement to german Strings

### ISSUE THREAD

**Issue by Murcl** [TortugaPower/BookPlayer#537]
# 🌎 Environment

 - OS Version: 14.3
 - Version/Release: 3.11.0-2

# 💬 Description

I found 2 strings that could be improved in the german version.

# 🦶 Reproduction Steps

The 2 strings:
1. Siri Shortcuts -- Resume last book: the german string says "Zuletzt gespieltes Buch fortzusetzen" but I think it should mean "Zuletzt gespieltes Buch fortsetzen"
2. On the main screen, when you select all playlists, the string "deselect all" says "Keine". It would be a bit clearer if it said "Alle abwählen", which would be consistent with the "Alle auswählen" when you don't have all the items selected.

@pichfl, what do you think of it?

**Comment by pichfl** [comment]
Oh most definitely a good idea. The current translation was made rather quickly. Will change on Localize so @GianniCarlo can prepare a bugfix in one of the next releases.

**Comment by Murcl** [comment]
Thank you @pichfl!

**Comment by GianniCarlo** [comment]
This will be included in the next release 3.11.1
