### ISSUE TITLE
Bug: Tip Pricing Doesn’t match

### ISSUE THREAD

**Issue by fowl2** [TortugaPower/BookPlayer#545]
# 🌎 Environment

 - OS Version: iOS 14.5 (18E5140k)
 - Version/Release: 3.11.0-2

# 💬 Description

Here is a screenshot of the "Tip Jar" screen on my device. 

![image](https://user-images.githubusercontent.com/12844147/107354847-c732fe00-6b22-11eb-8b95-e998846104f9.jpeg) 

And here is the purchase that was actually made:

![image](https://user-images.githubusercontent.com/12844147/107354903-ddd95500-6b22-11eb-812a-48dcad539721.jpeg)

Note that the first says $4.99 for but I was actually charged $7.99!

Yes I should've read the confirmation screen better (and I'm *not* asking for a refund), but this is clearly suboptimal. I'm guessing the buttons are hard coded instead of getting the price from the App Store for my region.

**Comment by GianniCarlo** [comment]
Oh damn, yeah that's bad, it's as you say, the values are hard-coded in the app. I'll work on it this week to figure out how to read them from the App Store directly based on region. Thanks for reporting it @fowl2

**Comment by GianniCarlo** [comment]
This is solved with https://github.com/TortugaPower/BookPlayer/pull/546 I'll include it in the next release. Thanks again @fowl2 !
