### ISSUE TITLE
Access built-in media libraries

### ISSUE THREAD

**Issue by papaGregor** [TortugaPower/BookPlayer#547]
It seems to me that one of the biggest issues for a third-party app like this is getting content into the app, especially since the demise of iTunes. I’ve just discovered that, at least in iOS 14, the app can request access to the user’s media libraries, so that the media does not have to be separately imported into the third-party app. Bookmobile Audiobook Player does this as of today, if you want to check it out. I’ve attached a screenshot of my Privacy settings after Bookmobile made the request.
![27025CB4-2A96-4C64-9541-9CEE218C7973](https://user-images.githubusercontent.com/17756141/107725798-e5703980-6c9b-11eb-9c11-6cfb1e994ae3.png)

**Comment by pichfl** [comment]
We are aware of this option, but importing files into these built-in libraries is even more involved than importing a file into BookPlayer using a cloud provider which integrates well with the iOS Files.app. To make the project less reliant on cloud services and iTunes, we are planning to provide a web importer which allows you to send files directly to the app even from devices which do not support AirDrop (PCs etc.) See #362 for details.

Adding support for Apple Music and local libraries outside of BookPlayer may come as a big new feature in a later version, but do not hold your breath for now.

For anyone wanting to help us out implementing this, please drop by our Discord server first, there is much to discuss behind the scenes which is beyond the scope of this issue.

I'll close this issue as this is not immediately actionable.

**Comment by papaGregor** [comment]
Hi, Florian -

Sorry, I was unclear. I didn’t mean actually importing the files in the sense of copying. Bookmobile just acquires read access to the built-in media libraries. I don’t know if that simplifies the issue as far as the coding goes…

On Feb 14, 2021, at 9:22 AM, Florian Pichler <notifications@github.com> wrote:

﻿
We are aware of this option, but importing files into these built-in libraries is even more involved than importing a file into BookPlayer using a cloud provider which integrates well with the iOS Files.app. To make the project less reliant on cloud services and iTunes, we are planning to provide a web importer which allows you to send files directly to the app even from devices which do not support AirDrop (PCs etc.) See #362 for details.

Adding support for Apple Music and local libraries outside of BookPlayer may come as a big new feature in a later version, but do not hold your breath for now.

For anyone wanting to help us out implementing this, please drop by our Discord server first, there is much to discuss behind the scenes which is beyond the scope of this issue.

I'll close this issue as this is not immediately actionable.

**Comment by pichfl** [comment]
That was very clear, I think you missunderstood me here. Without iTunes/Music it's not possible to *add* files to the internal Libraries in the first place, which is the reason why BookPlayer exists as an alternative. 

We are aware that some publishers publish audiobooks to Apple Music and we will explore showing files from these Libraries in the future, but right now this is beyond what BookPlayer is meant to do: Provide an easy way to listen to actual mp3/m4b files.
