### ISSUE TITLE
Unable to copy books using file sync (Potential regression)

### ISSUE THREAD

**Issue by master0v** [TortugaPower/BookPlayer#552]
# 🌎 Environment

 - OS Version: BigSur + iOS 14.4
 - Version/Release: Latest from App Store

# 💬 Description
It used to be possible to connect the phone using the usb cable and drag/drop books into the BookPlayer folder in order to copy them to the player.  It no longer works

<img width="715" alt="Screen Shot 2021-02-20 at 8 15 51 AM" src="https://user-images.githubusercontent.com/18746987/108595133-9f2e7080-7354-11eb-9a12-7c986db68212.png">

# 🦶 Reproduction Steps

Steps to reproduce the behavior, provide an example of the command line issued:
1. Connect the phone using usb cable to a mac
2. drag/drop files into the book player files folder
3. Launch BookPlayer

# 🤔 Expected Results
Player prompts the user which playlist they want to import the files into

# 😲 Actual Results
Nothing happens

**Comment by GianniCarlo** [comment]
Hi @master0v ! Yes, it's been some time since we disabled direct folder support due to a bug, we're currently working on it in this Sprint, so hopefully we have it back in the next version near the start of March. The current workaround is to first zip the folders and then pass that zip file(s) to the app as you're doing with the folders

**Comment by master0v** [comment]
Thanks for the workaround.  I also found that when copying entire folder over Airdrop, iOS does not present bookplayer as a target.  It does so only when dropping a bunch of mp3 files.  Should I file it as issue, or is this also known?

**Comment by GianniCarlo** [comment]
yes that's related to folder support, once we enable it back again, BookPlayer will show up in the list 👍, thanks for your attention to detail 😁

**Comment by GianniCarlo** [comment]
This should be already be solved in the latest version 👌, please feel free to continue the conversation if you still have this issue
