### ISSUE TITLE
Despite cover art is saved in id3 tag it does not shows up

### ISSUE THREAD

**Issue by menkab** [TortugaPower/BookPlayer#553]
I have cover art written into id3 tag of the mp3 files, but it does not show up.
File size is about 78Kb and ist jpeg.

https://github.com/TortugaPower/BookPlayer/issues/512#issuecomment-721617777

**Comment by GianniCarlo** [comment]
This may be related to the issue introduced in the last version, this PR should fix it https://github.com/TortugaPower/BookPlayer/pull/560

**Comment by pichfl** [comment]
This may be related to #556

**Comment by GianniCarlo** [comment]
The new version was approved, in a few hours it should appear in the App Store, feel free to reopen if the issue persists
