### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by blckbrd14** [TortugaPower/BookPlayer#555]
Great work all around with this app, thank you! Here are two suggestions for new features:

• A theme that mimics Audible app’s dark grey scheme for all the people who have a strong emotional connection to that specific tint from hours of using Audible.
• A weird feature I haven’t seen in any app: a sleeping aid that remembers your original place in the book. In other words, the ability to play books without registering the final position in the timeline. Sometimes you just want to sleep and not pay attention to the book. So you hit this special play button and the book plays for x minutes. When it stops, the location resets to the position you started from.

**Comment by pichfl** [comment]
For other people wanting to post suggestions: We do have the [Discussions feature](https://github.com/TortugaPower/BookPlayer/discussions) enabled for this repository, please use that if you do not have problems with BookPlayer but want to contribute with ideas.

1. New theme: New themes will drop more regularly in the future. The suggestion is duly noted. We won't copy verbatim, but I think getting inspiration is acceptable.
2. There is no need for a special play button for this once the new bookmarks feature arrives. #127 is tracking this. We will provide automatic bookmarks for the last time you hit play/pause. 

As this issue does not contain any problems with the current build, I'm closing it. This does not mean we have to stop discussion, it's just a measure to keep a good overview.
