### ISSUE TITLE
m4b with png artwork not showing.

### ISSUE THREAD

**Issue by xvaara** [TortugaPower/BookPlayer#556]
# 🌎 Environment

 - OS Version: 14.4
 - Version/Release: 3.11.2-1

# 💬 Description

m4b with png artwork not showing.

# 🦶 Reproduction Steps

Created a m4b with audiobookbinder, added a png as artwork.

# 🤔 Expected Results

Show artwork on list and play screen.

# 😲 Actual Results

No artwork.
 ffprobe give:
```
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 106 kb/s (default)
    Metadata:
      creation_time   : 2021-02-23T10:14:25.000000Z
    Stream #0:1: Video: png, rgb24(pc), 400x480, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Stream #0:2(und): Data: bin_data (text / 0x74786574), 0 kb/s
```
Using itunes I removed the png and added jpg of the cover.
```
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 400x480 [SAR 72:72 DAR 5:6], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Stream #0:2(und): Data: bin_data (text / 0x74786574), 0 kb/s
```
still no luck.

I looked at another m4b that works in BookPlayer and it has:
```
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Data: bin_data (text / 0x74786574)
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:2: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
```

**Comment by XiaoHippo** [comment]
Seeing the same thing, but with JPEG cover art. Worked on an older version but not on the latest that was released yesterday.

**Comment by Klench** [comment]
I am experiencing the same issue, with a jpg image.

**Comment by lilgrassin** [comment]
Same here, experiencing missing cover art for any audiobooks imported since the latest app update.

**Comment by pichfl** [comment]
Can confirm this is happening. Not sure why though.

**Comment by GianniCarlo** [comment]
I've forgotten to mention, I've scheduled this to be reviewed next sprint that starts next week, this may prompt a patch release to get the fix out by next week. Thanks everyone for reporting this 🙂

**Comment by david0z3ro** [comment]
Thanks for this amazing app.
Indeed, no art work is showing up in my side as well. It does show up in native iBooks app though. File is acquired in BookPlayer via download from NAS.

**Comment by GianniCarlo** [comment]
This PR fixes this issue (retroactively as well) https://github.com/TortugaPower/BookPlayer/pull/560

**Comment by GianniCarlo** [comment]
The new version was approved 👍, in a few hours it should appear in the App Store, feel free to reopen if the issue persists
