### ISSUE TITLE
App plays audiobooks on iPhone but not on Apple Watch

### ISSUE THREAD

**Issue by Stephanieml3** [TortugaPower/BookPlayer#571]
I'm unable to hear my audiobooks on my Apple Watch using bluetooth earbuds. I hear them on my iPhone instead. I'm assuming the audiobooks haven't synced to my watch even though I can select them on the Apple Watch app. 
Thanks for your help with this issue!

**Comment by pichfl** [comment]
Books are not playing directly on the Watch right now. The Watch app is currently only a companion for the main application. 

This will change once #464 is resolved and will most likely take some time as we have to refactor how we handle books in general first.

I'll close this as a duplicate for now, if I mistook something here, do not hesitate to clarify and I'll reopen the issue.

**Comment by Stephanieml3** [comment]
Thank you, Florian for this information! Unfortunately, I can't use this app until this issue is resolved. Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
