### ISSUE TITLE
Heavy battery drain playing MP3 to Bluetooth speaker

### ISSUE THREAD

**Issue by eluphira** [TortugaPower/BookPlayer#573]
When playing a book consisting of multiple MP3 files to a Bluetooth speaker, battery drain is heavy and the back of the iPhone becomes warm.  By heavy I mean the battery level dropped from 79% to 71% in 2 minutes.

The iPhone is in airplane mode. WiFi is off. No other apps should be in background.

With Bluetooth off, playing to the internal speaker, battery drain is slow as expected.

Playback speed is 1.0.

Settings > Battery > Battery Health > Maximum Capacity is 94%

Battery drain is slow as expected when playing the same book with MP3 Audiobook Player through a Bluetooth speaker.

BookPlayer 3.12.0-2
iOS 14.4
iPhone 7 Plus

**Comment by ChrisNFS** [comment]
Same problem here. Massive (read very heavy) battery drain using Bluetooth (AirPods). Battery level dropped from 95% to 30% in 2 hours, no other apps used. Bookplayer was in background, playing a single MB4 audiobook. Problems exists with 3.12.0-2, not before. I am using iOS 14.4.2.

**Comment by GianniCarlo** [comment]
in the latest version (v4.5.0) we improved battery performance, can you verify if this is still happening?

**Comment by ChrisNFS** [comment]
The problem with the battery drain does no longer exist. Thank you!

„BookPlayer“ is just wonderful!! Please keep on the good works!

Cheers
Chris

**Comment by GianniCarlo** [comment]
Thanks a lot for the confirmation!! 🥳
