### ISSUE TITLE
Sync files between iphone and ipad

### ISSUE THREAD

**Issue by mark-mess** [TortugaPower/BookPlayer#586]
Hi, I want to use BookPlayer on my iphone and my ipad.  Right now I do not see my files from my iPhone when I go to the app on my iPad. Is there a way to sync them?
Thanks! Mark

**Comment by GianniCarlo** [comment]
Hi @mark-mess , we currently don't have a way to do cross-device synchronization, it's in our pipeline though 🙂. Side note, If you want to share one book from your phone to your ipad, you can 'Share' it from the options menu of a book (not playlist) and it will open up the iOS share sheet, allowing you to send it via Airdrop to your iPad (current progress won't be sent :/)

**Comment by mark-mess** [comment]
Thanks!  I didn’t know I could airdrop. Thats works great.
I appreciate the reply.
Mark

**Comment by Lwio** [comment]
Has there been any progress on this?
This is the top feature I am looking for.

**Comment by GianniCarlo** [comment]
Not yet, but now that we have the bound features out, cross sync is our next big milestone to tackle

**Comment by Lwio** [comment]
Thank you.

**Comment by GianniCarlo** [comment]
I'm closing this issue in favor of #287
