### ISSUE TITLE
MacOS app support

### ISSUE THREAD

**Issue by technolaaji** [TortugaPower/BookPlayer#606]
# 🗣 Supporting macos to run bookplayer as an ios app

some of the apps that I use have some sort of compatibility to run on macos (M1 version). it would be ideal if the mobile app can be supported on macos to run but not fully supported as in width screen but rather just run the app directly with the iphone default size. take overcast as an example where you can run the app on the m1 mac at the size of the iphone screen. the ability to listen to an audiobook on your phone then continue on your laptop is quite of a gamechanger to me 

# 📝 Notes

I don't think there should be any modifications that much to make it run on macos, no design changes or anything

# 🎨 Design

no design changes, iphone sized app that runs like what runs on ios is pretty good enough 

# ✅ Acceptance Criteria

**GIVEN** not giving nor assigning this to anyone, just mentioning it to see if the community agree on this
**WHEN** no specific timing, it is a nice addition to have for the app

# 🚫 Out of Scope

not much honestly, correct me if I am wrong if there is something beyond the scope of the project

**Comment by GianniCarlo** [comment]
With v4.0.0 out now, we have enabled the app to be available for the appstore on Mac M1.

There are some reordering issues with v4.0.0 that will be addressed in v4.0.1 which is pending review, but other than that, you should be able to drag files from finder on top of the app and import files

Syncing progress cross device isn't yet supported, but we are moving towards that goal

**Comment by skobylite** [comment]
Hey GianniCarlo - is this something you guys have made any progress on with cross device syncing to mac version?

**Comment by GianniCarlo** [comment]
still working on it @skobylite, there has been some other functionality that we have ready for v5.0.0 that has taken some focus away from the cross device sync (search support, share extension, new selection and edit controls), and we only have one more major feature to complete before going back to cross device sync, which is editing book metadata + artwork, once that's done, we can fully go back to cross device sync and finish v5.0.0 feature set
