### ISSUE TITLE
Bug: Random playlists vanish after dragging and sorting a file within a different playlist

### ISSUE THREAD

**Issue by kirtangor** [TortugaPower/BookPlayer#609]
# 🌎 Environment

 - OS Version: 14.4
 - Phone: iPhone XS
 - Version/Release: 4.0.0-7

# 💬 Description

I lost around 40-50 of my audiobooks that were in a couple of playlist after dragging a file to arrange its order within a different playlist.

This seems like a very weird bug, but I am heartbroken at losing so many good books gathered over the course of many months.

I see that the files still seem to be physically present. I can see them contributing to the phone's storage within the app. However, they are no longer visible in the app. PLEASE HELP!!!! 

# 🦶 Reproduction Steps

1. Create three playlists __Suspense, __Horror, __Fiction
2. Add a few files to each playlist
3. Drag a file from the bottom of the __Horror playlist to the top of the list
4. When you are at the top, drag the file over the title of the playlist
5. Close the app
6. Open the app again, the __Suspense and __Horror playlist have vanished

**Comment by kirtangor** [comment]
I see that a hotfix for a reorder bug is already in review. However, is the hotfix addressing the bug and would it also bring back the files lost due to it?

**Comment by GianniCarlo** [comment]
Hi @kirtangor , that will be addressed in a upcoming PR, we are working on a data management settings, so the orphaned files that are still on disk, can be found and matched with possibly Book objects that got their Folder or Library relationship cut off and are on limbo (or they can be deleted too, whichever course the user decides)

I see that 4.0.1 was just approved by Apple, so I'm closing this issue, feel free to reopen if you find an issue again with reordering.

**Comment by kirtangor** [comment]
Hi @GianniCarlo, thanks for the update! I just installed the latest version and unfortunately the files are still not back. Would the app perform an auto-scan the first time it launches to fix this? I tried opening / re-opening the app multiple times and still do not see those files. The bug that actually caused this problem seems to have been fixed though.

**Comment by kirtangor** [comment]
Since I am not a collaborator on the project, I cannot reopen the issue. Would you like me to file a new one?

A workaround to export those files out of the disk would also be appreciated, ad-interim.

Thanks again for all your work on the app - It's amazing!

**Comment by GianniCarlo** [comment]
Thanks :D, regarding the issue, yes I think that would be best, there's still not one that refers to either data storage management, or a solution for those that were affected by this bug. Good idea about the ability to export files from there too 🤔

**Comment by kirtangor** [comment]
Thanks again for your quick response. I will file a new bug as soon as I get free. I have currently connected my iPhone with the Mac and am exporting the whole Processed folder of the app to my Mac's disk. I have my fingers crossed and am hoping that the files are still there.
