### ISSUE TITLE
Bug: Random playlists vanish after dragging and sorting a file within a different playlist

### ISSUE THREAD

**Issue by kirtangor** [TortugaPower/BookPlayer#610]
## Environment

 - OS Version: 14.4
 - Phone: iPhone XS
 - Version/Release: 4.0.0-7

## Description

Due to the reordering bug introduced in release 4.0.0-7, dragging a file in one playlist to the top of the playlist and ordering it caused a few (random?) playlist folders to disappear. Luckily the folders are still intact on the disk, however their association is somehow lost.

**IMP NOTE**: Do not panic! If you encounter this issue, you can recover your files using softwares like iMazing or Finder (if using a Mac)

## Steps to reproduce the behavior
1. Create three playlists __Suspense, __Horror, __Fiction
2. Add a few files to each playlist
3. Drag a file from the bottom of the __Horror playlist to the top of the list
4. When you are at the top, drag the file over the title of the playlist
5. Close the app
6. Open the app again, the __Suspense and __Horror playlist have vanished

Reference #609 (closed bug)

**Comment by GianniCarlo** [comment]
This was fixed between 4.1.0 and 4.2.0 I believe, thanks for reporting it 👌
