### ISSUE TITLE
Bug: Language error

### ISSUE THREAD

**Issue by rastaman111** [TortugaPower/BookPlayer#628]
In the Russian version of the language, part of the new menu is described in English, perhaps it was so conceived :)

![image](https://user-images.githubusercontent.com/15727518/132394386-cf595182-152d-4cb5-ac49-d5f49172dfca.jpeg)
![image](https://user-images.githubusercontent.com/15727518/132394402-5ecfad13-dbb9-4bac-8a81-efeb6d21977c.jpeg)

**Comment by GianniCarlo** [comment]
Ah yes, there's a lot of new text that needs localization in the platform we use [Lokalise](https://lokalise.com), I have yet to reach out to the original contributors so translations can be updated. Besides bookmarks, there's still one more screen we're planning on adding, and we haven't set the text for English yet. But yes, this needs to be addressed as well

**Comment by GianniCarlo** [comment]
This should already be solved, feel free to comment if it persists
