### ISSUE TITLE
Bug: app crashes as soon as it opens after update

### ISSUE THREAD

**Issue by AddaxSoft** [TortugaPower/BookPlayer#634]
## Environment

 - OS Version: iOS 14.5.1
 - App Version: latest (22/September/2021)

## Description

 the app craahes as soon as it is open

## Steps to reproduce the behavior
1. Open app

Logs:

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000100b2dc14
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [33257]
Triggered by Thread:  0

**Comment by Chrischmi** [comment]
Same here in 4.2.0 final and beta.

https://user-images.githubusercontent.com/6383221/139559179-6cc8db40-526f-40d8-8954-ee6c77649cb6.MOV

I shared crash data within beta.

**Comment by bornio** [comment]
Same. Happened after trying to import mp3, using “open with”.

**Comment by GianniCarlo** [comment]
I'm looking into this, it looks like sometimes the NSFetchRequests even though the query offset is specified, it may end up fetching already loaded books. I'm patching that, also just in case, we made the file relative path as the is for the uitableviewdiffabledatasource

**Comment by GianniCarlo** [comment]
I'm closing this issue in favor of #665 , also the update has just been released by Apple, please follow up on #665 if the issue persists cc @bornio @Chrischmi
