### ISSUE TITLE
Storage management issue, spinning FILES icon

### ISSUE THREAD

**Issue by paulhargreaves** [TortugaPower/BookPlayer#637]
iOS 15.0 BookPlayer 4.1.1-1

I've airdropped twice and both times the book doesn't appear.

The files appear to have transferred, per the storage consumed from the iOS side

![ios storage](https://user-images.githubusercontent.com/1288695/134765964-18007715-1805-4e79-be6d-ca403aadbff8.png)

but inside bookplayer it shows no files, even after 14 hours or so, and icon below FILES just spins.
 
![in app spinning](https://user-images.githubusercontent.com/1288695/134765960-dd78fd5d-28fc-4e4d-a3e7-68ec8e10b115.png)

This may be related to https://github.com/TortugaPower/BookPlayer/issues/625 ?

**Comment by paulhargreaves** [comment]
I've deleted the app and reinstalled, re-sent my files across.

**Comment by GianniCarlo** [comment]
yes it's definitely related, it looks like the files aren't being picked up from the Inbox folder after airdrop finishes. We'll add something to routinely clean up that folder, either by prompting the import process or by just deleting them based on date added 🤔. The storage management only takes into account the Processed folder, which was a black hole after the book was imported. The Inbox folder can be safely deleted from iTunes file sharing (or from the Finder on Macs) without affecting the app
