### ISSUE TITLE
Import to Existing Playlist

### ISSUE THREAD

**Issue by mttjj** [TortugaPower/BookPlayer#638]
# 🗣 Context

I may be missing something but when I import a bunch of files from iTunes (Finder) I only have the option of importing them to the library or into a new playlist. I would like to be able to pick an existing playlist to which to import the files. I have 800+ files that I want to add but I want to do it in chunks of 50 or so just to make sure everything doesn't crash and burn. But after the first set, I cannot add the additional sets of 50 to the existing playlist. I have to add them to my library and then Edit > select them one-by-one > _then_ move them to the existing playlist. 

# 💬 Narrative

As a … user
I want … to be able to import to an existing playlist
So that … I can save time and user steps

# 📝 Notes

_Provide additional notes…_ see above

# 🎨 Design

_Provide design example, screenshot, text input/output etc_ I think it's self-explanatory

# ✅ Acceptance Criteria

**GIVEN** … 
**WHEN** … I drag files in iTunes (Finder) to import into BookPlayer
**THEN** … I am given the option to import to an existing playlist in addition to the current options of importing into the Library or a New Playlist

# 🚫 Out of Scope

_Describe what is out of scope_

**Comment by GianniCarlo** [comment]
Hi @mttjj , you're right, I don't know how we missed adding that option. We have included that change in our upcoming release 4.2.0 (see commit https://github.com/TortugaPower/BookPlayer/pull/645/commits/945f4fbd13dfdf6b94b03f7eed4b394305f7fc5f) I'll update the beta later today

**Comment by mttjj** [comment]
Since I posted this a few weeks ago I found a workaround that saved me some time. I just needed to have the particular playlist open while importing to be prompted to import to the _current playlist_. But this new functionality will still be a very welcome addition and makes sense functionally.

Thanks so much @GianniCarlo!

**Comment by GianniCarlo** [comment]
that's great! 😁 , I've updated the beta with the changes, I'm closing this issue, but feel free to continue discussing here if you find anything wrong
