### ISSUE TITLE
Add file action sheet: Add option to Import from URL

### ISSUE THREAD

**Issue by Resonanz** [TortugaPower/BookPlayer#646]
> # 🗣 Context
> 
> Import from URL would be a nice feature.

**Edit by @pichfl**

We currently have a menu that allows you to add files or create playlists and contains a message informing users about AirPlay. 

We could add a new menu option "Import from URL" which opens an alert with an input field for a URL (and potentially basic validation insuring only URLS are put into the field) which then triggers the same interaction we have when the `bookplayer://download?url=` scheme is triggered.

**Comment by taxilian** [comment]
That would be fantastic -- as a new user this is the thing I'm struggling with the most, how to get books efficiently from my web-based calibre system ([calibre-web](https://github.com/janeczku/calibre-web) project which supports m4b files) into bookplayer; I am going to try to figure out how to add the bookplayer urls to the project somehow but in the mean time I was hoping to at least have some way that I could -- in the app -- say "download url" and paste the link in. I know that might not be intuitive for some, but it would make things possible which aren't currently as far as I can tell.

I wish I was familiar enough with Swift to help with this myself -- I could test and refine, but I am not sufficiently familiar with things to help much short term

**Comment by GianniCarlo** [comment]
this will be included in the next release! (thanks @jeepston !)
