### ISSUE TITLE
Bug: Old widgets don't change their background to match system theme

### ISSUE THREAD

**Issue by rakleed** [TortugaPower/BookPlayer#650]
## Environment

 - OS Version: 15.0.2
 - App Version: 4.1.1-1

## Description

Old widgets do not change their background to match the system theme. If I choose a dark system theme, the widget stays with a light background. Also, when choosing a light system theme, different parts of the widget have a slightly different background color.

## Steps to reproduce the behavior
1. Open the screen with widgets.
2. Add the old widget.

<details>
<summary>Screenshots</summary>

![image1](https://user-images.githubusercontent.com/19418601/137505844-ba10dc41-5d52-4cff-ab95-843fc7e0b3dd.jpg)

![image2](https://user-images.githubusercontent.com/19418601/137505863-d46d3d84-5bd6-46f1-bf65-a7739737955e.jpg)

</details>

**Comment by GianniCarlo** [comment]
@rakleed we have dropped support for the Today's extension widget, due to Apple shifting to the new type of widgets in iOS 14
