### ISSUE TITLE
Bug: Aspect ratio of covers is wrong

### ISSUE THREAD

**Issue by fuddl** [TortugaPower/BookPlayer#658]
## Environment

 - OS Version: 15.0.2
 - App Version: 4.2.0-11

## Description

Covers have a forced square aspect ratio and thus, look distorted when representing the cover of a printed book:

The issue occurred with the last update. 

![Distorted book cover](https://user-images.githubusercontent.com/842548/139593254-c7f7a9ce-2c6a-4e27-b555-edee54df49cf.jpg)

## Steps to reproduce the behavior

1. Create a playlist
2. Add audio files with a non square cover to it
3. play the playlist

**Comment by GianniCarlo** [comment]
thanks @fuddl for creating the ticket, this has been solved in #661 and will be released in the next version

**Comment by fuddl** [comment]
👌
