### ISSUE TITLE
Share audiobooks

### ISSUE THREAD

**Issue by pichfl** [TortugaPower/BookPlayer#66]
The swipe left menu for a cell that contains a book or playlist item should include an additional action called "Share" which should bring up the share sheet for the associated file. 

Original text:

> Since BookPlayer accepts audiobooks via AirDrop or generic file sharing, it should also allow you to share a book in a similar fashion.
> 
> This should not be too hard to implement, but it stops files from being stuck inside the player and makes it easier to bring files from one device to the next, which will also be nice for possible future developments.

**Comment by GianniCarlo** [comment]
Awesome idea!

**Comment by GianniCarlo** [comment]
mmmmm looking into this one, we should have preserved in some way the original filename in 3.0.0 for this feature 🤔

**Comment by GianniCarlo** [comment]
it won't be a problem if we're sharing between BookPlayer apps in different devices. But if the intention is just the extraction of the book, then before sharing the book, the hash filename should be changed to the next best thing we have, which would be the title

**Comment by pichfl** [comment]
We could always generate a sensible new file name given we store all the meta info.
```swift
\(author) - \(album) - \(title) (\(year)).\(ext)
```

**Comment by GianniCarlo** [comment]
resolved by #251
