### ISSUE TITLE
Bug: "Select all" not working as it should

### ISSUE THREAD

**Issue by skracke** [TortugaPower/BookPlayer#663]
## Environment

 - OS Version: 14.7.1
 - App Version: 4.2.0-11

## Description

When you select "Edit" and then "Select All" to create a playlist with all selected files, only about half of the files will be included in the playlist.
Another strange phenomenon that I noticed is that if you scroll through the selected files after selecting "Select all", all selection marks disappear when you get a bit down in the list.

**Comment by GianniCarlo** [comment]
I think this is due to items being loaded in pages, so select all is only picking up the loaded items. Thanks for creating the ticket

**Comment by GianniCarlo** [comment]
Oh and the deselect looks to be due to the list reloading after the next page is loaded

**Comment by GianniCarlo** [comment]
This will be included in the next release 4.2.2
