### ISSUE TITLE
v4.2.0 Crashes On Launch

### ISSUE THREAD

**Issue by Yonidass** [TortugaPower/BookPlayer#665]
## Environment

 - OS Version: 15.1
 - App Version: 4.2.0

## Description

After upgrading to the latest version, the app worked a few times normally but now crashes every time I try to launch it. Did nothing since the upgrade except listen a few times, and added 1 bookmark to a file.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by gyre** [comment]
Not that this is any further help, but I'm having the same issue. iPhone 11pro. iOS 15.1. Latest book reader.

**Comment by Yonidass** [comment]
Thanks. Maybe you can add this comment to the bug thread…?

**Comment by GianniCarlo** [comment]
based on the crashlogs, this may be due to the UITableViewDiffableDataSource, we have reverted that in this PR #660. I'm leaving this issue open to follow up once v4.2.1 is out

**Comment by Yonidass** [comment]
Not sure if you’ve submitted your own report, but I just got this:

Hi Matthew!

Thanks for reaching out, we have received other reports as well, and based on crashlogs we believe it’s related to this issue https://github.com/TortugaPower/BookPlayer/pull/660

We have submitted a new version to Apple so it can be reviewed and released as soon as it’s approved. We also include a fix for autoplay which is broken in 4.2.0

Best,
Gianni

**Comment by Yonidass** [comment]
Oops. Last reply was a mistake.

**Comment by GianniCarlo** [comment]
yup, I'm going through email support too, and linking to the github issues when possible

**Comment by turingsecurity** [comment]
> yup, I'm going through email support too, and linking to the github issues when possible

How long will it take Apple to push the update? It’s been nearly 4 days now without autoplay and an essentially dead app.

**Comment by gyre** [comment]
I deleted my identical bug report as it added no extra value to the dev.  :)

**Comment by GianniCarlo** [comment]
@turingsecurity It usually takes between 2-3 days upon submission, it was submitted yesterday around 7am (UTC-5)

**Comment by GianniCarlo** [comment]
Apple has released v4.2.1, please let me know if the crash is still happening after updating, cc @Yonidass @turingsecurity @gyre

**Comment by gyre** [comment]
Bookplayer still crashes on launch for me for 4.2.1.

iOs 15.1.  iPhone 11pro.

If you need crashdump let me know how I can get it to you. :)

**Comment by Yonidass** [comment]
Still crashes for me too.

**Comment by GianniCarlo** [comment]
damn, @gyre can you install the previous version beta via testflight? and submit the crash report via there? → link to join: https://testflight.apple.com/join/FLv3zLyN

**Comment by GianniCarlo** [comment]
oh I see @Chrischmi has already done so, thanks a lot!, the error looks related to the Theme that it's used to load the initial state of the app, it seems to be nil, I'll add a default value for that

<img width="991" alt="Screen Shot 2021-11-02 at 12 33 53" src="https://user-images.githubusercontent.com/14112819/139916456-ff6fc2c8-0e32-497e-ba10-b1a7ab20e8f1.png">

**Comment by gyre** [comment]
Heh.  I did install 4.2.0 via TF and it crashed.  Hopefully you got the crash report as well :)

**Comment by GianniCarlo** [comment]
well we can be sure now that this is what's happening, got the crash report and it's the same issue 😬 

<img width="912" alt="Screen Shot 2021-11-02 at 12 51 49" src="https://user-images.githubusercontent.com/14112819/139919254-dd8606e4-9a71-4bd7-bbf4-f4fa1e9fe623.png">

Thanks for installing @gyre 😁 , the good thing, is that I already had a solution in place for this, that I implemented for the widgets extension, I forgot to put it in the main app. I'll submit an open beta shortly with that fix, I want to include other things in the next version as well

**Comment by GianniCarlo** [comment]
PR: https://github.com/TortugaPower/BookPlayer/pull/666

**Comment by GianniCarlo** [comment]
Build submitted to TestFlight, it takes around the same time usually as submitting to the app store for the beta to go live

<img width="463" alt="Screen Shot 2021-11-02 at 13 17 40" src="https://user-images.githubusercontent.com/14112819/139922509-1136918f-176e-4b92-ad83-e1f8908b2288.png">

I'll post here once it's approved and live, link to join: https://testflight.apple.com/join/FLv3zLyN

**Comment by lexxanite** [comment]
Can confirm this is still present in 4.2.1

**Comment by gyre** [comment]
4.2.2(1) just arrived.  and crashed.  stacktrace (hopefully) submitted via TF

**Comment by GianniCarlo** [comment]
Thanks for your prompt reply @gyre , can you update to the build 3 and test? I just updated the beta again

**Comment by gyre** [comment]
4.2.2(3) starts and plays.  at least the first few secs i tested.  :)

**Comment by GianniCarlo** [comment]
nice!

**Comment by gyre** [comment]
now i can go and continue the washing up with my earbuds in.  thanks for fixing this :) :)

**Comment by GianniCarlo** [comment]
Thanks everyone for your help in solving this issue 🙌
