### ISSUE TITLE
Chapter selection is white in dark mode

### ISSUE THREAD

**Issue by patjolata** [TortugaPower/BookPlayer#667]
After the update to the v. 4.2.1 the selection has a white background in dark mode (please take a look at the screenshot). Until yesterday it was black or dark in dark mode. Please tell me, if you need any more information. Thanks! 

![3B459D00-343B-4E79-AF35-BD0CAF668D7C](https://user-images.githubusercontent.com/53347808/139953860-8a0a8a82-065d-4ef8-9218-1735bb93c3c8.png)

**Comment by patjolata** [comment]
I think I understand the problem now. I have the dark mode for iOS disabled, i.e. I'm always in light mode. But because I use the BookPlayer mostly during bedtime, I've got he toggle 'Always use dark mode' in the app enabled (screenshot 1).

![IMG_8212](https://user-images.githubusercontent.com/53347808/142066642-e0c4e0dd-6f89-480d-bea8-96487104b1ef.PNG)

When I go to the chapters of an audio book, I have the light background (which should be dark by the settings of the app and used to be dark before 4.2 update) (screenshot 2).

![IMG_8213](https://user-images.githubusercontent.com/53347808/142066884-6c9a838e-e2d6-4e3d-8098-a81fcb296750.PNG)

When I turn on the dark mode the chapter register is dark as it should be - even if it used to have white letters on the black background (as chosen in the app settings)(screenshot 3).

![IMG_8214](https://user-images.githubusercontent.com/53347808/142067123-f2911ad7-fea2-4304-93cb-9b66c90cd96f.PNG)

Could you please fix this behaviour of the app because I get blinded each night. ;) 

I'm using the BookPlayer in v. 4.2.2-3 and iOS 15.1 on an iPhone 12.

**Comment by GianniCarlo** [comment]
Thanks for extra details 👌, we'll work on a fix for this

**Comment by GianniCarlo** [comment]
This is fixed in https://github.com/TortugaPower/BookPlayer/pull/692 and will be included in the next version
