### ISSUE TITLE
Bug: Imported playlist files appear at top of list instead of bottom

### ISSUE THREAD

**Issue by malloy70** [TortugaPower/BookPlayer#670]
## Environment

 - OS Version: 15.0.2
 - App Version: 4.2.1-1

## Description

Before two updates ago, when adding a file to a playlist, the file appeared at the end/bottom of the list. Now it appears at the beginning/top and must must be dragged to the bottom, if desired. Perhaps an option could be made available to set a default?

## Steps to reproduce the behavior
1. At the bottom of the list of files in a playlist, tap "+ Add".
2. Tap "Import files".
3. Tap a file to import.
4. File appears in the playlist at the beginning/top of the list.

**Comment by GianniCarlo** [comment]
I reverted the changes in this PR → https://github.com/TortugaPower/BookPlayer/pull/675

**Comment by GianniCarlo** [comment]
This will be included in the next release 4.2.2
