### ISSUE TITLE
Bug: Filename appears in main player vs. Title tag

### ISSUE THREAD

**Issue by malloy70** [TortugaPower/BookPlayer#671]
## Environment

 - OS Version: 15.0.2
 - App Version: 4.2.1-1

## Description

Before two updates ago, the main player screen displayed the currenlty playing file's "Title" metadata tag. Now it displays the filename (e.g. "myfilename20211103.mp3" vs. "My File Title, 11-03-2021"). However, the Title tag is displayed in other areas, such as a playlist and the player widget. Preferably, the Title tag could be displayed (or an option could be added).

## Steps to reproduce the behavior
1. Tap a file to play from a playlist.
2. Filename appears below artwork instead of title tag.

**Comment by LordZork** [comment]
@malloy70 I noticed this too, I think after the **4.2.0** update.  I didn't think about it being a bug, though—good call!

**4.2.1** crashes on launch for me, every time, so I'm not sure if the file name issue is still present... at least for me.

**Comment by GianniCarlo** [comment]
I had to double check, but you're right, for some reason we thought that all parts of an mp3 book would have the same encoded title, but they do have the part number encoded in there too. Thanks for creating a ticket for this, I'll create a PR addressing this

**Comment by GianniCarlo** [comment]
This will be included in the next release 4.2.2

**Comment by malloy70** [comment]
Awesome! Thanks for this and for #670. It's really cool to have devs that care and are reponsive. Great community. I had to tip!

**Comment by GianniCarlo** [comment]
Thanks for your support @malloy70!! :D
