### ISSUE TITLE
Bug: v4.2.1 Crashes On Launch

### ISSUE THREAD

**Issue by LordZork** [TortugaPower/BookPlayer#672]
## Environment

 - iOS Version: 15.1
 - App Version: 4.2.1

## Description

The BookPlayer app updated either last night or this morning, and now crashes immediately on launch (every time).  I've rebooted my iPhone and I've tried opening the app a dozen or more times, to no avail.

Note:  I updated to iOS 15.1 yesterday, though I don't recall if I used BookPlayer between that update and the app update.  I only know that I am unable to use or even open the app as of **4.2.1**.  I had no issues with **4.2.0**.

## Steps to reproduce the behavior
1. Tap on (open) BookPlayer app.

**Comment by LordZork** [comment]
@GianniCarlo, I would be happy to join/test the beta, but I'm nervous I might lose app date (loaded books, playlists, listen location, etc.).  I am guessing you cannot guarantee this won't happen, but can you at least tell me if it is likely or not?  Thanks!

**Comment by GianniCarlo** [comment]
it should not happen if you're on v4.2.1, the only case where that may happen is when there's a database migration, and the beta has stuff that the appstore version doesn't have, in that case you cannot revert to the app store version.

But that's not the case here, you can switch between the appstore version and the latest beta without any problems

**Comment by LordZork** [comment]
@GianniCarlo, I just installed the beta....

I opened and closed the app several times—no crashes this time! :)

Also, I see you fixed #671 as well.  Thanks!

**Comment by GianniCarlo** [comment]
awesome 🙌

**Comment by Mr-Mistoffelees** [comment]
Thanks so much for your dedicated work here. A lot of people in my bubble are really happy to have one of their favorite apps back!
