### ISSUE TITLE
Bug: Autoplay is not working

### ISSUE THREAD

**Issue by jvaclavik** [TortugaPower/BookPlayer#679]
## Environment

 - OS Version: 15.0.2
 - App Version: 4.2.0.11

## Description

In previous versions autoplay worked out of the box but in this one playing is stopped every time when I finish one file from the whole playlist. It's quite disruptive and it's hard go to next chapter during driving for example. In settings I have autoplay library turned to on.

## Steps to reproduce the behavior

It works like that without any specific requirements. Just add files, create playlist and play. After finishing the file playing is stopped.

**Comment by pichfl** [comment]
Please update to the latest release, which is 4.2.2-3

**Comment by jvaclavik** [comment]
Nice, it's working now. Thank you! Awesome app by the way 🙂
