### ISSUE TITLE
Apple Watch “Now Playing” controls—“Chapter” instead of “Rewind”

### ISSUE THREAD

**Issue by LordZork** [TortugaPower/BookPlayer#680]
## Environment

 - iOS Version: 15.1
 - watchOS Version: 4.3.2
 - App Version: 4.2.2

## Description

On the Apple Watch, the "Now Playing" controls should reflect the iPhone app controls.  However...

**BookPlayer**

iPhone (app):
"Rewind" and "Forward"

Apple Watch (Now Playing):
"Chapters" and "Forward"

![image](https://user-images.githubusercontent.com/65878888/140621259-9628d61b-a64e-41bd-91de-054fc95908d7.png)

The controls were correct previously, though I can't say exactly when.  I only know I first noticed they were different with BookPlayer 4.2.0.

That said, the "Now Playing" controls are correct with other apps, such as Audible...

**Audible**

![image](https://user-images.githubusercontent.com/65878888/140621698-e9e0d95a-c939-4435-99be-a163ef153388.png)

**Comment by LordZork** [comment]
I just remembered, the 4.2.0 update included "redesigned player... controls."  This change must have impacted how the Apple Watch "Now Playing" works... either accidentally (a bug?) or intentionally?

**Comment by GianniCarlo** [comment]
@LordZork can you tap on the hamburger icon and post a screenshot of the options there? before I tested on adding bookmarks support from the lock screen on the iphone, but it generated the same problem of replacing the rewind icon in favor of a hamburguer icon on the iphone. I left the code in as a reference for the future, but disabled the button

It no longer shows in the iphone, so I'm curious if that may be affecting the watch? on my watch I'm still able to see the rewind icon though

**Comment by LordZork** [comment]
Sorry for the delay!  Here are some screenshots...

iPhone — hamburger icon NOT tapped:

![image](https://user-images.githubusercontent.com/65878888/141603642-c1159548-746c-4f50-992e-7dcdb0d00863.png)

iPhone — hamburger icon TAPPED:

![image](https://user-images.githubusercontent.com/65878888/141603655-3c250eaa-cca1-49f8-a08e-aa20db54531d.png)

Apple Watch — hamburger icon NOT tapped:

![image](https://user-images.githubusercontent.com/65878888/141603669-7533f004-47ad-4e9f-96db-cd7abcc603d9.png)

As you can see, the hamburger icon is grayed out (tapping does nothing).  The icon is there, but it doesn't function.

**Comment by LordZork** [comment]
@GianniCarlo do those images help—need anything else?

**Comment by GianniCarlo** [comment]
I've been trying to reproduce but with no result @LordZork , can you tap on the '...' button and see what's in there? For context, this is what I see on WatchOS 8.1:

![incoming-FD605ECF-8024-4B90-A62D-E187B143B70C](https://user-images.githubusercontent.com/14112819/141832171-521365a6-5c27-4002-8cbe-1dccd2624459.PNG)

**Comment by LordZork** [comment]
@GianniCarlo, I have the original Apple Watch (still works great), which is why I'm running an older version of watchOS (it's the latest available). Though, as previously mentioned, the correct controls display for other apps, such as Audible.

I appreciate you looking into this! Here's some screenshots...

iPhone — "..." icon NOT tapped:

![image](https://user-images.githubusercontent.com/65878888/141880290-07351579-12d7-4dd3-8de6-1710f09750f8.png)

iPhone — "..." icon TAPPED:

![image](https://user-images.githubusercontent.com/65878888/141880325-abbc22fc-5612-4496-aa2d-dca9be40cc2e.png)

Apple Watch — "..." icon NOT tapped:

![image](https://user-images.githubusercontent.com/65878888/141880415-9f2d8ab6-0558-4e0c-8dd0-dd1c91a16a84.png)

Apple Watch — "..." icon TAPPED:

![image](https://user-images.githubusercontent.com/65878888/141880427-a82fc1b0-35ad-4838-92c4-ed9ade2934fc.png)

**Comment by LordZork** [comment]
@GianniCarlo, btw... off topic... I couldn't help noticing the book on your screenshot.  How do you like the Hyperion series?  I've never heard of it, but I'm a big fan of Sci-Fi and Fantasy—always looking for new books.  I'm currently listening to Dune and the Stormlight Archive (both are solid so far).  Before that, I listened to the Red Rising series, which I really liked.

**Comment by GianniCarlo** [comment]
I'll download the simulator version for watchOS 4.3.2 and test with that 👍 

Re off topic, I love the Stormlight Archive! and for that matter I think I've gone through almost everything that Brandon Sanderson has put out on audiobooks. Haven't read Red Rising, I'll check those next, my current backlog is running thin (after Hyperion I wasn't sure which series to pick up)

> How do you like the Hyperion series?

To be honest, I had trouble getting into the first book, I had to force myself to stick to it until (no spoilers) the people gathered start a journey and then each tell why they are there (which to be fair, is not that long into the book, but still). Once those mini stories started, I no longer had to force myself, but they weren't as interesting to me as to go eagerly back to the book whenever I had the time. With all the context of the first book, I can say that I'm enjoying more the second book, and now that I've made it this far, I'll definitely go through to the last book

**Comment by LordZork** [comment]
@GianniCarlo any luck with the issue, or with testing the simulator version for watchOS 4.3.2?

**Comment by LordZork** [comment]
@GianniCarlo 

Just a quick update...

I've been installing and testing beta versions of BookPlayer, as they're released, and I've even completely reset and re-setup my Apple Watch, but the wrong icon/control function is still showing instead of rewind.  

As mentioned before, the correct function is present with other apps, such as audible.

Hopefully you're able to resolve this! BookPlayer is one of my all-time favorite apps, and I'm really missing the rewind function!

**Comment by GianniCarlo** [comment]
Hi @LordZork sorry I forgot to post an update, in the last Xcode there's no way to install the simulator for watchOS 4.3.2. I downloaded Xcode 9.4.1, but I haven't had time yet to tinker with how to pass the watch SDK from the older Xcode to the new one. Now that v4.4.0 is out in the AppStore I'll look at this again 👍

**Comment by GianniCarlo** [comment]
Super late follow up @LordZork , I did try to install the old simulator by importing the old Xcode files, but sadly it didn't work :/. We launched a beta with the watch app rewrite in SwiftUI, but we had to up the deployment target to watchOS 7 (link to join beta: https://testflight.apple.com/join/FLv3zLyN)

I found the screenshot with the problem I had when trying to create the old simulator. Instead of showing the watchOS list to be selected, it showed an iOS list when creating a Watch simulator

<img width="866" alt="Screen Shot 2021-12-28 at 17 17 45" src="https://user-images.githubusercontent.com/14112819/159351278-451eb008-1cb7-4bb9-a675-6bb00b53d829.png">

**Comment by LordZork** [comment]
Hi @GianniCarlo, thank you for the follow up—I really appreciate it!

I just downloaded and tested the latest beta: v4.5.0 (2)

Sadly, I am still experiencing the same issue...

Instead of the rewind icon, I get the hamburger icon (which is still grayed out, and tapping does nothing).

Being that I am unable to test or even use the actual **BookPlayer** *Watch* app (due to an older Watch and watchOS), I have only ever used the Watch's built-in **Now Playing** feature.  And, as mentioned before, **BookPlayer** is the only app I've experienced the aforementioned issue with... which wasn't an issue prior to **BookPlayer** v4.2.0.
 
I am not sure if there is anything that can be done, but it sounds like it probably isn't fixable at this point, which is definitely a bummer.  **BookPlayer** is my favorite audiobook app—I've used it a lot, and I've donated (it's worth it).

That said, if this isn't fixable, there is another/similar app in the App Store I may try... at least until I finally decide to get a new Apple Watch (my current Watch still works great, so I haven't needed or even wanted to upgrade).

Again, I appreciate all your time and effort on this.  It's a fantastic app!!

Thanks!

**Comment by GianniCarlo** [comment]
Thanks for your support :D. Btw I just realized that I never deleted the disabled bookmarks thing for the lock screen (which affects the apple watch now playing screen too), I added it in the latest version of the beta (alongside a fix for the speed rate label being truncated in the phone). Can you install and see if by any chance that fixes it?

**Comment by LordZork** [comment]
@GianniCarlo, I just tested **v4.5.0 (3)**.  It's fixed!!!

Thank you so much!!

**Comment by GianniCarlo** [comment]
awesome! finally closing this issue then
