### ISSUE TITLE
Adjust time remaining based on playback speed

### ISSUE THREAD

**Issue by Matthewb143** [TortugaPower/BookPlayer#685]
## Feature request

- Have the remaining duration of what you are listening to be based on your current playback speed, ie if a book is 10 hours left at 1x speed when you change the speed it will update the remaining time so 2x speed would so 5 hours remaining and so on.

## Narrative

- Helps you know how much time you actually have left when listening to something, and also allows you to pick playback speed based on how much time you have to listen.

**WHEN:**
- User changes playback speed
**THEN:** 
- Remaining duration is recalculated to reflect this change

**Comment by GianniCarlo** [comment]
This will be included in the next release 👌
