### ISSUE TITLE
Bug: ...import files from cloud storage hangs

### ISSUE THREAD

**Issue by elric667** [TortugaPower/BookPlayer#697]
## Environment

 - OS Version: 15.1
 - App Version: 4.3

## Description

Import files from cloud folder downloads the files and hangs when starting to import.  This has worked until the latest update

## Steps to reproduce the behavior
1. Import file
2. Select cloud storage I use pCloud
3. Find the audiobook
4. Select the audiobook and download
5. It downloads the file and shows fully downloaded but never imports

**Comment by GianniCarlo** [comment]
Hi @elric667 , can you attach a screen recording of the process? does the file app gets dismissed?

**Comment by elric667** [comment]
https://youtube.com/shorts/1_m06_6OzDU?feature=share

**Comment by elric667** [comment]
I had it running for six hours stuck at that spot.

**Comment by GianniCarlo** [comment]
@elric667 I cannot access the video, I tried from Chrome, Safari and Opera with the same blank page as result, see screenshot

<img width="1263" alt="Screen Shot 2021-11-24 at 09 36 26" src="https://user-images.githubusercontent.com/14112819/143258385-7676592c-9bc7-45a2-a73a-022e2ed9a5ad.png">

**Comment by GianniCarlo** [comment]
from the Youtube app it worked. I see that you're stuck in the Files app, and BookPlayer doesn't really get any event from the Files app until all the files are downloaded. That's how the API works, what I could suggest is that you go the other way around, from the Files app, select them, and use the share icon, from the share sheet, select BookPlayer as the destination
