### ISSUE TITLE
Bug: Crashes on startup.

### ISSUE THREAD

**Issue by lexxanite** [TortugaPower/BookPlayer#708]
## Environment

 - OS Version: 15.1.1 iPhone 12 Pro
 - App Version: 4.4.0 (3) TestFlight

## Steps to reproduce the behavior
1. Open Bookplayer

**Comment by lexxanite** [comment]
https://user-images.githubusercontent.com/73835921/145342084-b1697866-8c18-44ca-a964-1210606fe17b.MOV

**Comment by lexxanite** [comment]
Dropping out of TestFlight and reverting to 4.3.0 - 1 from the App Store restores the app functionality.

**Comment by GianniCarlo** [comment]
Thanks @lexxanite for reporting it, I'll disable the beta until I get this solved

**Comment by GianniCarlo** [comment]
@lexxanite I added a new version to the beta, 4.4.0 (4), it should fix this problem. Please let us know if this is the case

**Comment by lexxanite** [comment]
https://user-images.githubusercontent.com/73835921/145458914-128f9898-5250-4a46-859a-f9262ba0c65c.MOV

**Comment by lexxanite** [comment]
It worked until I said start testing on the feedback explanation screen of flight test. Then it promptly crashed and does that since.

**Comment by GianniCarlo** [comment]
it seems I inadvertently introduced that crash in #709, it's trying to create the Inbox folder if it's missing, but since it's a folder created by the system, it crashes when trying to create it manually.  Thanks @lexxanite for helping debug the beta. I'll write again here as soon as the next build is up in TestFlight

**Comment by GianniCarlo** [comment]
@lexxanite 4.4.0 (5) is up with the fix for the crash about the Inbox folder, please when you have the time, let me know if it fixes your crash

**Comment by lexxanite** [comment]
TestFlight version now opens as expected.

**Comment by GianniCarlo** [comment]
Thanks again @lexxanite for your help!
