### ISSUE TITLE
Bug: ...Apple watch app doesn't work at all.

### ISSUE THREAD

**Issue by movieman12341** [TortugaPower/BookPlayer#711]
## Environment

 - OS Version: [15.1]
 - App Version: [4.3.0-1]

## Description

The apple watch app doesn't seem to sync to the phone rendering the apple watch app completely useless as I can't select books or start playback from the watch. If I start playback from the phone, I can pause or skip forward/backwards so at least that works. However, I should be able to start playback from the watch by clicking on apple watch app and clicking on "Last Played" book and it start playback. In my case, when I click on the book I want to play, it just goes to the now playing screen. If I click the play button my music starts playing instead of the book. 

Anyone have any suggestions? I've tried deleting Bookplayer from phone and watch and reinstalled, restarted phone and watch, cleared cache, and nothing is working. Thank you.

**Comment by GianniCarlo** [comment]
Can you test with the beta of the upcoming version? (Link to join https://testflight.apple.com/join/FLv3zLyN)

**Comment by GianniCarlo** [comment]
It seems the beta has the same issue, thanks for reporting it @movieman12341 I'll look into it

**Comment by GianniCarlo** [comment]
This has been fixed in the latest beta v4.4.0 (6) and will be included in the next App Store release

**Comment by movieman12341** [comment]
@GianniCarlo Sorry for late reply as I just saw this. Good news! Thanks for getting this fixed.
