### ISSUE TITLE
Total time remaining, combined from all chapters

### ISSUE THREAD

**Issue by r0bj** [TortugaPower/BookPlayer#714]
## Feature request

Time remaining for current chapter is ok but it would be really useful to be able to see also total time remaining, combined from all chapters.

**Comment by pichfl** [comment]
If your book is a chapterized m4b, you can tap the label in the middle below the playback position slider to switch between the total time of the book and the currently playing chapter.

If you have a book that is an mp3 file per chapter you'll have to wait for the 4.4.0 release to be published, which includes a feature to bind those files into a single volume which will behave like a proper m4b audiobook.

I'm closing this as #706 is scheduled for release once the beta phase is over.
