### ISSUE TITLE
support "Clear Playback history"

### ISSUE THREAD

**Issue by binglin1009** [TortugaPower/BookPlayer#715]
As the name of title, will you add this feature? Users, for example, like me, want to listen some programs again and again. When I finish all the episodes, I want to replay it again. But for some episodes, there may be still few seconds/minutes left. it will not play from the very beginning.(sorry, I do not know if I am clear about it. I just want to say when a new episode is played, it should begin from the 1st second, not from the middle, etc. )

Best regards.

**Comment by pichfl** [comment]
Swipe left on any item in your library and select "Jump to start"
