### ISSUE TITLE
Bug: Pause playback - end of current chapter not working anymore

### ISSUE THREAD

**Issue by stefandesu** [TortugaPower/BookPlayer#721]
## Environment

 - OS Version: 15.2 (latest)
 - App Version: 4.4.0-8 (latest)

## Description

There was some recent change that seems to have caused the "end of current chapter" option to stop working. I use this option almost every day and it just stopped working a couple of days ago, so I guess it's the latest update. I'm using a folder with a bunch of files and only want to go through one per day. After it didn't work yesterday, I even converted it into a "single volume with chapters" introduced in the update, but the option still does not work.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
Thanks for reporting the issue @stefandesu , we're including a fix for this in the next release

**Comment by GianniCarlo** [comment]
v4.4.1 was just released to the appstore, please let us know @stefandesu when you get to test the new version

**Comment by stefandesu** [comment]
@GianniCarlo Thanks, I actually tried it already! So it does stop after the chapter which is good, but the behavior seems to be different from before. IIRC it left off at 0:00 of the following chapter, so when you went back the next time, it would start there. Now, it stops at the end of the chapter, and if you have Smart Rewind enabled, it will replay the last 30 seconds next time you go in. I'm pretty sure I haven't changed any other settings compared to before the bug was introduced, so I think Smart Rewind was enabled and it still started at the beginning of the following chapter.

To be honest, I don't really need Smart Rewind, so I'll just disable it for now, and I'm not sure which of these behaviors actually makes more sense. It feels a bit weird to replay just the end of the previous chapter.

**Comment by GianniCarlo** [comment]
Hmmmmmmm you're right @stefandesu , the behavior did change, I do think it's better for the timer to make it stay at the end of the chapter, so it's a visual queue for the user to know where it ended when the app is opened again. I think we just need to clear up the smart rewind timestamp, or avoid setting it when playback is paused by the sleep timer 🤔 so on resume, it won't rewind

There's a second release I want to do addressing other issues, so I'll include this change as well

**Comment by GianniCarlo** [comment]
@stefandesu the latest beta addresses this issue, if you'd like to join, here's the link: https://testflight.apple.com/join/FLv3zLyN otherwise we'll submit this version for AppStore review around Jan 6 🙌🏻

**Comment by cantonalex** [comment]
Yes this is super annoying. I love this app but the last few updates are making it unusable.

Even the auto title sort was removed.

**Comment by GianniCarlo** [comment]
Hi @cantonalex , we believe the auto title sort is related to #508 solved by https://github.com/TortugaPower/BookPlayer/pull/728 , if you can, please help us joining the beta (https://testflight.apple.com/join/FLv3zLyN) and testing the fix for this issue with the sleep timer, and the order of files imported, thanks 🙌

**Comment by stefandesu** [comment]
I think my particular issue is fixed with the recent update, so I'm going to close the issue. Thanks a lot!
