### ISSUE TITLE
FAQ update needed

### ISSUE THREAD

**Issue by gmaddry** [TortugaPower/BookPlayer#732]
## Environment
https://github.com/TortugaPower/BookPlayer/wiki/FAQ

## Description
Chapter and Verse no longer works with current Windows (10) and iTunes

## Steps to reproduce the behavior
Trying to install Chapter_and_Verse_V1_5_3_0.exe shows app needs QuickTime which is no longer available.

**Comment by GianniCarlo** [comment]
thanks @gmaddry ! the wiki has been updated
