### ISSUE TITLE
Play/pause starts flashing after a few chapters 

### ISSUE THREAD

**Issue by PeggyD1001** [TortugaPower/BookPlayer#735]
I have to quit the app. This has happened with two different books in the last two days. I have deleted the book and re-transferred it via AirDrop. I am leaving it as individual chapters rather than a volume to see if that works. I have not had a problem with volumes prior to the last two days.

**Comment by GianniCarlo** [comment]
This may have been tied to the playback loop issues we've had before, right now it should only flash once when the chapter changes, which is due to the player loading a new item for playback. Please let us know if this is still an issue
