### ISSUE TITLE
Bug: "Connectivity Error" on Apple Watch

### ISSUE THREAD

**Issue by joshjohanning** [TortugaPower/BookPlayer#737]
## Environment

 - OS Version: 15.2
 - App Version: 4.4.2

## Description

The app loads my on watch but when I raise my wrist I just get "Connectivity Error - there's a problem connecting to your phone, please try again later"

## Steps to reproduce the behavior
1. Play book on phone 
2. Raise watch 
3. See error

**Comment by joshjohanning** [comment]
gif

![Untitled](https://user-images.githubusercontent.com/19912012/148723277-09c45767-6dc9-453f-9db1-133739d42619.gif)

**Comment by FrozenGamerAK** [comment]
I have the exact same problem. frustrating for driving.

**Comment by potseeslc** [comment]
I have the same issue

**Comment by GianniCarlo** [comment]
Hi everybody! I've seen this issue reported via support before, for some reason deleting the app from the apple watch, and then reinstalling the companion app from within the iOS Watch app seems to solve this issue. I haven't looked into the new apis regarding watch connectivity, hopefully they have improved by now, but it is on my todo list to rework the watch app using SwiftUI as well

**Comment by GianniCarlo** [comment]
quick follow up, I've been reworking the entire watch app to use swiftUI, and I'm also reworking the use of the WatchConnectivity framework, and have now understood more about the framework, the next update should be more stable. Hopefully we can put a beta up by next week 👍

**Comment by GianniCarlo** [comment]
The beta is live, I had some complications with SwiftUI, but it's finally done 🎉 (link to join via TestFlight: https://testflight.apple.com/join/FLv3zLyN). The target deployment has been increased to iOS 14, and WatchOS 7 though (this was for ease of use of some things in SwiftUI, besides our plan to next tackle CarPlay with iOS 14 apis)

**Comment by joshjohanning** [comment]
> I've seen this issue reported via support before, for some reason deleting the app from the apple watch, and then reinstalling the companion app from within the iOS Watch app seems to solve this issue.

This worked for me. 

Joining the beta, thanks for your progress @GianniCarlo!
