### ISSUE TITLE
Fade out volume before sleep timer is coming in

### ISSUE THREAD

**Issue by ghost** [TortugaPower/BookPlayer#740]
## Feature request
- Slowly turn the volume of the playback down, seconds before the sleep timer is coming in.

## Narrative
If a sleep timer is set, the playback does not end abruptly after the sleep timer expires, but slowly fades out a few seconds before (e.g. 5-10 seconds).

## Design
No changes in UI design needed. Maybe introduce an optional settings entry to toggle on/off the fade-out.

**Comment by GianniCarlo** [comment]
I forgot to close this, I can't remember when we introduced it, but the behavior right now is that it will fade out when using the sleep timer
