### ISSUE TITLE
center current playback speed in display

### ISSUE THREAD

**Issue by PeggyD1001** [TortugaPower/BookPlayer#742]
## Feature request

In the first version that included the many new speed choices, when the current playback speed was tapped that speed would be centered in the display like in the attached screenshot, making it easier to adjust the speed up or down from the current speed.

## Narrative

Currently, the playback speed display goes to the top of the speed list, starting with the slowest speed. I'd like the behavior to go back to that previous behavior

## Design

![Screenshot 2022-01-24 at 17 34 02](https://user-images.githubusercontent.com/79957921/150894702-4399f895-ed43-485d-ac9e-465fe9e20845.png)

**Comment by GianniCarlo** [comment]
We have changed this for the upcoming release with a new design, now tapping on the speed item will show this

![image](https://user-images.githubusercontent.com/14112819/150896557-3c2b3f9d-16be-4610-8bce-951f847da3dd.png)

**Comment by PeggyD1001** [comment]
Thank you. I really like the idea of being able to set a default speed.

What I liked about the current speed being centered is the easy ability to go up or down from there. Usually, I just want to slow down a bit without having to scroll through the long list of speeds & then go back to my preferred speed.

Peggy DeLise
