### ISSUE TITLE
Bug: app 4.4.4 version crashes immediately after start

### ISSUE THREAD

**Issue by INFINITY-8888** [TortugaPower/BookPlayer#757]
## Environment

 - OS Version: iOS 15.2.1
 - App Version: 4.4.4
 -  Hardware : iPhone XS Max 

## Description

App crashes immediately after started.

**Comment by Geordon** [comment]
I am also having this issue.  iPhone SE (2020) ios 15.2.1, BookPlayer ver 4.4.4.

Process info from Mac Console of Book Player:
https://gist.github.com/Geordon/0659ccc04f442a05b53a9da3dc24ea0e

**Comment by GianniCarlo** [comment]
This is due to the app failing to load the current chapter of the last played book. Every book should have at least one chapter (even if there's no file metadata about it, in that case the chapter will be the entire book). By any chance do you remember what the last played book was? m4b? single mp3? mp3 bound into a volume via the inapp feature? I can patch this, but I'd like to get to the source of the problem which is the chapter not loading in memory

**Comment by Geordon** [comment]
As I recall, mine was a single MP3 file audiobook, not bound by the in-app feature.  The previous version loaded and played the same file without issue, but I'd be glad to do anything that might help troubleshoot.

**Comment by Geordon** [comment]
Removed the app from my phon, made sure that I deleted the file from the phone (Commander One, went into the BookPLayer folder on the phone and deleted the MP3, redownloaded app and opened it without any contend.  Opened fine. 

Used Finder to load the same file back into the BookPLayer app, opened the app, imported the file, closed app, opened it, file plays as expected.

**Comment by GianniCarlo** [comment]
@Geordon  was the mp3 inside a playlist or at the library level? could you share that file to [my email](mailto:gcarlo89@hotmail.com) if it isn't too big?

**Comment by Geordon** [comment]
> @Geordon was the mp3 inside a playlist or at the library level? could you share that file to [my email](mailto:gcarlo89@hotmail.com) if it isn't too big?

It was originally at the library level.  I'll get you a copy of the file directly.

**Comment by Geordon** [comment]
@GianniCarlo Email sent!

**Comment by GianniCarlo** [comment]
Received! Thanks @Geordon

**Comment by Geordon** [comment]
@GianniCarlo I was listening to the book in question and I discovered that it stopped playing right around the 4 hour 5 minute mark.  I tried playing the same file on my computer and it plays fine through there.  Same with a different media player on my iPhone (Readdle Documents, for this instance)

**Comment by Urahara888** [comment]
I had .m4b on playback when it got that behavior.

**Comment by GianniCarlo** [comment]
I've submitted a new version to TestFlight, when the app launches and if it fails to load the last played book properly, it will show an alert with debug info, after that, you should be able to select manually the book back from the library and it should play. If it plays, then I would have confirmed that the problem is that when trying to load the chapters of a book via a CoreData relationship instead of a direct query to the database, it's generating a fault, making it crash

I'll comment back here when the build is approved for beta test in TestFlight 👌, thanks everybody for reporting and providing more info

**Comment by GianniCarlo** [comment]
> @GianniCarlo I was listening to the book in question and I discovered that it stopped playing right around the 4 hour 5 minute mark. I tried playing the same file on my computer and it plays fine through there. Same with a different media player on my iPhone (Readdle Documents, for this instance)

Regarding this @Geordon , it may be related to limitations with the engine we use, which is Apple's [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer). We have two other engines we'd like to test (VLCKit, AudioKit) but haven't had the time yet to add a proper abstraction

**Comment by GianniCarlo** [comment]
The beta is live @INFINITY-8888 @Urahara888 , if you haven't uninstalled and installed back again the app, please join via this [link](https://testflight.apple.com/join/FLv3zLyN), and let us know if the behavior I mentioned before is happening or if it's still crashing

> ... when the app launches and if it fails to load the last played book properly, it will show an alert with debug info, after that, you should be able to select manually the book back from the library and it should play. If it plays, then I would have confirmed that the problem is that when trying to load the chapters of a book via a CoreData relationship instead of a direct query to the database, it's generating a fault, making it crash

**Comment by GianniCarlo** [comment]
@Geordon I re-encoded the file you sent me using @ahoereth instructions in [this comment](https://github.com/TortugaPower/BookPlayer/issues/497#issuecomment-993857286) and it plays fine until the end, and the chapters metadata gets parsed too. I sent the reencoded m4b file to your mail using wetransfer 👍

**Comment by jodrescher** [comment]
I also had the problem with the crash. With the test version, the app starts normally again and plays the last book without displaying any dialog.

**Comment by GianniCarlo** [comment]
thanks for the confirmation @jodrescher , hmmm I'll leave the changes I put in to avoid relying on the CoreData relationships and fetch the data directly from the DB just in case. With that and another thing I'm finishing up, I'll release the new version 👍

**Comment by jodrescher** [comment]
@GianniCarlo After a complete app restart, the app crashed again directly, but then started on the second or third attempt. After further testing with complete app restarts, I was also able to reproduce this. The app sometimes starts directly, sometimes it crashes first and then starts.

**Comment by Geordon** [comment]
> @Geordon I re-encoded the file you sent me using @ahoereth instructions in [this comment](https://github.com/TortugaPower/BookPlayer/issues/497#issuecomment-993857286) and it plays fine until the end, and the chapters metadata gets parsed too. I sent the reencoded m4b file to your mail using wetransfer 👍

Awesome, thank you!  I'll admit, I wasn't the one who encoded the original file, so I don't know what the parameters were.  Interesting that the chapter info was parsed after reencoding the MP3 to M4B.  Regardless, thanks to both you and @[ahoereth](https://github.com/ahoereth)!

**Comment by GianniCarlo** [comment]
@jodrescher I just added a second build to TestFlight, with the logic added about loading the chapters directly from the db, please let me know if the crashing behavior still persists. This build also adds an option for a custom sleep timer as well

**Comment by INFINITY-8888** [comment]
@GianniCarlo , the second build works great. Starts and plays just fine. 
I appreciate you fixing it so quickly. 
Have a great day!
…back to listening my books…

**Comment by jodrescher** [comment]
In principle, it runs quite well again. However, I have a crash every now and then when starting the app. I tried to export a device log via XCode, but somehow it doesn't show me one.

Thanks for your effort
