### ISSUE TITLE
Repeat listening and scramble

### ISSUE THREAD

**Issue by F0nt** [TortugaPower/BookPlayer#758]
## Feature request

- The ability to repeat loop one file.
- and the ability to scramble a playlist for random playback of each file once, or to randomly play from the pool of files for  continuous playback.

## Narrative

With this ability, it would be possible to repeat listen to a short file of rain, for example, to help with sleeping or meditation, or to listen to a mix of various sounds that continuously play randomly.

It could be handled by adding three toggles to the playlist under the swipe left options. They could be something like "loop", "scramble and loop once" and "scramble continuously."
Visually, the playlist (folder) in the library can then show a little rotating arrow for loop and an S or similar for scrambled and maybe "cont" prefixing the S for continuous scrambled play.
For individual files, it's simply an extra toggle under player controls or similar placement. 

I hope this made sense :)

**Comment by pichfl** [comment]
This project is by name and intention a player for audiobooks which are not improved by shuffling them. There are many great independent and even open source players on the App Store which focus on music and background sound; BookPlayer has a different focus.
