### ISSUE TITLE
Bug: Sleep timer plays next chapter while audio fades out

### ISSUE THREAD

**Issue by daviddavis** [TortugaPower/BookPlayer#764]
## Environment

 - OS Version: 15.3.1
 - App Version: 4.4.5-2

## Description

[The original feature request](https://github.com/TortugaPower/BookPlayer/issues/404) says "When sleep timer is set to anything other than Chapter End [fade out the audio]" but BookPlayer seems to always fade out the audio even when the sleep timer is set to chapter end. 

IMO BookPlayer shouldn't fade out when the sleep timer is set to end of chapter. It would be better to just stop and not fade out.

## Steps to reproduce the behavior
1. Set the sleep timer to chapter end
2. Observe that the audio fades out and even starts the first few seconds of the next chapter

**Comment by GianniCarlo** [comment]
Hmmmmm yes this makes sense 🤔, for chapter end it wouldn't feel like an abrupt pause

**Comment by GianniCarlo** [comment]
Hey @daviddavis , I finally have a fix for this, it's currently live on a beta (link to join: https://testflight.apple.com/join/xLDneJXN) as I'd like feedback also on the shake-to-snooze functionality I put in as well (on a later version, I plan on adding a settings screen for the sleep timer to toggle both the fade-out and shake features)

**Comment by daviddavis** [comment]
@GianniCarlo I tested out the beta (both the end of chapter sleep and the shake to snooze) and they work well. 👍

**Comment by GianniCarlo** [comment]
thanks for the follow up @daviddavis !

**Comment by GianniCarlo** [comment]
Closing this issue, as this was included in v5.0.5 👌 (v5.0.6 currently live on the AppStore)
