### ISSUE TITLE
Bug: Apple Watch app rendered unusable with latest apple watch update

### ISSUE THREAD

**Issue by movieman12341** [TortugaPower/BookPlayer#766]
Refer to pic. That's the only screen and it won't let you do anything at all. If a book is playing, it still shows just like the pic. Can't pick a book or even show the now playing controls. Pushing the "refresh data" button doesn't do anything.

Latest version of IOS, Bookplayer, and WatchOS.

![incoming-08AE9775-824C-4E28-84A4-1191C44723C8](https://user-images.githubusercontent.com/21317547/156206621-dba3cb39-7763-48b3-b6ac-8c5e395fa0a6.PNG)

**Comment by GianniCarlo** [comment]
There are some issues with how BookPlayer uses the framework WatchConnectivity, those are being addressed in the watch app rewrite I'm working on with SwiftUI. I'm having some problems though with some items left to do, so I may open a WIP pull request and ask for help from the community
