### ISSUE TITLE
Option for the Player: switch chapters button with bookmarks. Or long press bookmarks button to bring up list.

### ISSUE THREAD

**Issue by TFenby** [TortugaPower/BookPlayer#767]
## Feature request

Apart from resuming an audiobook from where I left off in a physical book, I don't think I've once used the chapter list. I use bookmarks probably dozens of times daily. Set a bookmark when going to bed and setting a sleep timer, then skip back to it and fast forward a few minutes to get that nice balance between hearing more of the book but still using it as a sleep aid. Add a bookmark when a meeting you probably don't need to pay attention on starts that you can jump back to if you get distracted and stop listening. I'm sure there's plenty of others using bookmarks as extensively as I do, and it would be nice to swap them in as a primary feature/button in place of chapters.

## Narrative

In Settings, probably under Player Controls, add a toggle switch to change the Chapters button in the player with Bookmarks.
Alternatively, add a toggle switch to make a long press of the bookmarks button bring up the bookmarks list.

## Design

All existing design elements.

## Bribe

If there's a way to put a cash bounty on specific feature requests I'll throw some dollars at this.

**Comment by GianniCarlo** [comment]
This was included in the latest release (v4.6.0) now available in the AppStore
