### ISSUE TITLE
Off center progress ball

### ISSUE THREAD

**Issue by ThomasPf** [TortugaPower/BookPlayer#773]
## Environment

 - OS Version: [15.3.1]
 - App Version: [4.4.5-2]

## Description

When in the book part of the UI, the progress timer ball at the head of the current progress is slightly askew (the top part has more ball then the bottom part).

## Steps to reproduce the behavior
1. Open any book
2. See progress bar

![image](https://user-images.githubusercontent.com/19855145/159682567-3d7603c8-94d6-4d5b-bf2e-8034ecdf200d.png)

**Comment by fabifabulousity** [comment]
I noticed that as well. Although it’s only minor regarding UX, I wonder if this could be (easily) fixed?

**Comment by GianniCarlo** [comment]
This was addressed by @Jeepston and will be included in the next release (v5.0.0) 🙌
