### ISSUE TITLE
Bug: Telemetry Removed but still in privacy policy (with broken link)

### ISSUE THREAD

**Issue by scolby33** [TortugaPower/BookPlayer#784]
## Environment

 - OS Version: N/A
 - App Version: N/A

## Description

It appears that telemetry has been removed as of https://github.com/TortugaPower/BookPlayer/commit/f0abacd790f5d55d7c5375d8d2cad2406e2c102a, but it is still present in the privacy policy:
https://github.com/TortugaPower/BookPlayer/blob/89030b26129981a2c0de91c0327923d55b3eb06a/PRIVACY_POLICY.md?plain=1#L11

Additionally, this is a semi-broken link, which goes to an unhelpful page:

> ### Hi
> This website is no longer available using this domain, but you know where to find us. Sorry for the inconvenience.

If telemetry has been removed permanently, perhaps an update to the privacy policy should be made. If not, an up-to-date link in the privacy policy would be good to have.

## Steps to reproduce the behavior
N/A

**Comment by GianniCarlo** [comment]
Hi @scolby33 ! thanks for reporting this issue, for the time being we removed it, but we may introduce it back in v5.0.0 for cross device sync in a more limited capacity

**Comment by GianniCarlo** [comment]
I've updated the name and link in our privacy policy here (https://github.com/TortugaPower/BookPlayer/commit/ecb612887bc91afd24557c91592c07154133f8fa) 👍
