### ISSUE TITLE
Toggle to Disable Sentry Reporting

### ISSUE THREAD

**Issue by scolby33** [TortugaPower/BookPlayer#785]
## Feature request

I understand the usefulness of automated crash reporting for bug fixing and improving the user experience of the app. However, I would like to accept the cost of not having my problems automatically reported in order to limit the app's communication to third-party services. Ideally this would be opt-in at first run, but an opt-out option would also be appreciated.

As a mitigation, manual reporting of crashes could be added.

- Add a toggle to disable Sentry reporting
- Ideally, it would be possible to make this selection before any contact is made with external servers
- (More complicated, but could be useful) Add the ability to store Sentry reports to be manually exported and communicated to the developers (via GitHub or the like) instead of sending them via an external service
 
## Narrative

**GIVEN:**
- A user who would like to minimize contact with third-party services

**WHEN:**
- Initially using the app

**THEN:** 
- Offer the user the ability to disable reporting to Sentry, either explicitly or in the settings menu

**GIVEN:**
- A user who experienced a crash and would like to report details to the developer

**WHEN:**
- Entering the app after a crash has been experienced

**THEN:** 
- Offer the user the opportunity to manually submit the crash report to Sentry, to forward the crash report as an email, or to export the crash report as a text file to communicate it to the developers in some other way

## Design

- A simple toggle in the settings page that disables automatic submission of Sentry reports
- (Possibly) a question at first launch about whether to opt-in to Sentry reporting
- (Possibly) a new modal or other UI presented after a crash to manually submit the report, preferably including details of what is included in the report

**Comment by GianniCarlo** [comment]
v5.0.9 is currently live, and provides a way to disable sentry reporting 👌. I do believe we can take this one step further as you suggested, but instead of prompting on first launch, we prompt for access after a crash occurs to enable or keep off
