### ISSUE TITLE
Manage your files / sorting

### ISSUE THREAD

**Issue by oldman63** [TortugaPower/BookPlayer#796]
Under Settings / Manage your files

The file list is not sorting!

Please Add sorting options or sort the list by file name

Thx

**Comment by GianniCarlo** [comment]
Currently it's sorted by file size, but we could add a sort button at the top right corner to toggle between size and by file name 🤔

**Comment by oldman63** [comment]
Ok, thx

**Comment by GianniCarlo** [comment]
v5.0.4 is now live on the AppStore 🙌
