### ISSUE TITLE
Incorrect strings not found on Lokalise.com

### ISSUE THREAD

**Issue by oldman63** [TortugaPower/BookPlayer#799]
The "unknown author" text is not found on lokalise.com (Hungarian localisation, I am the Hungarian translator)

Also, there is a language error that I can't find:

Incorrect text: Fájlok
Correct text: Fájl

Please help me...

![2022 05 27-2](https://user-images.githubusercontent.com/3171626/170723419-eb4865a6-02f3-4006-b44d-5f18672b1fd6.png)

**Comment by GianniCarlo** [comment]
Hi @oldman63 ! the key we use there is `voiceover_unknown_author` probably it would be better to have a separate key 🤔 , but for the time being we're using that for the Unknown author. Regarding the plural form, the next app version will have the fix (Here's the line where we changed that → https://github.com/TortugaPower/BookPlayer/pull/797/files#diff-62108f0dcc6958dc1677ac225ef14e3f5b77b9e715bc705abe6044af97d59f00R16)

**Comment by GianniCarlo** [comment]
one thing to note, the Unknown Author value is set when the file is imported, I think we need to change that to an optional, so we only store in the database when the author exists, otherwise the unknown author key can be loaded on the fly in memory

**Comment by GianniCarlo** [comment]
yup, here is the folder for the hungarian translation → https://github.com/TortugaPower/BookPlayer/tree/develop/BookPlayer/hu.lproj
the .stringsdict file has the plural keys, and the .strings file has the regular keys that don't need plural form consideration

when looking through the files in the branch `develop` that's basically what's coming in the next release, and the branch `master` should have what is available in the AppStore version
