### ISSUE TITLE
Bug: App crash while opening

### ISSUE THREAD

**Issue by patjolata** [TortugaPower/BookPlayer#802]
## Environment

 - OS Version: 15.5.
 - App Version: 4.6.0

## Description

Since the last update of the BookPlayer app to v. 4.6.0 the app crashes while opening. I only can open it via the shortcut in the app switcher while I connect my phone to a bluetooth speaker. I'm using an iPhone 13.

Edit: It doesn't crash every time, but I haven't found a pattern yet. If I can provide any more help, please tell me what I can do. Thanks!

## Steps to reproduce the behavior
1. opening the app from the homescreen

**Comment by GianniCarlo** [comment]
Thanks for reporting the issue @patjolata , I've been looking into this, and it looks like it's crashing after loading the last played book and preparing to send the watch app context. Just to make sure I'm on the right error log, you have a paired apple watch?

**Comment by patjolata** [comment]
@GianniCarlo Yes, sorry I forgot about the watch. I have one paired.

**Comment by GianniCarlo** [comment]
@patjolata can you test if this is still happening on the latest beta version for the next v4.6.1? (link to join: https://testflight.apple.com/join/FLv3zLyN)

**Comment by patjolata** [comment]
@GianniCarlo  I‘ve installed the beta v. 4.6.1 last night and I haven‘t seen any crashes yet. Will keep you updated if some occur. Thank you again for your fast response and help! ☺️ I really love the app! 😊

**Comment by patjolata** [comment]
I still haven't had any crashes and I'm now on the App store version. I guess we can close this issue. Thanks again!
