### ISSUE TITLE
Bug: Cyrillic characters displayed incorrectly

### ISSUE THREAD

**Issue by qmicron** [TortugaPower/BookPlayer#803]
## Environment

 - OS Version: [e.g. 15.5]
 - App Version: [e.g. 4.6.0-4]

## Description

Cyrillic characters are not displayed correctly in list of files

![image](https://user-images.githubusercontent.com/22538575/173226305-f21b3b81-eae3-434e-81b8-3ef290030e82.png)

At the same time, library names are displayed correctly

![image](https://user-images.githubusercontent.com/22538575/173226217-896d5f85-9df3-4789-b1b0-8a24905c801c.png)

FileBrowser and Import apps also display everything correctly.

![image](https://user-images.githubusercontent.com/22538575/173226672-c0acd829-49a9-46aa-9de4-3b90702ebd6f.png)

![image](https://user-images.githubusercontent.com/22538575/173298680-e47d9a89-3cd3-4402-b40e-c04aa2c31138.png)

**Comment by qmicron** [comment]
I figured out where the crooked characters come from. They were originally in the title
![image](https://user-images.githubusercontent.com/22538575/173299706-b7ae8573-b97d-4b83-af11-b561f394eb33.png)

Sorry.

**Comment by GianniCarlo** [comment]
No worries 👌 thanks for following up, yesterday I was thinking of which would be the easiest way of verifying the file's metadata before replying, since we've had a similar issue filed like this before. It's good to know that the File Explorer show the info 👍
