### ISSUE TITLE
Bug: Strong battery drain when plaing short files

### ISSUE THREAD

**Issue by iNecas** [TortugaPower/BookPlayer#804]
## Environment

 - OS Version: 4.6.0
 - App Version: 15.4.1

## Description

When playing short files (around 2 minutes), it seems the phone gets warmer than on longer files (compared to 20-40 minutes). I've tried different encodings (mp3/aac) and bit rates and the length of the files seems like the key think that seems to be causing the warmth and battery issues. Even playback speed didn't seem to matter.

**Comment by GianniCarlo** [comment]
We received a report too via email support, I'm adding here the screenshot of the app usage for the other case to track the issue with this ticket

![image](https://user-images.githubusercontent.com/14112819/173680863-5703960a-fff2-4e65-9e1e-d7ef63588014.png)
![image](https://user-images.githubusercontent.com/14112819/173681120-6e7ac6d3-1b59-46b7-b8ad-3611de17475a.png)


if you can @iNecas, could you add yours too? I've been trying to replicate, but I don't see this level of battery drain, not sure if maybe it's the debug mode, I'll try running it as distribution and see what happens. For more context, how big in size is your library?

**Comment by iNecas** [comment]
Maybe, trying to create a book with 250 2-minute files and playing that could lead to reproduce the issue…

**Comment by mkellogg** [comment]
I had this issue too recently. 407 mp3s @ 64kbps, each about 5 minutes, or 2.5-3.0mb each. The phone got noticeably warmer and battery usage was much higher (82% of total usage in 3h44m of activity over a 24 hour period). 

My library only contained this and 2 other books. One with 88 40-45 minute files. The other a single m4b, 20 hours in length.

**Comment by Mr-Mistoffelees** [comment]
I'm experiencing the same issue. Device gets hot while playing an audiobook and battery consumption increases.

**Device / Software:** 
iPhone X
iOS 15.4
BookPlayer 4.6.1-1

**Audio Book**
424 files
~2-5 min, ~2-5MB each file
MP3, 129kBit/s

**How did I import the Audiobook?**

1. Put files into my NextCloud
2. Refreshed NextCloud on my device (did NOT download the audiobook)
3. Opened the BookPlayer App and tried to import ALL ~424 files at once. This failed and the BookPlayer app did not respond anymore.
4. So I split the audiobook into 4 folders, which contain 99, 99, 99 and 128 files
5. Imported the first folder and created a new playlist. Added the second, third and fourth folder to the existing playlist.

Uploaded a screenshot from todays playing "session". Not sure if anything of this helps but just to let you know. Thanks btw. for your incredible work which gave me hours a plesant driving while using the app. :)

![bookplayer_tmp](https://user-images.githubusercontent.com/74265480/177289775-32801bfc-57b3-4810-8e73-97581a44f7dc.jpg)
)

**Comment by iNecas** [comment]
FYI to workaround the issue, I've used https://github.com/sandreas/m4b-tool to merge the small files into chapterred m4b: seems like BookPlayer is better optimized for that format (+ allows easily switch progress view between chapters and the whole book).

**Comment by GianniCarlo** [comment]
The new beta has a possible fix for this (link to join: https://testflight.apple.com/join/FLv3zLyN). It reworks how the next item is fetched (which before it was looping through the entire folder which is not good). If someone can test this and confirm if it helps, it'd be great 👍

**Comment by GianniCarlo** [comment]
got confirmation via mail support that this one is fixed 🎉
