### ISSUE TITLE
Button-free / gesture based navigation

### ISSUE THREAD

**Issue by kooshiel** [TortugaPower/BookPlayer#825]
## Feature request

Hello and thank you for BookPlayer. I would love to see a button-free mode that would allow for gesturing left/right to go back/forward the specified skip interval. I use this all the time in the Audible app so that I can easily rewind without looking at my device. It's especially useful when driving. I'm currently using Bookmobile to listen to my non-Audible books which also has this feature (driving mode). I would very much like away from Bookmobile and this is the one feature that's holding me back.

Audible also allows gesturing up/down to add a clip/bookmark, which I don't use as much. Actually, I find that I often accidentally add clip/bookmarks, which is annoying. I'd rather have an option to disable this feature, or perhaps attach a different gesture for adding bookmarks like double tap or something.

Thank you for considering.

![IMG_6489](https://user-images.githubusercontent.com/1352102/187045932-04061d58-c86a-4f2a-b058-a3c65eead825.PNG)

**Comment by GianniCarlo** [comment]
Interesting, I wasn't aware there was a button-free screen in Audible 🤔 

This should be fairly easy to do for anyone who wish to contribute, the code requirements and screen lifecycle are similar to how the Bookmarks screen is created and presented (coordinator, viewController and viewModel), it just needs the PlayerManager object (for the play/pause and skipping) and the LibraryService object, to create the bookmarks. There would need to be a notification pane or view banner that gives feedback to the user about their action.

I can provide further instructions if needed over on [Discord](https://discord.gg/6YmZcN54EW) in the #dev channel

**Comment by GianniCarlo** [comment]
This will be included in the next release
