### ISSUE TITLE
Bug: CarPlay interface icon size wrong

### ISSUE THREAD

**Issue by fabifabulousity** [TortugaPower/BookPlayer#831]
## Environment

 - OS Version: iOS 16.0
 - App Version: 4.7.0

## Description
Size of button icons at CarPlay interface inconsistent. See the attached screenshots. It seems that at booth screenshots the size of the icons seems wrong. Especially the bookmark icon. Maybe you could have a look at using the SF icons set instead of custom icons. 

## Steps to reproduce the behavior
1. connect iPhone with car to activate CarPlay
2. open BookPlayer
3. start playback of an audiobook

![8564F4D0-926A-4F2A-AC96-9C547167025E](https://user-images.githubusercontent.com/72652159/190261817-a3ccb07a-ec9c-4be5-8898-b58d595223aa.png)
![B1B5F35E-D5ED-468F-A81D-C39919059C4A](https://user-images.githubusercontent.com/72652159/190261824-42b1033d-8884-47ef-afb8-80729f821fb3.jpeg)

**Comment by GianniCarlo** [comment]
thanks for reporting @fabifabulousity , I was hoping it was just an issue in the beta, as nothing has changed in the carplay manager regarding icons. I'll look into a solution for this

**Comment by fabifabulousity** [comment]
Okay, maybe one more thing. I only had the chance to test this a few times since I run on iOS 16 when it was officially released: when BookPlayer on the iPhone is not in the background (hence closed completely) and I would like to start it from the CarPlay interface it just gives me a black screen and does not show any audiobooks. I needed to start the app on the phone first. Is this a thing you have also noticed?

**Comment by GianniCarlo** [comment]
This is solved in v4.7.1. Regarding the other thing you mentioned @fabifabulousity, I haven't had that issue yet, but feel free to open a new ticket to track that one 👍
