### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by available-is** [TortugaPower/BookPlayer#846]
## Feature request
Help Wanted !!!!
- Describe in broad strokes the changes or enhancements you'd like to see
- Would like to find in Wiki or Q&A a short guidance on how to UNINSTALL in a clean way the App with all its hidden features, like database etc.... 
- **Today, I just would like to know How to proceed with the UNINSTALL as described before** 
- Thanks !!!

## Narrative

- Feel free to change the following format to better suit the details of the enhancement
- I installed the App because I was looking for an alternative for "books" on my new MacBook Air (M2, 2022), but unfortunately the App does not meet my needs and on top it doesn't work well ....

**GIVEN:**
- Provide the context of the application: **BookPlayer.app**
**WHEN:**
- Describe the action or trigger: opening a self created audiobook (which played fine in previous iTunes and in the Books App) the BookPlayer presents itself with the icons "-30" - "play" - "+30" on top of the other items underneath the name of the audiobook in a way I can't read and use what is underneath - as well the "play" button etc. doesn't respond ... so it feels useless for me...
- On top the App crashes unexpected quite often, while trying to navigate through the app and its futures.

- **THEN:** 
- Describe the resulting change of the state in the application
THANKS for your HELP !!!! 
I'm just a user of the app, didn't found another way to ask for help other then signing up in GitHub ... feels complicated too.... would had preferred to donate, if satisfied with the app... sorry and thanks for your quick help here!

## Design

_Provide design example, screenshot, text input/output etc_

<img width="509" alt="Bildschirmfoto 2022-10-16 um 09 51 25" src="https://user-images.githubusercontent.com/115918996/196024858-13acaa91-3a49-4d44-8d55-6c27622d85ff.png">

**Comment by GianniCarlo** [comment]
Hi there, hmmm it looks like for some reason the app is stuck in landscape mode in the MacBook, I don't currently have access to an M1/2 machine, so I can't quite debug the issue, as landscape is not enabled. That said, to uninstall on the Mac, it should be the same as any other app you install from the AppStore, just go to your Applications folder, and drag to the trash bin, emptying the trash bin should remove all records of the app. We don't really add anything else on the Mac, as it's only available for M1/2 machines because they can run iPhone apps

**Comment by available-is** [comment]
Hi Gianni Carlo,
Thanks a lot for getting back so fast.
Regarding to landscape mode, couldn’t find anything to enable or disable this….
I just uninstalled as you said. Thought it might have a database somewhere…. 
So thanks for clarifying!
Britta
