### ISSUE TITLE
iOS 16: no cover art on lockscreen 

### ISSUE THREAD

**Issue by huehnerbrueh** [TortugaPower/BookPlayer#849]
Not sure if it is me or if it is a bug: cover art is shown in the app but not on the lockscreen.

**Comment by GianniCarlo** [comment]
🤔 iOS 16 introduced an option to move the artwork to the background of the lockscreen, not sure if that is bugging out at the OS level? see video attached


https://user-images.githubusercontent.com/14112819/196188541-098a7273-c6ee-4e54-a7ea-3eb6d1080fef.mov

**Comment by huehnerbrueh** [comment]
Yes, that’s how I thought it should be. Looks like this for me:

![32620050-375D-4A59-A7F9-8A818B7425A4](https://user-images.githubusercontent.com/48827157/196199743-eb2410a8-f740-4a8d-b20f-eb7897795b22.png)

![A8E4ADC0-2F6E-4592-AC95-7BC2A635989A](https://user-images.githubusercontent.com/48827157/196199920-2ca4364f-30cd-4f32-b3db-b57ddf702817.png)

I’ll try tagging the file with a different App, maybe that will solve it.

**Comment by huehnerbrueh** [comment]
There was a BookPlayer update today (4.7.2) that fixed it. The artwork is displayed correctly now.
