### ISSUE TITLE
Album Artwork Editing and Author Renaming

### ISSUE THREAD

**Issue by mckayfackrell** [TortugaPower/BookPlayer#854]
## Feature request
For some of the mp3 files I forgot to edit beforehand, there is no way to edit the album artwork or author once the files have been transferred to BookPlayer. 

My request is for the option to edit the album artwork by simply adding a photo from the user's photo album on their phone. 

The request would also include the option to rename the author or add the author if it was previously not in the mp3 files. 

## Narrative
**GIVEN:**
The user imports their own mp3 audiobook files and saves them to a volume but has no album artwork or author. 
**WHEN:**
The user can press the edit button to display a new pencil button on top of the preexisting album artwork of each volume indicating it can be changed. 

The user can also swipe left on the volume and press the options button to pull up the options menu. A new menu feature would be present, "edit album artwork". 

As for the editing of the author request, the user can press the preexisting rename button to pull up the renaming of the title card. Instead of editing the volume title only, there would be another entry to edit the author of the volume as well. 
**THEN:**
The user can then edit the album artwork from each instance stated above. They must grant permission to allow access to their photo library, select the appropriate photo, and be given the option to crop the photo if necessary. 
(By default the photo would automatically crop in a square ratio, but the user can center or change the size of the square ratio.)

The user has successfully changed the album artwork for the specified volume. 

As for the author, the user can click rename after entering the title and author correctly. 

Both the album artwork and author will display accordingly as if the information was in the original mp3 files. 

## Design
![34DE0EAA-D528-4C0B-8FAD-4C7DD06ED009](https://user-images.githubusercontent.com/110206514/199314060-9ca3edb6-6be4-4704-9820-ac50fc56752c.jpeg)
![3293D10A-EF7C-42D1-A5EC-39D33EFC885D](https://user-images.githubusercontent.com/110206514/199314064-fedc6b24-7840-443a-91fb-6554265ad9c9.jpeg)

**Comment by GianniCarlo** [comment]
Hi @mckayfackrell , yes this is something that we want to tackle for the next major version, though we were thinking on displaying a screen with the different options to modify instead of having the different controls in the library and update via alerts 🤔

**Comment by mckayfackrell** [comment]
That sounds like a great option! I'm looking forward to that release. Let me know if there is anything I can do to help move the process along (ie testing).

Just want to say how much my wife and I love using this app! We put on Harry Potter whenever we go on road-trips, it's the best! Thanks for all the hard work 🙌🏼

**Comment by GianniCarlo** [comment]
v5.0.0 is finally released, there are big fundamental changes on how the app works, so we'll be checking if any issues come up that need to be addressed
