### ISSUE TITLE
MacOs app delete files without asking

### ISSUE THREAD

**Issue by yoeluru** [TortugaPower/BookPlayer#859]
If you open an mkv file and then click on cancel on importing, the file will be removed from your system.

**Comment by GianniCarlo** [comment]
Looks like we need to add a check of the platform before deleting the files. On iOS the files are copied to an Inbox folder by the system, so we need to free that up if [the import operation is cancelled](https://github.com/TortugaPower/BookPlayer/blob/develop/BookPlayer/Import/ImportViewModel.swift#L92). I'll include that fix for the next version, thanks for reporting the issue @yoeluru

**Comment by GianniCarlo** [comment]
This should have been solved by https://github.com/TortugaPower/BookPlayer/pull/899 which was released just now in v5.0.0
