### ISSUE TITLE
Recent books widget on iOS is blank

### ISSUE THREAD

**Issue by Fmeraz9888** [TortugaPower/BookPlayer#861]
The recent books widget on iOS is blank, have deleted the app, restarted my phone, updated everything and nothing shows up on the widget.
![08EB9DAD-C7BF-4159-BA14-5D9E4A16E953](https://user-images.githubusercontent.com/103539241/207434851-474f40a7-474b-41c6-9e8a-cba51032c63e.png)

**Comment by sfmoca** [comment]
I also have this issue. 5.0.2-3, iOS 16.5.1. iPhone 14 Pro Max. Like OP, I’ve tried to restart the device, remove and reinstall the widget, etc., with no success. 

I use this widget a lot so I would appreciate a fix / help. Thank you!

**Comment by GianniCarlo** [comment]
v5.1.0 is out now and has reworked the widgets, please let me know if this issue persists
