### ISSUE TITLE
Bug: IOS - Audiobook gets deleted when opened via Files.app (or imported a second time)

### ISSUE THREAD

**Issue by crieke** [TortugaPower/BookPlayer#867]
## Environment

 - iOS 16.2
 - App Version: 4.7.2-1

## Description

I am not sure, if this issue fits into this topic as well. As I've noticed a file deletion issue on iOS as well.
If I click on an m4b via the Files app in the `BookPlayer/Processed` folder, it opens up the BookPlayer app and asks to import that file again (even though it is already imported). 
- You have 2 choices then: If you cancel the process, the audiobook gets deleted and the already imported one can't be played anymore.
- You click Import (again) and have a duplicate of the audiobook in the Book Player library.

It'd be great, if BookPlayer would not try to import an already imported audiobook again when it is selected from the Files.app within BookPlayers own folder. Instead it could launch BookPlayer and start Playback of the corresponding audiobook.

## Steps to reproduce the behavior
1. Have BookPlayer installed on your phone with some imported Audiobooks 
2. Open Apples Files.app and browse "On My Phone"`/BookPlayer/Processed`
3. Click on any audiobook file
4. Import Screen in BookPlayer will pop up
5. Either select "Cancel" (-> Audiobook will no longer be available in Bookplayer)...
6. ...or select "Import" (-> Audiobook will be in the Library twice)

**Comment by GianniCarlo** [comment]
🤔 are you accessing it via Files due to the search functionality? or is there another reason you go through there? that aside, yeah it makes sense to detect that the incoming file is already from the Processed folder, so it doesn't prompt importing the book again

**Comment by crieke** [comment]
Actually, I tried to find the audiobook file in the Files app to share it with another device by airdrop (and was not aware of the option to share it within BookPlayer when swiping the audiobook in the Library). That led to the situation that I clicked some m4b files in the files app by accident.
I was a little bit puzzled about the deleted file afterwards...
But I could imagine, it might happen in other situations as well, when people just browse or (as you mentioned) search for files and click on it...

**Comment by GianniCarlo** [comment]
ooooh ok, makes sense 👍

**Comment by lamnatos** [comment]
Just to second this, I've had the same thing happen to me. Tap book in Files.app, select Cancel, book is deleted from app.

**Comment by GianniCarlo** [comment]
The fix is included in the newly released v5.0.0 🙌
