### ISSUE TITLE
Motion reset sleep timer

### ISSUE THREAD

**Issue by elric667** [TortugaPower/BookPlayer#869]
## Feature request

Sleep timer reset on motion like into the one in smart audiobook player for android

## Narrative

I love their sleep timer function. It’s a unique feature I have never seen in any other audiobook app. You set a time after which the player turns off, but if your device notices movement, the timer resets.

So, if you are still awake and want to continue listening, just give your phone a little shake. No need to look at the screen and reset the sleep timer manually!

**Comment by GianniCarlo** [comment]
Hey @elric667 , I finally implemented this, it's currently live on a beta (link to join: https://testflight.apple.com/join/xLDneJXN) let me know how you feel the shake gesture recognition (I plan on adding a settings screen for the sleep timer to toggle both the fade-out and shake features in a future version)

**Comment by GianniCarlo** [comment]
just a heads-up that the first build of the beta had a crash related to some VoiceOver translation updates for v5.0.5, and it was limited to a subset of the languages we support (more info on #969), I've updated TestFlight with a new build which fixes this issue

**Comment by GianniCarlo** [comment]
Closing this issue, as this was included in v5.0.5 👌 (v5.0.6 currently live on the AppStore)
