### ISSUE TITLE
Pause at end of chapter not working

### ISSUE THREAD

**Issue by markangeltrueman** [TortugaPower/BookPlayer#880]
## Environment

 - OS Version: ios 16.3.1
 - App Version: 4.7.2-1

## Description

Pause at end of chapter isn't working. This is with a single mutli-chapter m4b file.

## Steps to reproduce the behavior
1. Start a chapter
2. use the sleep icon to set pause to end of chapter
3.  when chapter reaches the end, the book continues to the next chapter.

**Comment by GianniCarlo** [comment]
Just a heads-up @markangeltrueman , I finally have a fix for this, it's currently live on a beta (link to join: https://testflight.apple.com/join/xLDneJXN) as I'd like feedback also on the shake-to-snooze functionality I put in as well (on a later version, I plan on adding a settings screen for the sleep timer to toggle both the fade-out and shake features)

**Comment by GianniCarlo** [comment]
following up on this, the first build of the beta had a crash related to some VoiceOver translation updates for v5.0.5, and it was limited to a subset of the languages we support (more info on #969), I've updated TestFlight with a new build which fixes this issue

**Comment by GianniCarlo** [comment]
Closing this issue, as this was included in v5.0.5 👌 (v5.0.6 currently live on the AppStore)
