### ISSUE TITLE
Bug: .battery of my iPhone 11 pro started to be super hot after a few minutes of using the app. furthermore, I'm losing battery capacity super fast. The Other app is working well without any issues. ..

### ISSUE THREAD

**Issue by maksupilami** [TortugaPower/BookPlayer#884]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
I'm closing this issue in favor of ticket #843 to consolidate all the info and have one place where I can follow up with updates
