### ISSUE TITLE
Bug: the player adjusts the length of audio files twice

### ISSUE THREAD

**Issue by vovikhs** [TortugaPower/BookPlayer#895]
Hello, the player adjusts the length of audio files twice.  Why so?  For example, the duration of an audiobook is 1 hour, and the player shows 2 hours

**Comment by GianniCarlo** [comment]
Hi @vovikhs , can you verify with a tool like [mp3val](https://sourceforge.net/projects/mp3val/) to check if the file integrity is ok? when a file is imported, we check the file's metadata to load all relevant information about the book, including the duration

**Comment by vovikhs** [comment]
Hello. In the player, for some reason, the duration of files (books)
shows 2 times more. For example, here is a file with a book, 6 hours,
17 minutes and 21 seconds long. But the program displays 12 hours 32
minutes and 42 seconds. And so it is with every book. m4a files

чт, 20 квіт. 2023 р. о 23:42 Gianni Carlo ***@***.***> пише:

**Comment by vovikhs** [comment]
Here is another example with another book, also in the player shows
the duration 2 times longer. When a book is ordered, time just goes by
and it's quiet

пт, 21 квіт. 2023 р. о 18:15 Volodymyr Pavlenko
***@***.***> пише:

**Comment by vovikhs** [comment]
Hello.  Please tell me, is there any way to solve this problem?

пт, 21 квіт. 2023 р. о 18:18 Volodymyr Pavlenko <
***@***.***> пише:

**Comment by pichfl** [comment]
Please double-check the files with the software Gianni mentioned before. mp3val will also check m4a files.

**Comment by vovikhs** [comment]
Files without errors, they correctly display the duration.  Also, the
duration is correctly displayed in other players.  Not displayed
correctly only in BookPlayer

нд, 23 квіт. 2023 р. о 20:30 Florian Pichler ***@***.***> пише:

**Comment by GianniCarlo** [comment]
next thing would be if you could share via email one of the files with the issues to take a look into it

**Comment by vovikhs** [comment]
https://drive.google.com/file/d/16zxaHvarsvvwud-W4wWu_0EHHwBfe4Mf/view?usp=drivesdk


чт, 18 трав. 2023 р. о 03:17 Gianni Carlo ***@***.***> пише:

**Comment by GianniCarlo** [comment]
Late follow up, I checked the file, and it looks like it's an aac file underneath, and from what I've read, the mp3 container cannot store an aac stream, so that's definitely one of the problems. As mentioned on other tickets, we don't really manage encoding of the files, we just put the native `AVPlayer` to read the audio files, and show on the UI the info we get

<img width="943" alt="Screenshot 2023-08-20 at 14 23 06" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/afaba0d4-eeea-4b03-a007-62c310ab8fe2">
