### ISSUE TITLE
Adding book cover art

### ISSUE THREAD

**Issue by djvice** [TortugaPower/BookPlayer#903]
I see in the screensshots of the app in the app store that book cover art is supported, but I cannot find how to add a books cover art. Please help. Thanks!

## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
The current app store version loads the artwork from the file's metadata, if your file doesn't include the artwork, then the app will show a default one. In [our wiki](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-combine-mp3-files-into-m4b-audio-books) we list some apps you can use to transform mp3s to m4b and in the process add an artwork as well. One thing to note, is that we're bringing support for updating the artwork and author's name from within the app in the next release
