### ISSUE TITLE
Apple Watch independent Download

### ISSUE THREAD

**Issue by JCDC85** [TortugaPower/BookPlayer#912]
## Feature request

- Describe in broad strokes the changes or enhancements you'd like to see

What are the chances of us getting the ability to download/import audiobooks directly onto Apple Watch to listen to without internet/iPhone nearby? The primary reason I got an Apple Watch was to go on runs and exercise, listening to audiobooks/podcasts, while leaving my iPhone at home. I would definitely pay money for this to be a premium feature.

**Comment by GianniCarlo** [comment]
Hi @JCDC85 ! yes, there is a two step update, the first one being playback streaming from the Apple Watch, and the second one is transferring the file to the apple watch for offline playback. The first one will be the focus of the next version v5.1.0

I'm closing this ticket, as your request is already being tracked on #651
