### ISSUE TITLE
Navigation bar is white while 'Always use dark theme' is enabled after update to 5.0.0

### ISSUE THREAD

**Issue by patjolata** [TortugaPower/BookPlayer#916]
- OS Version: iOS 16.5
 - App Version: 5.0.0

After the update to version 5.0.0 BookPlayer will show the navigation bar in white even if the option 'Always use dark theme' is chosen. While changing the option and re-applying it leads to the result that the navigation bar is dark as well. But completely closing and re-opening the app the navigation bar will be white again.

1. Open BookPlayer with the option 'Always use dark theme' enabled
2. Navigation bar will still be white (while the rest is dark)
3. Toggle the 'Always use theme' off and on again and the navigation bar will be dark
4. Close and re-open the app and the navigation bar will be white again

![IMG_1669](https://github.com/TortugaPower/BookPlayer/assets/53347808/af4af507-ca0f-4962-93a9-41c9584b7959)

**Comment by GianniCarlo** [comment]
Thanks for reporting the issue @patjolata, I have an additional question so I can reproduce the same case, is the dark mode at the OS level light?

**Comment by patjolata** [comment]
Yes, I have my OS in the light mode. I'm using BookPlayer mostly in the evening in bed - that's why I prefer to have it in dark mode. But I like iOS more in the light mode. Hope that helps you to find the bug.

**Comment by Jeepston** [comment]
Apparently, this is related to changing appearance of the toolbar when scrollview offset is changing. Not reproducible on Simulator

**Comment by GianniCarlo** [comment]
I was able to reproduce this issue by having my system setting to light, forcing the app to be on dark mode, and force quitting the app and launching it without any debugger attached. I found there are two things that were not being set on code. I'll include it on the next update

**Comment by GianniCarlo** [comment]
This is now live on v5.0.3 in the AppStore, @patjolata whenever you can, please let us know if you still see this issue

**Comment by patjolata** [comment]
Thank you! Looks perfect. Have tried to start the app a few times and the navigation bar is dark as it should be.
