### ISSUE TITLE
Bug: The time in library is not shown anymore

### ISSUE THREAD

**Issue by smk62** [TortugaPower/BookPlayer#921]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## In the Library the time is not shown anymore

In the library you see how many file are in the folders, but not any more, how long they are, how much time it would need to listen to the files.

I see four files, length 0 seconds for example - It should be 47 hours 25 min or so.
The files in the folders are accessible. You can still listen to the audiobooks.

## Steps to reproduce the behavior
1. open the book player app
2. look in the folder menu
3. Close the app, the bug remains
![Bildschirmfoto 2023-06-19 um 21 31 28](https://github.com/TortugaPower/BookPlayer/assets/137110201/3b4bbf6a-4a6f-47f1-ac9a-8092d24c23ff)

**Comment by GianniCarlo** [comment]
@smk62 v5.0.1 is live now in the AppStore, while I don't think the fix I included for the folder details will have an effect here, it's worth to check. 

Regarding this particular issue, one quick way to fix it would be to just create an empty folder inside each of them and delete it, the folder details will be rebuilt, and the duration should be updated. I need to understand though if this happens midway usage (so it could happen again), or if it happened as soon as the app was upgraded

**Comment by GianniCarlo** [comment]
I put out a separate beta build for anyone that experienced this issue (link to join this group: https://testflight.apple.com/join/55p6XyEa). This build will rebuild details of any folder shown on screen that have the `0s` duration , and on the next app launch, it should show the proper duration.

This is just a temporal measure to quickly fix the details of anyone who had the database migration problems when first going from v4.x.x to v5.x.x, and after having the folders fixed, I recommend that you install back the latest AppStore version (you shouldn't have any problems switching from AppStore to TestFlight and back again)
