### ISSUE TITLE
Broken update 

### ISSUE THREAD

**Issue by fernandobrigida** [TortugaPower/BookPlayer#924]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by fernandobrigida** [comment]
iOS 16.5
App 5.0

after the last update (5.0) the crashes as soon as it’s open 
It freezes in the background image 
No response

**Comment by GianniCarlo** [comment]
@fernandobrigida is any error message shown and afterwards it stays on the background image? if so, we're tracking that on #918

**Comment by fernandobrigida** [comment]
Yeah, it’s the same bug
Thanks for getting back so quickly 

keep up the good work

**Comment by GianniCarlo** [comment]
@fernandobrigida just a heads-up that we have a beta live right now (link to join: https://testflight.apple.com/join/xLDneJXN), and the build was submitted yesterday to the AppStore for review and approval for release. The library progress will most likely be unrecoverable, but all the files and folder hierarchy will show up if you haven't deleted the app yet

I'm closing this issue in favor of #918
