### ISSUE TITLE
Bug: ITUNES FILE TRANSFER - EVERYTHING DELETED

### ISSUE THREAD

**Issue by zaynumar** [TortugaPower/BookPlayer#927]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

What has happened ???
My entire Audibook library has been deleted !!!!

I was trying to import some new books to my library via iTunes file sharing - normal easy method - drag and drop boom. Now after the update it doesn’t work.

I then cleared all the untransferred files on my iTunes (they didn’t transfer / app didn’t registered them after syncing) then all of a sudden over 100gigabytes of my iPhone vanish… 

The app has deleted my entire library !!!

these recent updates have been too much at once and it has ruined a lot of things 

Edit 

i cleared all the data and deleted the app and reinstalled and started again:

after importing 55 books from my pc to iPhone via iTunes file transfer with BookPlayer , the stupid app isn’t showing or recognising my books even though they’re in the files folder for BookPlayer section….

i don’t understand why they’re not automatically synced  #[](url)

## Steps to reproduce the behaviour
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
@zaynumar this looks related to https://github.com/TortugaPower/BookPlayer/issues/915 , can you verify if you're on v5.0.0? We just released v5.0.1 which fixes this issue and should show the disappeared items

Please let us know the app version, you can go to settings and in the support section there's a label with the info (see screenshot)

![image](https://github.com/TortugaPower/BookPlayer/assets/14112819/1ea7bdf0-f1a6-4910-ad8f-d2d63a00be04)

**Comment by zaynumar** [comment]
I’m on the LATEST VERSION

and also

There needs to be another edit section on the tittle for AUTHOR NAME aswell… 

WHAT FILE STRUCTURE DO WE NEED TO IMPORT THE BOOKS SO ALL INFORMATION IS THERE?

I’ve been using 

author name > Book title > audiobook files

But I don’t like the way it appears on the app as it shows the author as an extra folder so I delete the author folder and then just have the book title but when I do this author name is unknown?

what to do …
![IMG_2722](https://github.com/TortugaPower/BookPlayer/assets/41214891/54ffdc34-bcb1-4430-be4d-0a7a8943c988)

**Comment by GianniCarlo** [comment]
@zaynumar I'm trying to reproduce the issue but with no success. Can you send me a screen recording of the process? or a very detailed steps to reproduce the issue?

What I've tried so far:

* Transfer via USB 2 audio files, while on the app being inside a folder, the two files were imported without problems
* Transfer a folder with 2 audio files at the root of the library, the folder was imported without problems
* Transfer a folder with 2 audio files, while on the app being inside a folder, the folder was also imported without problems

After each successful import, I checked the previous files, and they're still there. When dropping the files onto the iPhone File Sharing tab, I just added them at the root level

Let me know if there's an additional step, or the quantity of files I should be testing with (and the hierarchy of the folders)

**Comment by GianniCarlo** [comment]
@zaynumar there's a new Testflight build (link to join: https://testflight.apple.com/join/xLDneJXN) that solves showing the import screen, and should address this issue as well. Please let me know if this also fixes your issue

**Comment by GianniCarlo** [comment]
@zaynumar v5.0.2 is out! That should address the issue about the app not recognizing the files added via iTunes File sharing. There is another issue here, which was the deletion of the library, we've found a scenario when this could happen when importing and renaming the folder when it's in the process of uploading it to the cloud, we're working on a fix for that.

To keep things cleaner and keeping one problem per issue, I'm closing this ticket, and opening another to focus on the problem I mentioned.

Sorry again that the library got deleted, we'll sort this out in the next version so it doesn't happen again
