### ISSUE TITLE
Bug: Issue assigning book art

### ISSUE THREAD

**Issue by jmk5543** [TortugaPower/BookPlayer#931]
## Environment

 - iOS: 16.5.1
 - App Version: 5.0.1

## Description

Attempts to add art to a book are unsuccessful, app displays 'error: item not exists'. See attached video. https://github.com/TortugaPower/BookPlayer/assets/83310552/122a8f73-04d4-4841-aa91-c6c58ee3cd1a

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
Hi @jmk5543 , I think this is related to #919 , can you confirm this only happens with the items that were just imported?

**Comment by jmk5543** [comment]
@GianniCarlo No, not imported recently. The mp3 files had been in the app for days. The mp3 files had been combined into a volume for at least 48 hours.

**Comment by GianniCarlo** [comment]
@jmk5543 can you check on the Profile tab, if there are any Queued sync tasks? just to verify if there are any sync jobs that got stuck, if that's the case, can you send me via mail to support@bookplayer.app the email or private relay email you used for sign up so we can verify any possible errors on our servers?

If you used Apple's  private relay email, you can find it on your iPhone or iPad going to the following:
- Open the Settings app, then tap your name to view your Apple ID settings.
- Tap Password & Security.
- Tap Apps Using Your Apple ID.
- Tap BookPlayer
- The Apple Relay Email will be displayed under 'This App Received:'.

**Comment by GianniCarlo** [comment]
@jmk5543 v5.0.2 is out, and should fix the problem, I'm closing this issue but feel free to comment if this happens again
