### ISSUE TITLE
Bug: Folder structure lost on recent update

### ISSUE THREAD

**Issue by skobylite** [TortugaPower/BookPlayer#957]
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

On the recent update, I've lost the folder structure for my library - all files are now loose. Is there a way to restore this?

(Apologies if I've missed the memo on this, I've looked through the release notes and previous issues and can't find anything about this)

## Steps to reproduce the behavior
- Opening library feed

**Comment by GianniCarlo** [comment]
Hi @skobylite , do you remember what version were you on before updating? If a migration fails, it reboots the library with the folder hierarchy that is on disk, and having the folder hierarchy on disk reflect the digital library 1 to 1 was introduced in v4.0.0, so this could be a migration error coming from v3.12.0. One easy way to know that you were on v4.x.x was if you ever saw the storage management option in settings (third section), as that was introduced shortly after v4.0.0

![image](https://github.com/TortugaPower/BookPlayer/assets/14112819/aa59d432-2b3b-4798-ad62-85041e528c6e)

If you were already on v4 before installing v5, can you verify if the folders are still on disk by going to the Files app → On my iPhone → BookPlayer → Processed ?

**Comment by GianniCarlo** [comment]
I'm closing the ticket due to inactivity, @skobylite please let me know any additional info you can provide from what I mentioned on my previous comment, also v5.0.4 is now live on the AppStore, which brings more stability to the app

**Comment by skobylite** [comment]
Sorry for the delay. I usually update every week, so I wasn't updating from a particularly old version. The folder structure is still intact on my icloud, and 80% of the files are still on the disk. It's a good prompt for me to delete everything and clean up my library anyway from unfinished books, now that sync is available!
