### ISSUE TITLE
Bug: iPad in landscape / horizontal view

### ISSUE THREAD

**Issue by hendrikthilo** [TortugaPower/BookPlayer#965]
## Environment

 - OS Version: [iPad 16.5.1]
 - App Version: [5.0.4]

## Description

Elements at bottom are overlaying over each other when in horizontal view. It does not seem to be wanted, but I’m not sure. It is better in vertical.

## Steps to reproduce the behavior
1. Open app, 
2. start playing audiobook
3. enlarge view away from library view
4. 

Example picture

![IMG_4365](https://github.com/TortugaPower/BookPlayer/assets/80397986/32400c5a-723c-4b38-a392-ce56d3724328)

**Comment by GianniCarlo** [comment]
Yes it's definitely a bug, I've been trying to reproduce it, and it looks related to the size and aspect ratio of the artwork, I'll see how to add constraints to it, so it doesn't push off the controls like that, thanks for reporting it @hendrikthilo !

**Comment by GianniCarlo** [comment]
@hendrikthilo the fix is currently up on a beta on TestFlight (link to join: https://testflight.apple.com/join/xLDneJXN). Please let me know if it fixes your issue

**Comment by hendrikthilo** [comment]
It is fixed with this beta version. Thank you very much for your amazing work.

**Comment by GianniCarlo** [comment]
Closing this issue, as this was included in v5.0.5 👌 (v5.0.6 currently live on the AppStore)
