### ISSUE TITLE
Documentation Request: 5.0 sync features documentation 

### ISSUE THREAD

**Issue by tom-kaufman** [TortugaPower/BookPlayer#966]
## Feature request

- I didn't see an issue for this already. I'm requesting the documentation for the sync service added in 5.0. I'm excited to make my own desktop app that works with BookPlayer so that I can seamlessly go back and forth between my mobile and PC!

**Comment by GianniCarlo** [comment]
Thanks for opening this ticket @tom-kaufman ! I'll get to this after I wrap up v5.0.5, I'm almost done with the sleep timer related issues and improvements I'm working on, I wanted to include some changes to the background URLSessions management, as I got some feedback from Apple's code level support thing, but I'll focus on that on v5.0.6 🤔

**Comment by GianniCarlo** [comment]
Got the Postman collection in a shareable state (don't forget to set the specified jwt_token variable at the collection level):

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/10416776-40a49b6e-8f9f-463f-8f06-7dc866a5815f?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D10416776-40a49b6e-8f9f-463f-8f06-7dc866a5815f%26entityType%3Dcollection%26workspaceId%3D0b373f38-83d7-4257-9410-1baa18d69056)

Please let me know if you have any questions or problems @tom-kaufman

**Comment by tom-kaufman** [comment]
Thanks for taking the time to put this together! I have one personal project to wrap up before starting this next one, but I will try to read through what you provided so far, so that I can ask any questions while it's still fresh for you.

**Comment by tom-kaufman** [comment]
@GianniCarlo any chance you could point me in the right direction for authenticating? I haven't worked with iOS/Apple related development at all. I'm hoping that I don't need to be on a mac to be able to do this?

**Comment by GianniCarlo** [comment]
Hey @tom-kaufman ! they have a javascript option to do the Apple sign in too, so not necessary to be on a Mac ([link to docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple)). I was reading through it, and it looks like when doing it with popup == true, you'll get the response on the listeners (attached image)

<img width="967" alt="Screenshot 2023-08-19 at 20 16 17" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/e7332167-1e79-4f1b-9afa-d2a01a5f19df">

from that response you only need to send the `idToken` to our login endpoint. I think there are some params on the JS configuration of Apple sign in, but we can go over that on Discord 🤔

**Comment by GianniCarlo** [comment]
The repo for the api is open source now ([link](https://github.com/TortugaPower/bookplayer-api)), it's still a work in progress on how friendly it is for setup though, I'm closing this issue, and we can continue any discussion about integrations over there 👍

**Comment by tom-kaufman** [comment]
@GianniCarlo thanks for open sourcing the API! @harrisi and I have been communicating to set up a desktop app to use the API. Will be in contact if I have questions.
