### ISSUE TITLE
Bug: ... Crashes on startup

### ISSUE THREAD

**Issue by daxmonson** [TortugaPower/BookPlayer#971]
## Environment

 - OS Version: [15.7.7]
 - App Version: [5.05]

App crashes on startup after the latest install. 

## Steps to reproduce the behavior
1. Install app, start up, crash
 
Have restarted device etc. Have a ton of audiobooks in there, will they be deleted if I delete the app and install again, or will they be offloaded and come back? Is there a testflight link available to try that might work?

**Comment by GianniCarlo** [comment]
I forgot to follow up here, over Discord I mentioned I submitted a TestFlight build for review that addresses this. For discoverability I'll post here as well when the beta is ready for install

**Comment by GianniCarlo** [comment]
The beta is ready, for anyone experiencing this, you can join via this link: https://testflight.apple.com/join/xLDneJXN 
Please let me know if it fixes the issue

**Comment by daxmonson** [comment]
That worked, use it daily so thanks for the super quick fix.

**Comment by GianniCarlo** [comment]
v5.0.6 is now live in the AppStore 👌
