### ISSUE TITLE
Bug: Mp3 files with long file names do not appear in Library after import

### ISSUE THREAD

**Issue by polpinty** [TortugaPower/BookPlayer#973]
## Environment

 - OS Version: 16.5.1
 - App Version: 5.0.4-3

## Description

![image](https://github.com/TortugaPower/BookPlayer/assets/121939973/97659b43-84b7-4766-b855-f761a2352bf0)

![image](https://github.com/TortugaPower/BookPlayer/assets/121939973/801b6d73-e900-4357-8263-26ec2f828216)

**Comment by GianniCarlo** [comment]
@polpinty could you share the file in some way (via support if you wish support@bookplayer.app)? it shouldn't be a problem how long the name is, or at least we don't set a limit 🤔

**Comment by polpinty** [comment]
@GianniCarlo here it is.
[https://drive.google.com/file/d/1YgIHHOwXoEzNxlAbCmdB9XxwjNf_hWru/view?usp=drivesdk]()
Actually, it is audio extracted from youtube video.

Please, let me know when i can delete the file.

**Comment by GianniCarlo** [comment]
Thanks @polpinty got the audio file, will report back later today or at the lates tomorrow with what I find

**Comment by GianniCarlo** [comment]
I ran the file through ffprobe, and it looks alright. I imported the file on my app, and it showed up (see screenshot). It looks like something else is happening here, @polpinty can you create an empty folder on the library screen? just to see if it shows up after that, maybe the 'empty screen' is being shown incorrectly 🤔 

![IMG_F6906B9BE34D-1](https://github.com/TortugaPower/BookPlayer/assets/14112819/85246faf-78fa-42ae-83e3-feded00d55a1)

**Comment by polpinty** [comment]
@GianniCarlo , nothing new. Same result after import to empty folder
![image](https://github.com/TortugaPower/BookPlayer/assets/121939973/05e36364-dbaa-488e-958a-bc0aef699e53)

**Comment by polpinty** [comment]
Normal iOS behaviour 😂
Reinstall the app (delete/install) solved the issue.
Sorry for bothering.
