### ISSUE TITLE
Bug: When importing mp3 I get Error The operation could not be completed

### ISSUE THREAD

**Issue by Mech0z** [TortugaPower/BookPlayer#979]
## Environment

 - OS Version: 16.6
 - App Version: 5.0.6

## Description

I have a 3 part audiobook where part 1 dont work in bookplayer, part 2 and 3 works.

If I play directly inside nextcloud it works fine and plays like a normal mp3 on my iphone
If I import directly from URL I get the same issue
If I play the mp3 directly on my pc it also works fine in all mediaplayers

Is there some way to get more explicit errors in the iphone app?

The codec information from VLC are the same for both files that work and dont work
![image](https://github.com/TortugaPower/BookPlayer/assets/2316684/56ff4fd7-4487-4543-80a8-c42c9825ab4d)

## Steps to reproduce the behavior
1. Import either through nextcloud or URL
2. Play
3. Error: The operation could not be completed

**Comment by GianniCarlo** [comment]
Hi @Mech0z can you share the file to [my email](mailto:gcarlo89@hotmail.com)? we usually show the localized error description, but I can look into the error code, and see if there's any additional info on it.

<img width="695" alt="Screenshot 2023-08-14 at 08 17 33" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/9c55300a-d783-4b5b-a8ca-165ac703a15f">

As another option that could work, if you're comfortable using command line tools like [FFMPEG](https://www.ffmpeg.org), you can try the command, and try playing the new file:

```bash
ffmpeg -i path/to/file.mp3 -c copy newfile.mp3
```

**Comment by GianniCarlo** [comment]
Follow up on this, when trying to load the shared item, it produces this error:
```
▿ Optional<Error>
  - some : Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12842), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x600000d40990 {Error Domain=NSOSStatusErrorDomain Code=-12842 "(null)"}}
```

From the error code reference, it only says Unknown error :/

<img width="632" alt="Screenshot 2023-08-19 at 12 41 40" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/95984cca-19ea-4978-9933-26e62848d8ba">

When inspecting with ffprobe we get the following

<img width="942" alt="Screenshot 2023-08-19 at 12 42 47" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/b4701314-d6e4-4041-a1c6-fa71f272702e">

With the two lines standing out

```
[mp3 @ 0x137904080] Skipping 5 bytes of junk at 25333.
[mp3 @ 0x137904080] Estimating duration from bitrate, this may be inaccurate
```

Posting this for anyone having a similar issue, but basically one can always try to fix the file with FFMPEG, or if the file is part of a bigger book, use an app to merge this part with another as @Mech0z did, and the resulting file shouldn't have this issue

Thanks @Mech0z for sharing the file and providing the extra info as well
