### ISSUE TITLE
FAQ Suggestion for m4b conversion on Windows (11)

### ISSUE THREAD

**Issue by mrthomnas** [TortugaPower/BookPlayer#985]
## Environment

 - Windows 11 (Related to The FAQ Specifically on converting to m4b

## Description

I tried the converter mentioned on the FAQ for Windows (Audiobook Creator), however it required quicktime and was failing for me on Windows 11. I found this project instead and it worked very well out of the box with no configuring: https://github.com/yermak/AudioBookConverter. I think it would benefit future users if you listed this in the FAQ as well.

## Steps to reproduce the behavior
1. Attempt install of Audiobook Creator on Windows 11
2. Was not able to reconcile an error with SSA.exe 'SSA: unable to initialize QuickTime for Windows MP4v2: Could not open'
3. yermak's GitHub project listed above, AudioBookConverter is more recently updated (late 2022) and worked out of the box

**Comment by mrthomnas** [comment]
I don't see a way to mark this as an "enhancement", but it's definitely not a bug, just a suggestion for the FAQ page for conversion to m4b.

**Comment by GianniCarlo** [comment]
Hi @mrthomnas ! thanks for pointing this out, I've included AudioBookConverter to the Wiki, and also added that Audiobook Creator required quicktime installed

**Comment by mrthomnas** [comment]
I missed this notification originally, but thank you for doing that!
