### ISSUE TITLE
Bug: I want to fix Recent Books Widget's spacing error and suggest a text alignment in it.

### ISSUE THREAD

**Issue by thai-d-v** [TortugaPower/BookPlayer#990]
## Environment

 - OS Version: [16.6]
 - App Version: [5.0.7-3]

### The Recent Books Widget's spacing error.

The widget distributes inequality space for book items when fewer than 4 books and 1 has a long title.
![image](https://github.com/TortugaPower/BookPlayer/assets/46838577/e09d2510-d453-410c-8249-9f542b3cc20b)

The widget should display equally like this.
![image](https://github.com/TortugaPower/BookPlayer/assets/46838577/7fe06514-9306-473f-9ef8-9fb45792c13f)

More than that, I suggest changing the title alignment to make multiline titles look more balanced.
![image](https://github.com/TortugaPower/BookPlayer/assets/46838577/744d56c3-b4a5-4e0d-8eef-e22cbaf0e1a1)

Of course, I already fixed it and I'm waiting to hear from you to create the pull request. 😁

## Steps to reproduce the behavior
1. Open this project in Xcode, and go to the file `RecentBooksWidgetView.swift`.
2. Replace `struct RecentBooksWidgetView_Previews: PreviewProvider {...}` by this code:
```swift
struct RecentBooksWidgetView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
          RecentBooksWidgetView(
            entry: LibraryEntry(date: Date(),
                                items: [.previewItem(title: "a very very very long title"),
                                        .previewItem(title: "a short title"),
                                        .previewItem(title: "a short title")],
                                theme: nil,
                                timerSeconds: 300,
                                autoplay: true))
                .previewContext(WidgetPreviewContext(family: .systemMedium))
        }
    }
}

#if DEBUG
extension SimpleLibraryItem {
  static public func previewItem(title: String) -> Self {
    SimpleLibraryItem(
      title: title,
      details: "some details",
      speed: 1,
      currentTime: 1,
      duration: 1,
      percentCompleted: 10,
      isFinished: false,
      relativePath: UUID().uuidString,
      remoteURL: nil,
      artworkURL: nil,
      orderRank: 1,
      parentFolder: nil,
      originalFileName: "",
      lastPlayDate: nil,
      type: SimpleItemType.book)
  }
}
#endif
```

**Comment by GianniCarlo** [comment]
Hi @thai-d-v ! thanks for pointing this out, and definitely if you already have the changes, please create the PR 😁. I was looking into adding a privacy section for next version so users can opt out of Sentry.io crash reporting, will probably finish that over the weekend and submit the version to the Appstore

**Comment by thai-d-v** [comment]
@GianniCarlo, this is my pull request #991. I hope that it works. 😁
