### ISSUE TITLE
Bug: I think the code indentation should be more consistent.

### ISSUE THREAD

**Issue by thai-d-v** [TortugaPower/BookPlayer#993]
## Description

I noticed that the code indentation is not consistent.
- some have 4 spaces
https://github.com/TortugaPower/BookPlayer/blob/90ba3dc04d50b10b8d54f10b68831b768a45a4aa/BookPlayerWidgetUI/RecentBooksWidgetView.swift#L163-L166

- some have 2 spaces
https://github.com/TortugaPower/BookPlayer/blob/90ba3dc04d50b10b8d54f10b68831b768a45a4aa/BookPlayer/Player/PlayerManager.swift#L134-L137

1. Which style do you like better?
2. Would you like me to fix this for you? 😁

**Comment by GianniCarlo** [comment]
ah yes, the project started out with the default 4 spaces indentation, but later I switched to 2 spaces. I've been updating that wherever I do major changes to a file, but yeah feel free to open a PR for that 😁

**Comment by thai-d-v** [comment]
@GianniCarlo can you take a look at this #994 😁
